<?php
// md2html.php: Convert /docs/*.md to .html and .php files in /views/
// .html files: Full standalone HTML documents
// .php files: Content-only for web app integration

// Directory setup
$docsDir = __DIR__ . '/../../docs/';
$viewsDir = __DIR__ . '/../views/';

$mdFiles = glob($docsDir . '*.md');

// Helper: convert Markdown to HTML (tries league/commonmark if available; fallback is basic conversion)
function markdown_to_html($md) {
    // Use league/commonmark if available
    if (class_exists('League\CommonMark\CommonMarkConverter')) {
        $converter = new League\CommonMark\CommonMarkConverter();
        return $converter->convert($md);
    }
    // Fallback: use parsedown if available
    if (class_exists('Parsedown')) {
        $pd = new Parsedown();
        return $pd->text($md);
    }
    // Naive fallback: handle only very basic stuff
    $html = htmlspecialchars($md, ENT_QUOTES, 'UTF-8');
    // Headings
    $html = preg_replace('/^###### (.*?)$/m', '<h6>$1</h6>', $html);
    $html = preg_replace('/^##### (.*?)$/m', '<h5>$1</h5>', $html);
    $html = preg_replace('/^#### (.*?)$/m', '<h4>$1</h4>', $html);
    $html = preg_replace('/^### (.*?)$/m', '<h3>$1</h3>', $html);
    $html = preg_replace('/^## (.*?)$/m', '<h2>$1</h2>', $html);
    $html = preg_replace('/^# (.*?)$/m', '<h1>$1</h1>', $html);
    // Bold/italic
    $html = preg_replace('/\*\*(.*?)\*\*/', '<strong>$1</strong>', $html);
    $html = preg_replace('/\*(.*?)\*/', '<em>$1</em>', $html);
    // Lists
    $html = preg_replace('/^\s*-\s+(.*)$/m', '<li>$1</li>', $html);
    // Paragraphs
    $html = preg_replace('/\n{2,}/', "</p><p>", $html);
    $html = '<p>' . $html . '</p>';
    // Lists blocks: wrap <li> into <ul> (very basic, not nested)
    $html = preg_replace_callback('#((<li>.*?</li>\s*)+)#s', function($m) {
        return '<ul>' . $m[1] . '</ul>';
    }, $html);
    // Restore links (very basic)
    $html = preg_replace('/\[(.+?)\]\((.+?)\)/', '<a href="$2">$1</a>', $html);
    return $html;
}

// Template for full HTML documents (standalone/offline use)
function html_template($title, $contentHtml) {
    return <<<HTML
<!-- Generated by md2html.php -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{$title}</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <style>
        body { font-family: 'Inter',system-ui,sans-serif; max-width: 730px; margin: 32px auto; background: #fafbfc; color: #23272e; line-height: 1.7; }
        h1, h2, h3 { margin-top: 2.2em; margin-bottom: 0.7em; }
        code, pre { background: #f2f3f6; border-radius: 2px; padding: 2px 4px; font-family: 'JetBrains Mono',monospace; }
        pre { padding: 12px; overflow-x: auto; }
        ul, ol { margin-left: 2em; }
        a { color: #1660b5; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
{$contentHtml}
</body>
</html>
HTML;
}

// Template for PHP content-only (web app integration)
function php_template($title, $contentHtml) {
    return <<<PHP
<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
{$contentHtml}
</div>
PHP;
}

foreach ($mdFiles as $mdFile) {
    $basename = basename($mdFile, '.md');
    echo "Processing: $basename.md\n";

    $md = file_get_contents($mdFile);

    // Extract first heading as title (fallback: filename)
    if (preg_match('/^#\s+(.+)$/m', $md, $m)) {
        $title = trim($m[1]);
    } else {
        $title = $basename;
    }

    $htmlContent = markdown_to_html($md);

    // Generate HTML file (full document)
    $htmlOutput = html_template($title, $htmlContent);
    $htmlPath = $viewsDir . $basename . '.html';
    file_put_contents($htmlPath, $htmlOutput);
    echo " -> Wrote $htmlPath\n";

    // Generate PHP file (content-only)
    $phpOutput = php_template($title, $htmlContent);
    $phpPath = $viewsDir . $basename . '.php';
    file_put_contents($phpPath, $phpOutput);
    echo " -> Wrote $phpPath\n";
}

echo "Done. Generated both .html (standalone) and .php (content-only) files.\n";

