#!/bin/bash

# Shader compilation script for Linux
# Requires: glslangValidator, bin2hex (or equivalent)

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

TOOLS_DIR="tools"
GLSL_DIR="glsl"
SPIRV_DIR="spirv"
TMP_FILE="$SPIRV_DIR/data.spv"
OUT_DATA="$SPIRV_DIR/shader_data.c"
OUT_BINDING="$SPIRV_DIR/shader_binding.c"

# Check for glslangValidator
if ! command -v glslangValidator &> /dev/null; then
    echo "Error: glslangValidator not found. Please install Vulkan SDK or add it to PATH."
    exit 1
fi

# Create directories
mkdir -p "$SPIRV_DIR"
mkdir -p "$TOOLS_DIR"

# Build bin2hex if needed
if [ ! -f "$TOOLS_DIR/bin2hex" ]; then
    if [ -f "$TOOLS_DIR/bin2hex.c" ]; then
        echo "Building bin2hex..."
        if gcc -o "$TOOLS_DIR/bin2hex" "$TOOLS_DIR/bin2hex.c" -lm 2>/dev/null; then
            echo "  bin2hex built successfully"
        else
            echo "Warning: Failed to build bin2hex. Shader data conversion may fail."
        fi
    else
        echo "Warning: bin2hex.c not found. Shader data conversion may fail."
    fi
fi

# Build bindshader if needed
if [ ! -f "$TOOLS_DIR/bindshader" ]; then
    if [ -f "$TOOLS_DIR/bindshader.c" ]; then
        echo "Building bindshader..."
        gcc -o "$TOOLS_DIR/bindshader" "$TOOLS_DIR/bindshader.c" -lm
    fi
fi

# Initialize output files
echo "// Autogenerated shader data - do not edit manually" > "$OUT_DATA"
echo "" >> "$OUT_DATA"

echo "// Autogenerated shader binding - do not edit manually" > "$OUT_BINDING"
echo "" >> "$OUT_BINDING"
echo "static void vk_set_shader_name( VkShaderModule shader, const char *name ) {" >> "$OUT_BINDING"
echo "    SET_OBJECT_NAME( shader, name, VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT );" >> "$OUT_BINDING"
echo "}" >> "$OUT_BINDING"
echo "" >> "$OUT_BINDING"
echo "void vk_bind_generated_shaders( void ){" >> "$OUT_BINDING"

# Compile fragment shaders
echo "Compiling fragment shaders..."
for f in "$GLSL_DIR"/*.frag; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .frag)
        glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_frag_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile vertex shaders
echo "Compiling vertex shaders..."
for f in "$GLSL_DIR"/*.vert; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .vert)
        glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_vert_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile geometry shaders
echo "Compiling geometry shaders..."
for f in "$GLSL_DIR"/*.geom; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .geom)
        glslangValidator -S geom -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_geom_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile compute shaders
echo "Compiling compute shaders..."
for f in "$GLSL_DIR"/*.comp; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .comp)
        # Check if shader uses ray tracing extensions (GIBS shaders)
        if grep -q "GL_EXT_ray_tracing" "$f" 2>/dev/null; then
            # Ray tracing compute shaders need vulkan1.2 target environment
            if glslangValidator -S comp --target-env vulkan1.2 -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
                if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
                    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_comp_spv"
                fi
            else
                echo "Warning: Failed to compile ray tracing compute shader: $f"
            fi
        else
            # Standard compute shaders
            if glslangValidator -S comp -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
                if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
                    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_comp_spv"
                fi
            fi
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile ray tracing shaders
# Ray tracing requires SPIR-V 1.4+ (target vulkan1.2 or higher)
echo "Compiling ray tracing shaders..."
for f in "$GLSL_DIR"/*.rgen; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rgen)
		if glslangValidator -S rgen --target-env vulkan1.2 -V -DUSE_BLUE_NOISE -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
            if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_rgen_spv"
            fi
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rmiss; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rmiss)
		if glslangValidator -S rmiss --target-env vulkan1.2 -V -DUSE_BLUE_NOISE -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
            if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_rmiss_spv"
            fi
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rchit; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rchit)
		if glslangValidator -S rchit --target-env vulkan1.2 -V -DUSE_BLUE_NOISE -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
            if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_rchit_spv"
            fi
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rahit; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rahit)
		if glslangValidator -S rahit --target-env vulkan1.2 -V -DUSE_BLUE_NOISE -I"$GLSL_DIR" -o "$TMP_FILE" "$f" >/dev/null 2>&1; then
            if [ -f "$TOOLS_DIR/bin2hex" ] && [ -f "$TMP_FILE" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "${basename}_rahit_spv"
            fi
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile template shaders
echo "Compiling template shaders..."
if [ -f "$GLSL_DIR/gen_frag.tmpl" ] && [ -f "$TOOLS_DIR/bin2hex" ]; then
    # Depth-fragment shader
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" -DUSE_CLX_IDENT -DUSE_ATEST -DUSE_DF >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_tx0_df"
    rm -f "$TMP_FILE"
    
    # Lighting shader variations
    glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_vert.tmpl" >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "vert_light" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_vert.tmpl" -DUSE_FOG >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "vert_light_fog" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_frag.tmpl" >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_light" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_frag.tmpl" -DUSE_FOG >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_light_fog" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_frag.tmpl" -DUSE_LINE >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_light_line" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/light_frag.tmpl" -DUSE_LINE -DUSE_FOG >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_light_line_fog" 2>/dev/null
    rm -f "$TMP_FILE"
    
    # Entity color shaders
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" -DUSE_ENT_COLOR -DUSE_ATEST >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_tx0_ent" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" -DUSE_ENT_COLOR -DUSE_ATEST -DUSE_FOG >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_tx0_ent_fog" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" -DUSE_ENT_COLOR -DUSE_ATEST -DUSE_VK_PBR >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_pbr_tx0_ent" 2>/dev/null
    rm -f "$TMP_FILE"
    
    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" -DUSE_ENT_COLOR -DUSE_ATEST -DUSE_FOG -DUSE_VK_PBR >/dev/null 2>&1
    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "frag_pbr_tx0_ent_fog" 2>/dev/null
    rm -f "$TMP_FILE"
    
    # Compile identity/fixed shader variations (matches Windows batch script)
    # Vertex shaders: shading mode (0-1) × tx (0-1) × mode (0-1) × fog (0-1) × env (0-1)
    for sh_idx in 0 1; do
        if [ $sh_idx -eq 0 ]; then
            sh_flag=""
            sh_id=""
        else
            sh_flag="-DUSE_VK_PBR"
            sh_id="pbr_"
        fi
        
        for tx_idx in 0 1; do
            if [ $tx_idx -eq 0 ]; then
                tx_flag=""
                tx_id="tx0"
            else
                tx_flag="-DUSE_TX1"
                tx_id="tx1"
            fi
            
            for mode_idx in 0 1; do
                if [ $mode_idx -eq 0 ]; then
                    mode_flag="-DUSE_CLX_IDENT"
                    mode_id="ident1"
                else
                    mode_flag="-DUSE_FIXED_COLOR"
                    mode_id="fixed"
                fi
                
                for fog_idx in 0 1; do
                    if [ $fog_idx -eq 0 ]; then
                        fog_flag=""
                        fog_id=""
                    else
                        fog_flag="-DUSE_FOG"
                        fog_id="_fog"
                    fi
                    
                    for env_idx in 0 1; do
                        if [ $env_idx -eq 0 ]; then
                            env_flag=""
                            env_id=""
                        else
                            env_flag="-DUSE_ENV"
                            env_id="_env"
                        fi
                        
                        # Compile vertex shader
                        vert_name="vert_${sh_id}${tx_id}_${mode_id}${env_id}${fog_id}"
                        compile_flags="$sh_flag $tx_flag $mode_flag $env_flag $fog_flag"
                        glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_vert.tmpl" $compile_flags >/dev/null 2>&1
                        if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$vert_name" 2>/dev/null
                            # Generate binding code
                            echo "    vk.modules.vert.${mode_id}[${sh_idx}][${tx_idx}][${env_idx}][${fog_idx}] = SHADER_MODULE( ${vert_name} );" >> "$OUT_BINDING"
                            echo "    vk_set_shader_name( vk.modules.vert.${mode_id}[${sh_idx}][${tx_idx}][${env_idx}][${fog_idx}], \"${vert_name}\" );" >> "$OUT_BINDING"
                        fi
                        rm -f "$TMP_FILE"
                    done
                done
            done
        done
    done
    
    # Fragment shaders for identity/fixed: shading mode (0-1) × tx (0-1) × mode (0-1) × fog (0-1)
    for sh_idx in 0 1; do
        if [ $sh_idx -eq 0 ]; then
            sh_flag=""
            sh_id=""
        else
            sh_flag="-DUSE_VK_PBR"
            sh_id="pbr_"
        fi
        
        for tx_idx in 0 1; do
            if [ $tx_idx -eq 0 ]; then
                tx_flag=""
                tx_id="tx0"
            else
                tx_flag="-DUSE_TX1"
                tx_id="tx1"
            fi
            
            for mode_idx in 0 1; do
                if [ $mode_idx -eq 0 ]; then
                    mode_flag="-DUSE_CLX_IDENT"
                    mode_id="ident1"
                else
                    mode_flag="-DUSE_FIXED_COLOR"
                    mode_id="fixed"
                fi
                
                for fog_idx in 0 1; do
                    if [ $fog_idx -eq 0 ]; then
                        fog_flag=""
                        fog_id=""
                    else
                        fog_flag="-DUSE_FOG"
                        fog_id="_fog"
                    fi
                    
                    # Build compile flags (add USE_ATEST for tx0)
                    compile_flags="$sh_flag $tx_flag $mode_flag $fog_flag"
                    if [ $tx_idx -eq 0 ]; then
                        compile_flags="$compile_flags -DUSE_ATEST"
                    fi
                    
                    # Compile fragment shader
                    frag_name="frag_${sh_id}${tx_id}_${mode_id}${fog_id}"
                    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" $compile_flags >/dev/null 2>&1
                    if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                        "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$frag_name" 2>/dev/null
                        # Generate binding code
                        echo "    vk.modules.frag.${mode_id}[${sh_idx}][${tx_idx}][${fog_idx}] = SHADER_MODULE( ${frag_name} );" >> "$OUT_BINDING"
                        echo "    vk_set_shader_name( vk.modules.frag.${mode_id}[${sh_idx}][${tx_idx}][${fog_idx}], \"${frag_name}\" );" >> "$OUT_BINDING"
                    fi
                    rm -f "$TMP_FILE"
                done
            done
        done
    done
    
    # Compile generic shader variations (matches Windows batch script)
    # Vertex shaders: shading mode (0-1) × tx (0-2) × env (0-1) × fog (0-1), with +cl variants when tx != 0
    for sh_idx in 0 1; do
        if [ $sh_idx -eq 0 ]; then
            sh_flag=""
            sh_id=""
        else
            sh_flag="-DUSE_VK_PBR"
            sh_id="pbr_"
        fi
        
        for tx_idx in 0 1 2; do
            if [ $tx_idx -eq 0 ]; then
                tx_flag=""
                tx_id="tx0"
            elif [ $tx_idx -eq 1 ]; then
                tx_flag="-DUSE_TX1"
                tx_id="tx1"
            else
                tx_flag="-DUSE_TX2"
                tx_id="tx2"
            fi
            
            for env_idx in 0 1; do
                if [ $env_idx -eq 0 ]; then
                    env_flag=""
                    env_id=""
                else
                    env_flag="-DUSE_ENV"
                    env_id="_env"
                fi
                
                for fog_idx in 0 1; do
                    if [ $fog_idx -eq 0 ]; then
                        fog_flag=""
                        fog_id=""
                    else
                        fog_flag="-DUSE_FOG"
                        fog_id="_fog"
                    fi
                    
                    # Base vertex shader (without cl)
                    vert_name="vert_${sh_id}${tx_id}${env_id}${fog_id}"
                    compile_flags="$sh_flag $tx_flag $env_flag $fog_flag"
                    glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_vert.tmpl" $compile_flags >/dev/null 2>&1
                    if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                        "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$vert_name" 2>/dev/null
                        # Generate binding code
                        echo "    vk.modules.vert.gen[${sh_idx}][${tx_idx}][0][${env_idx}][${fog_idx}] = SHADER_MODULE( ${vert_name} );" >> "$OUT_BINDING"
                        echo "    vk_set_shader_name( vk.modules.vert.gen[${sh_idx}][${tx_idx}][0][${env_idx}][${fog_idx}], \"${vert_name}\" );" >> "$OUT_BINDING"
                    fi
                    rm -f "$TMP_FILE"
                    
                    # +cl variant (only when tx != 0)
                    if [ $tx_idx -ne 0 ]; then
                        if [ $tx_idx -eq 1 ]; then
                            cl_flag="-DUSE_CL1"
                        else
                            cl_flag="-DUSE_CL2"
                        fi
                        vert_name="vert_${sh_id}${tx_id}_cl${env_id}${fog_id}"
                        compile_flags="$sh_flag $tx_flag $cl_flag $env_flag $fog_flag"
                        glslangValidator -S vert -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_vert.tmpl" $compile_flags >/dev/null 2>&1
                        if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$vert_name" 2>/dev/null
                            # Generate binding code
                            echo "    vk.modules.vert.gen[${sh_idx}][${tx_idx}][1][${env_idx}][${fog_idx}] = SHADER_MODULE( ${vert_name} );" >> "$OUT_BINDING"
                            echo "    vk_set_shader_name( vk.modules.vert.gen[${sh_idx}][${tx_idx}][1][${env_idx}][${fog_idx}], \"${vert_name}\" );" >> "$OUT_BINDING"
                        fi
                        rm -f "$TMP_FILE"
                    fi
                done
            done
        done
    done
    
    # Fragment shaders for generic: shading mode (0-1) × tx (0-2) × fog (0-1), with +cl variants when tx != 0
    for sh_idx in 0 1; do
        if [ $sh_idx -eq 0 ]; then
            sh_flag=""
            sh_id=""
        else
            sh_flag="-DUSE_VK_PBR"
            sh_id="pbr_"
        fi
        
        for tx_idx in 0 1 2; do
            if [ $tx_idx -eq 0 ]; then
                tx_flag=""
                tx_id="tx0"
            elif [ $tx_idx -eq 1 ]; then
                tx_flag="-DUSE_TX1"
                tx_id="tx1"
            else
                tx_flag="-DUSE_TX2"
                tx_id="tx2"
            fi
            
            for fog_idx in 0 1; do
                if [ $fog_idx -eq 0 ]; then
                    fog_flag=""
                    fog_id=""
                else
                    fog_flag="-DUSE_FOG"
                    fog_id="_fog"
                fi
                
                # Build compile flags (add USE_ATEST for tx0)
                compile_flags="$sh_flag $tx_flag $fog_flag"
                if [ $tx_idx -eq 0 ]; then
                    compile_flags="$compile_flags -DUSE_ATEST"
                fi
                
                # Base fragment shader (without cl)
                frag_name="frag_${sh_id}${tx_id}${fog_id}"
                glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" $compile_flags >/dev/null 2>&1
                if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                    "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$frag_name" 2>/dev/null
                    # Generate binding code
                    echo "    vk.modules.frag.gen[${sh_idx}][${tx_idx}][0][${fog_idx}] = SHADER_MODULE( ${frag_name} );" >> "$OUT_BINDING"
                    echo "    vk_set_shader_name( vk.modules.frag.gen[${sh_idx}][${tx_idx}][0][${fog_idx}], \"${frag_name}\" );" >> "$OUT_BINDING"
                fi
                rm -f "$TMP_FILE"
                
                # +cl variant (only when tx != 0)
                if [ $tx_idx -ne 0 ]; then
                    if [ $tx_idx -eq 1 ]; then
                        cl_flag="-DUSE_CL1"
                    else
                        cl_flag="-DUSE_CL2"
                    fi
                    frag_name="frag_${sh_id}${tx_id}_cl${fog_id}"
                    compile_flags="$sh_flag $tx_flag $cl_flag $fog_flag"
                    glslangValidator -S frag -V -I"$GLSL_DIR" -o "$TMP_FILE" "$GLSL_DIR/gen_frag.tmpl" $compile_flags >/dev/null 2>&1
                    if [ $? -eq 0 ] && [ -f "$TMP_FILE" ]; then
                        "$TOOLS_DIR/bin2hex" "$TMP_FILE" "+$OUT_DATA" "$frag_name" 2>/dev/null
                        # Generate binding code
                        echo "    vk.modules.frag.gen[${sh_idx}][${tx_idx}][1][${fog_idx}] = SHADER_MODULE( ${frag_name} );" >> "$OUT_BINDING"
                        echo "    vk_set_shader_name( vk.modules.frag.gen[${sh_idx}][${tx_idx}][1][${fog_idx}], \"${frag_name}\" );" >> "$OUT_BINDING"
                    fi
                    rm -f "$TMP_FILE"
                fi
            done
        done
    done
fi

# Close the binding function
echo "}" >> "$OUT_BINDING"

echo "Shader compilation complete!"
echo "Output: $OUT_DATA"
echo "Binding: $OUT_BINDING"

