#!/bin/bash

# Shader compilation script for Linux
# Requires: glslangValidator, bin2hex (or equivalent)

set -e

TOOLS_DIR="tools"
GLSL_DIR="glsl"
SPIRV_DIR="spirv"
TMP_FILE="$SPIRV_DIR/data.spv"
OUT_DATA="$SPIRV_DIR/shader_data.c"
OUT_BINDING="$SPIRV_DIR/shader_binding.c"

# Check for glslangValidator
if ! command -v glslangValidator &> /dev/null; then
    echo "Error: glslangValidator not found. Please install Vulkan SDK or add it to PATH."
    exit 1
fi

# Create directories
mkdir -p "$SPIRV_DIR"
mkdir -p "$TOOLS_DIR"

# Build bin2hex if needed
if [ ! -f "$TOOLS_DIR/bin2hex" ]; then
    if [ -f "$TOOLS_DIR/bin2hex.c" ]; then
        echo "Building bin2hex..."
        gcc -o "$TOOLS_DIR/bin2hex" "$TOOLS_DIR/bin2hex.c" -lm
    else
        echo "Warning: bin2hex.c not found. Shader data conversion may fail."
    fi
fi

# Build bindshader if needed
if [ ! -f "$TOOLS_DIR/bindshader" ]; then
    if [ -f "$TOOLS_DIR/bindshader.c" ]; then
        echo "Building bindshader..."
        gcc -o "$TOOLS_DIR/bindshader" "$TOOLS_DIR/bindshader.c" -lm
    fi
fi

# Initialize output files
echo "// Autogenerated shader data - do not edit manually" > "$OUT_DATA"
echo "#include \"shader_data.h\"" >> "$OUT_DATA"
echo "" >> "$OUT_DATA"

echo "// Autogenerated shader binding - do not edit manually" > "$OUT_BINDING"
echo "#include \"shader_binding.h\"" >> "$OUT_BINDING"
echo "" >> "$OUT_BINDING"

# Compile fragment shaders
echo "Compiling fragment shaders..."
for f in "$GLSL_DIR"/*.frag; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .frag)
        echo "  $basename.frag"
        glslangValidator -S frag -V -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_frag_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile vertex shaders
echo "Compiling vertex shaders..."
for f in "$GLSL_DIR"/*.vert; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .vert)
        echo "  $basename.vert"
        glslangValidator -S vert -V -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_vert_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile geometry shaders
echo "Compiling geometry shaders..."
for f in "$GLSL_DIR"/*.geom; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .geom)
        echo "  $basename.geom"
        glslangValidator -S geom -V -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_geom_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile compute shaders
echo "Compiling compute shaders..."
for f in "$GLSL_DIR"/*.comp; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .comp)
        echo "  $basename.comp"
        glslangValidator -S comp -V -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_comp_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile ray tracing shaders
echo "Compiling ray tracing shaders..."
for f in "$GLSL_DIR"/*.rgen; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rgen)
        echo "  $basename.rgen"
        glslangValidator -S rgen -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_rgen_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rmiss; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rmiss)
        echo "  $basename.rmiss"
        glslangValidator -S rmiss -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_rmiss_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rchit; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rchit)
        echo "  $basename.rchit"
        glslangValidator -S rchit -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_rchit_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

for f in "$GLSL_DIR"/*.rahit; do
    if [ -f "$f" ]; then
        basename=$(basename "$f" .rahit)
        echo "  $basename.rahit"
        glslangValidator -S rahit -V -I"$GLSL_DIR" -o "$TMP_FILE" "$f"
        if [ -f "$TOOLS_DIR/bin2hex" ]; then
            "$TOOLS_DIR/bin2hex" "$TMP_FILE" "$OUT_DATA" "${basename}_rahit_spv"
        fi
        rm -f "$TMP_FILE"
    fi
done

# Compile template shaders (if needed)
if [ -f "$GLSL_DIR/gen_frag.tmpl" ]; then
    echo "Compiling template shaders..."
    # Add template compilation here if needed
fi

echo "Shader compilation complete!"
echo "Output: $OUT_DATA"

