#version 460
#extension GL_EXT_ray_tracing : require

layout(location = 0) rayPayloadEXT vec3 hitValue;

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2D outImage;

void main()
{
	const vec3 origin = vec3( 0.0, 0.0, -5.0 );
	const vec3 direction = vec3( 0.0, 0.0, 1.0 );
	traceRayEXT( topLevelAS, gl_RayFlagsOpaqueEXT, 0xFFu, 0u, 0u, 0u, origin, 0.001, direction, 100.0, 0 );
	imageStore( outImage, ivec2( gl_LaunchIDEXT.xy ), vec4( hitValue, 1.0 ) );
}
