#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) uniform sampler2D currentDepthTexture;
layout(binding = 1, r32f) uniform writeonly image2D previousDepthTexture;

void main() {
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(previousDepthTexture);
	if (any(greaterThanEqual(pixel, size))) {
		return;
	}

	float depth = texelFetch(currentDepthTexture, pixel, 0).r;
	imageStore(previousDepthTexture, pixel, vec4(depth, 0.0, 0.0, 1.0));
}
