# Phase 5d: export CMake source lists for MSVC vcxproj sync.
# Enable: cmake -DIDTECH3_EXPORT_MSVC_MANIFEST=ON ...
# Output: ${CMAKE_BINARY_DIR}/msvc_source_manifest.json

macro(_idtech3_manifest_escape_json str out_var)
	string(REPLACE "\\" "\\\\" _s "${str}")
	string(REPLACE "\"" "\\\"" _s "${_s}")
	set(${out_var} "${_s}")
endmacro()

macro(_idtech3_manifest_append_sources json_var first_src_var list_var)
	set(_srcs ${${list_var}})
	if(NOT _srcs)
		return()
	endif()
	set(_first ${${first_src_var}})
	foreach(_src ${_srcs})
		if(_src MATCHES "\\.rule$")
			continue()
		endif()
		if(NOT IS_ABSOLUTE "${_src}")
			set(_abs "${CMAKE_SOURCE_DIR}/${_src}")
		else()
			set(_abs "${_src}")
		endif()
		if(NOT EXISTS "${_abs}")
			continue()
		endif()
		get_filename_component(_abs "${_abs}" REALPATH)
		file(RELATIVE_PATH _rel "${CMAKE_SOURCE_DIR}" "${_abs}")
		_idtech3_manifest_escape_json("${_rel}" _esc)
		if(NOT _first)
			string(APPEND ${json_var} ",")
		else()
			set(_first FALSE)
		endif()
		string(APPEND ${json_var} "\"${_esc}\"")
	endforeach()
	set(${first_src_var} ${_first})
endmacro()

macro(_idtech3_manifest_append_group json_var first_group_var group_name list_var)
	if(NOT DEFINED ${list_var})
		return()
	endif()
	set(_first_g ${${first_group_var}})
	if(NOT _first_g)
		string(APPEND ${json_var} ",")
	else()
		set(_first_g FALSE)
	endif()
	string(APPEND ${json_var} "\"${group_name}\":[")
	set(_first_src TRUE)
	_idtech3_manifest_append_sources(${json_var} _first_src ${list_var})
	string(APPEND ${json_var} "]")
	set(${first_group_var} ${_first_g})
endmacro()

macro(idtech3_export_msvc_manifest)
	if(NOT IDTECH3_EXPORT_MSVC_MANIFEST)
		return()
	endif()

	set(_json "{")
	set(_first_group TRUE)
	_idtech3_manifest_append_group(_json _first_group "qcommon" QCOMMON_SRCS)
	_idtech3_manifest_append_group(_json _first_group "server" SERVER_SRCS)
	_idtech3_manifest_append_group(_json _first_group "client" CLIENT_SRCS)
	_idtech3_manifest_append_group(_json _first_group "botlib" BOTLIB_SRCS)
	if(DEFINED RENDERER_VK_SRCS)
		_idtech3_manifest_append_group(_json _first_group "renderer_vulkan" RENDERER_VK_SRCS)
	endif()
	if(DEFINED RENDERER_COMMON_SRCS)
		_idtech3_manifest_append_group(_json _first_group "renderer_common" RENDERER_COMMON_SRCS)
	endif()
	string(APPEND _json "}")

	set(_out "${CMAKE_BINARY_DIR}/msvc_source_manifest.json")
	file(WRITE "${_out}" "${_json}")
	message(STATUS "MSVC manifest: ${_out}")
endmacro()
