// Autogenerated shader binding - do not edit manually

static void vk_set_shader_name( VkShaderModule shader, const char *name ) {
    SET_OBJECT_NAME( shader, name, VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT );
}

void vk_bind_generated_shaders( void ){
    vk.modules.dot_vs = SHADER_MODULE(dot_vert_spv);
    vk.modules.dot_fs = SHADER_MODULE(dot_frag_spv);
    vk.modules.fog_vs = SHADER_MODULE(fog_vert_spv);
    vk.modules.fog_fs = SHADER_MODULE(fog_frag_spv);
    vk.modules.color_vs = SHADER_MODULE(color_vert_spv);
    vk.modules.color_fs = SHADER_MODULE(color_frag_spv);
    vk.modules.filtercube_vs = SHADER_MODULE(filtercube_vert_spv);
    vk.modules.filtercube_gm = SHADER_MODULE(filtercube_geom_spv);
    vk.modules.irradiancecube_fs = SHADER_MODULE(irradiancecube_frag_spv);
    vk.modules.prefilterenvmap_fs = SHADER_MODULE(prefilterenvmap_frag_spv);
    vk.modules.bloom_fs = SHADER_MODULE(bloom_frag_spv);
    vk.modules.blend_fs = SHADER_MODULE(blend_frag_spv);
    vk.modules.gamma_vs = SHADER_MODULE(gamma_vert_spv);
    vk.modules.gamma_fs = SHADER_MODULE(gamma_frag_spv);
    vk.modules.brdflut_fs = SHADER_MODULE(brdflut_frag_spv);
    vk.modules.bloom_comp = SHADER_MODULE(bloom_comp_spv);

    vk_set_shader_name(vk.modules.dot_vs, "dot_vs");
    vk_set_shader_name(vk.modules.dot_fs, "dot_fs");
    vk_set_shader_name(vk.modules.gamma_fs, "gamma_fs");
}
