// This file is autogenerated during shader compilation
__attribute__((used)) static void vk_set_shader_name(VkShaderModule shader, const char *name) {
    SET_OBJECT_NAME(shader, name, VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT);
}

void vk_bind_generated_shaders(void) {
    // TODO: Add shader bindings here
}
