// This file is autogenerated during shader compilation
// Shader bindings are automatically generated by the shader compilation system.
// This function is called during renderer initialization to set up shader module names
// for debugging purposes. Actual shader binding (descriptor sets, pipelines) is handled
// by the pipeline creation system in vk_pipeline.c.

__attribute__((used)) static void vk_set_shader_name(VkShaderModule shader, const char *name) {
    SET_OBJECT_NAME(shader, name, VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT);
}

void vk_bind_generated_shaders(void) {
    // Shader bindings are handled automatically by the pipeline system.
    // This function is a placeholder for any future shader-specific initialization.
    // Current implementation: Shader modules are created and named during compilation,
    // and bound to pipelines during pipeline creation (see vk_pipeline.c).
    (void)0; // Suppress unused function warning
}
