<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>AIML 2.1 Interpreter</h1></p><p>The engine now ships with a lightweight AIML 2.1 parser/interpreter written in C++23. It is available whenever `USE_AIML` is enabled (default).</p><p><h2>API surface</h2></p><p>Header: `src/common/aiml/aiml_c_api.h`
<ul><li>`AIML_LoadFile(path)`: load an AIML file from the virtual filesystem (PK3-friendly).</li>
<li>`AIML_LoadBuffer(name, data)`: load AIML from an in-memory buffer.</li>
<li>`AIML_Respond(userId, input, out, outSize)`: evaluate user input and write a reply.</li>
<li>`AIML_SetBotPredicate` / `AIML_GetBotPredicate`: configure bot properties exposed via `&lt;bot name=&quot;...&quot;/&gt;`.</li>
<li>`AIML_ResetSession(userId)` / `AIML_ResetAllSessions()`: clear per-user state.</li></ul></p><p>The interpreter is initialized in `Qcommon_Init` and torn down in `Com_Shutdown`, so modules can call into it without extra setup.</p><p><h2>Supported AIML features</h2>
<ul><li>Categories with `pattern`, optional `that`, and optional `topic` (including `&lt;topic&gt;` blocks).</li>
<li>Wildcards (`*` and `_`) with capture for `&lt;star&gt;`, `&lt;thatstar&gt;`, and `&lt;topicstar&gt;`.</li>
<li>Template evaluation: `&lt;random&gt;&lt;li&gt;...&lt;/li&gt;&lt;/random&gt;`, `&lt;condition&gt;` (simple name/value forms), `&lt;set&gt;`, `&lt;get&gt;`, `&lt;bot&gt;`, `&lt;srai&gt;`, `&lt;think&gt;`, and case transforms (`&lt;uppercase&gt;`, `&lt;lowercase&gt;`, `&lt;formal&gt;`, `&lt;sentence&gt;`).</li>
<li>Per-user predicates, bot properties, and topic tracking (`&lt;set name=&quot;topic&quot;&gt;`).</li>
<li>Basic whitespace normalization and punctuation stripping for matching.</li></ul></p><p><h2>Usage example</h2></p><p>```c
char response[512];
if (AIML_LoadFile(&quot;scripts/chat.aiml&quot;) &amp;&amp; AIML_Respond(&quot;player1&quot;, &quot;Hello there&quot;, response, sizeof(response))) {
	Com_Printf(&quot;Bot: %s\n&quot;, response);
}
```</p><p>A minimal example file lives at `tests/aiml_sample.aiml` and can be loaded directly for smoke testing.</p><p><h2>Notes and limitations</h2>
<ul><li>XML parsing is intentionally conservative; malformed AIML will be rejected with a log message.</li>
<li>Recursion depth for `&lt;srai&gt;` is capped to avoid runaway loops.</li>
<li>If no category matches an input, the interpreter returns an empty string.</li></ul></p><p></p>
</div>