<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Asset Validation</h1></p><p><h2>Overview</h2></p><p>The asset validation tool (`tools/validate_assets.py`) provides comprehensive validation of game assets in mod directories, checking for missing references, bad paths, invalid metadata, manifest integrity, duplicate assets, and orphaned files.</p><p><h2>Features</h2></p><p><h3>Validation Checks</h3></p><p>1. <strong>Missing Asset References</strong>
<ul><li>Scans shader files for texture references</li>
<li>Scans map files for texture references</li>
<li>Reports missing textures, models, sounds</li></ul></p><p>2. <strong>Bad Paths</strong>
<ul><li>Checks for paths exceeding MAX_QPATH (256 characters)</li>
<li>Detects illegal characters (`..`, `\`, `:`)</li>
<li>Validates path format (no absolute paths)</li></ul></p><p>3. <strong>Invalid Files</strong>
<ul><li>Detects empty files</li>
<li>Validates file readability</li>
<li>Checks for corrupted files</li></ul></p><p>4. <strong>Manifest Integrity</strong>
<ul><li>Validates `manifest.json` structure</li>
<li>Verifies all manifest entries exist</li>
<li>Checks file hash integrity</li></ul></p><p>5. <strong>Duplicate Assets</strong>
<ul><li>Identifies duplicate files by content hash</li>
<li>Reports files with identical content</li></ul></p><p>6. <strong>Orphaned Assets</strong>
<ul><li>Finds assets not referenced in manifest</li>
<li>Identifies assets not used in shaders/maps</li></ul></p><p><h2>Usage</h2></p><p><h3>Basic Validation</h3></p><p>```bash
<h1>Validate assets in a mod directory</h1>
python3 tools/validate_assets.py mymod</p><p><h1>Or use the executable directly</h1>
./tools/validate_assets.py mymod
```</p><p><h3>Advanced Options</h3></p><p>```bash
<h1>Skip manifest validation</h1>
python3 tools/validate_assets.py mymod --no-check-manifest</p><p><h1>Check for orphaned assets</h1>
python3 tools/validate_assets.py mymod --check-orphans</p><p><h1>Verbose output</h1>
python3 tools/validate_assets.py mymod --verbose</p><p><h1>JSON output (for CI/automation)</h1>
python3 tools/validate_assets.py mymod --json
```</p><p><h3>Full Validation</h3></p><p>```bash
<h1>Run all checks including manifest and orphaned assets</h1>
python3 tools/validate_assets.py mymod --check-manifest --check-orphans --verbose
```</p><p><h2>Output Format</h2></p><p><h3>Standard Output</h3></p><p>The tool provides a detailed report with errors categorized by severity:</p><p>```
======================================================================
ASSET VALIDATION REPORT
======================================================================</p><p>ERRORS (2):
  [ERROR] missing: Shader references missing texture: textures/common/missing (file: shaders/test.shader)
  [ERROR] bad_path: Path too long (257 &gt;= 256): textures/very/long/path/to/texture/that/exceeds/maximum/path/length/texture.tga</p><p>WARNINGS (1):
  [WARNING] invalid: Empty file: sounds/missing.wav</p><p>INFO (1):
  [INFO] duplicate: Duplicate files found (hash: a1b2c3d4...): textures/duplicate1.tga, textures/duplicate2.tga</p><p>======================================================================
Summary: 2 errors, 1 warnings, 1 info messages
======================================================================
```</p><p><h3>JSON Output</h3></p><p>For CI/CD integration, use `--json` flag:</p><p>```json
{
  &quot;success&quot;: false,
  &quot;errors&quot;: [
    {
      &quot;severity&quot;: &quot;error&quot;,
      &quot;category&quot;: &quot;missing&quot;,
      &quot;message&quot;: &quot;Shader references missing texture: textures/common/missing&quot;,
      &quot;file&quot;: &quot;shaders/test.shader&quot;,
      &quot;line&quot;: null
    }
  ],
  &quot;stats&quot;: {
    &quot;total_assets&quot;: 150,
    &quot;pk3_files&quot;: 3,
    &quot;manifest_assets&quot;: 145,
    &quot;references&quot;: 200
  }
}
```</p><p><h2>Supported Asset Formats</h2></p><p><h3>Images</h3>
<ul><li>`.tga`, `.jpg`, `.jpeg`, `.png`, `.pcx`, `.bmp`, `.dds`, `.svg`, `.exr`</li></ul></p><p><h3>Models</h3>
<ul><li>`.md3`, `.ase`, `.obj`</li></ul></p><p><h3>Sounds</h3>
<ul><li>`.wav`, `.ogg`</li></ul></p><p><h3>Other</h3>
<ul><li>`.shader` (shader definitions)</li>
<li>`.map` (map source files)</li>
<li>`.bsp` (compiled maps)</li>
<li>`.pk3` (zip archives)</li></ul></p><p><h2>CI/CD Integration</h2></p><p><h3>GitHub Actions</h3></p><p>Add asset validation to your CI workflow:</p><p>```yaml
<ul><li>name: Validate Assets</li>
  </ul>run: |
    python3 tools/validate_assets.py mymod --json &gt; validation_results.json
    if [ $? -ne 0 ]; then
      echo &quot;Asset validation failed&quot;
      cat validation_results.json
      exit 1
    fi
```</p><p><h3>Pre-commit Hook</h3></p><p>Add to `.git/hooks/pre-commit`:</p><p>```bash
#!/bin/bash
<h1>Validate assets before commit</h1>
python3 tools/validate_assets.py mymod --check-manifest
if [ $? -ne 0 ]; then
    echo &quot;Asset validation failed. Please fix errors before committing.&quot;
    exit 1
fi
```</p><p><h2>Exit Codes</h2>
<ul><li>`0`: Validation passed (no errors)</li>
<li>`1`: Validation failed (errors found)</li></ul></p><p><h2>Best Practices</h2></p><p>1. <strong>Run validation before commits</strong>: Catch issues early
2. <strong>Use manifest validation</strong>: Ensure manifest.json is up to date
3. <strong>Check for orphans</strong>: Remove unused assets to reduce package size
4. <strong>Fix errors first</strong>: Address errors before warnings
5. <strong>Use JSON output in CI</strong>: Parse results programmatically</p><p><h2>Troubleshooting</h2></p><p><h3>&quot;Mod directory does not exist&quot;</h3>
<ul><li>Ensure you&#039;re running from the project root</li>
<li>Check that the mod directory path is correct</li></ul></p><p><h3>&quot;Failed to read shader file&quot;</h3>
<ul><li>Check file permissions</li>
<li>Ensure files are UTF-8 encoded</li>
<li>Verify file is not corrupted</li></ul></p><p><h3>&quot;Hash mismatch&quot;</h3>
<ul><li>File may have been modified after manifest was generated</li>
<li>Regenerate manifest with `tools/update_manifest.py`</li></ul></p><p><h3>&quot;Path too long&quot;</h3>
<ul><li>Reduce path depth or filename length</li>
<li>Consider reorganizing directory structure</li></ul></p><p><h2>Related Tools</h2>
<ul><li>`tools/update_manifest.py`: Generate/update manifest.json</li>
<li>`tools/package_mod.sh`: Package mod with validated assets</li>
<li>`tools/package_release.sh`: Create release packages</li></ul></p><p><h2>See Also</h2>
<ul><li><a href="ASSET_PIPELINE.md">Asset Pipeline Documentation</a></li>
<li><a href="MANIFEST_FORMAT.md">Manifest Format Documentation</a></li>
<li><a href="cicd.md">CI/CD Documentation</a></li>
</ul></p>
</div>