<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Backwards Compatibility Strategy</h1></p><p><h2>Overview</h2></p><p>This document outlines the comprehensive strategy for maintaining backwards compatibility across all engine subsystems, ensuring that mods, save games, network protocols, and assets continue to work across engine versions.</p><p><h2>Table of Contents</h2></p><p>1. <a href="#core-principles">Core Principles</a>
2. <a href="#protocol-versioning">Protocol Versioning</a>
3. <a href="#save-game-compatibility">Save Game Compatibility</a>
4. <a href="#qvm-compatibility">QVM Compatibility</a>
5. <a href="#asset-format-compatibility">Asset Format Compatibility</a>
6. <a href="#api-versioning">API Versioning</a>
7. <a href="#feature-detection">Feature Detection</a>
8. <a href="#deprecation-policy">Deprecation Policy</a>
9. <a href="#testing-strategy">Testing Strategy</a>
10. <a href="#migration-tools">Migration Tools</a></p><p><h2>Core Principles</h2></p><p><h3>1. Never Break Existing Content</h3>
<ul><li>Legacy mods must continue to work</li>
<li>Old save games must be loadable</li>
<li>Network protocols must support older clients</li>
<li>Asset formats must remain readable</li></ul></p><p><h3>2. Graceful Degradation</h3>
<ul><li>New features are optional</li>
<li>Missing features fail gracefully</li>
<li>Provide fallbacks for unsupported features</li>
<li>Clear error messages for incompatibilities</li></ul></p><p><h3>3. Version Everything</h3>
<ul><li>Network protocols are versioned</li>
<li>Save games include version numbers</li>
<li>Asset formats have version headers</li>
<li>APIs have version numbers</li></ul></p><p><h3>4. Feature Detection Over Assumptions</h3>
<ul><li>Query capabilities before use</li>
<li>Don&#039;t assume features exist</li>
<li>Provide detection mechanisms</li>
<li>Document feature availability</li></ul></p><p><h2>Protocol Versioning</h2></p><p><h3>Current Protocol Versions</h3></p><p>```c
#define PROTOCOL_VERSION_66    66  // Legacy Quake 3
#define PROTOCOL_VERSION_67   67  // Quake 3 1.31
#define OLD_PROTOCOL_VERSION  68  // Q3E older version
#define NEW_PROTOCOL_VERSION  71  // Q3E current version
#define DEFAULT_PROTOCOL_VERSION OLD_PROTOCOL_VERSION
```</p><p><h3>Protocol Negotiation</h3></p><p><strong>Current State</strong>: Basic protocol version checking exists, but no formal negotiation.</p><p><strong>Recommended Implementation:</strong></p><p>```c
typedef struct {
    int protocolVersion;
    uint32_t featureFlags;      // Bitmask of supported features
    qboolean strictMode;         // Strict compatibility mode
    qboolean allowExtensions;    // Allow protocol extensions
} protocolCapabilities_t;</p><p>// Negotiate protocol during connection
qboolean NET_NegotiateProtocol(netadr_t <em>from, protocolCapabilities_t </em>capabilities);</p><p>// Check if feature is supported
qboolean NET_HasFeature(int protocolVersion, uint32_t featureFlag);
```</p><p><h3>Feature Flags</h3></p><p>Define feature flags for protocol extensions:</p><p>```c
#define PROTO_FEATURE_COMPRESSED_SNAPSHOTS    (1 &lt;&lt; 0)
#define PROTO_FEATURE_DELTA_COMPRESSION      (1 &lt;&lt; 1)
#define PROTO_FEATURE_EXTENDED_ENTITIES      (1 &lt;&lt; 2)
#define PROTO_FEATURE_LARGE_MAPS              (1 &lt;&lt; 3)
#define PROTO_FEATURE_ENHANCED_PLAYERSTATE    (1 &lt;&lt; 4)
```</p><p><h3>Compatibility Modes</h3></p><p><strong>Strict Mode</strong>: Only use features available in both client and server protocol versions.</p><p><strong>Loose Mode</strong>: Use best available features, fallback gracefully.</p><p><strong>Implementation:</strong>
```c
// Server side
if (client-&gt;protocolVersion &lt; NEW_PROTOCOL_VERSION) {
    // Use legacy snapshot format
    SV_BuildLegacySnapshot(client);
} else {
    // Use enhanced snapshot format
    SV_BuildEnhancedSnapshot(client);
}
```</p><p><h3>Protocol Migration</h3></p><p><strong>Strategy:</strong>
1. Support multiple protocol versions simultaneously
2. Negotiate highest common version
3. Use feature flags for optional features
4. Maintain legacy code paths
5. Document deprecation timeline</p><p><h2>Save Game Compatibility</h2></p><p><h3>Current State</h3></p><p>Some save systems include basic versioning (e.g., inventory system), but no unified framework.</p><p><h3>Recommended Save Format</h3></p><p>```c
// Save file header
typedef struct {
    char magic[4];           // &quot;Q3SV&quot; or similar
    uint32_t version;        // Save format version
    uint32_t engineVersion;  // Engine version that created save
    uint32_t checksum;       // Data integrity check
    uint32_t dataSize;       // Size of save data
    time_t timestamp;        // Save timestamp
} saveFileHeader_t;
```</p><p><h3>Versioned Serialization</h3></p><p>```c
// Serialization context
typedef struct {
    uint32_t version;        // Format version being read/written
    qboolean strict;         // Strict mode (fail on unknown fields)
    void *userData;          // User context
} serializeContext_t;</p><p>// Versioned save function
qboolean Save_WriteVersioned(serializeContext_t <em>ctx, const void </em>data, size_t size);
qboolean Save_ReadVersioned(serializeContext_t <em>ctx, void </em>data, size_t size);
```</p><p><h3>Migration Framework</h3></p><p><strong>Automatic Migration:</strong>
```c
// Migration function signature
typedef qboolean (<em>SaveMigrateFunc_t)(serializeContext_t </em>from, 
                                      serializeContext_t *to,
                                      void *data);</p><p>// Register migration function
void Save_RegisterMigration(uint32_t fromVersion, uint32_t toVersion, 
                           SaveMigrateFunc_t migrateFunc);</p><p>// Migrate save file
qboolean Save_Migrate(const char *filename, uint32_t targetVersion);
```</p><p><strong>Example Migration:</strong>
```c
// Migrate from version 1 to version 2
qboolean MigrateV1ToV2(serializeContext_t <em>from, serializeContext_t </em>to, void *data) {
    oldSaveFormat_t <em>old = (oldSaveFormat_t </em>)data;
    newSaveFormat_t <em>new = (newSaveFormat_t </em>)Z_TagMalloc(sizeof(newSaveFormat_t), TAG_TEMP);
    
    // Copy compatible fields
    new-&gt;playerHealth = old-&gt;playerHealth;
    new-&gt;playerArmor = old-&gt;playerArmor;
    
    // Set defaults for new fields
    new-&gt;playerStamina = 100;  // New field, use default
    
    // Write migrated data
    return Save_WriteVersioned(to, new, sizeof(newSaveFormat_t));
}
```</p><p><h3>Save Corruption Recovery</h3></p><p><strong>Atomic Writes:</strong>
```c
// Write to temporary file first
char tempPath[MAX_QPATH];
Com_sprintf(tempPath, sizeof(tempPath), &quot;%s.tmp&quot;, savePath);</p><p>// Write save data
if (Save_WriteFile(tempPath, data)) {
    // Atomic rename
    FS_Rename(tempPath, savePath);
    return qtrue;
} else {
    FS_Remove(tempPath);
    return qfalse;
}
```</p><p><strong>Backup System:</strong>
```c
// Create backup before writing
void Save_CreateBackup(const char *savePath) {
    char backupPath[MAX_QPATH];
    Com_sprintf(backupPath, sizeof(backupPath), &quot;%s.bak&quot;, savePath);
    FS_CopyFile(savePath, backupPath);
}</p><p>// Restore from backup on corruption
qboolean Save_RestoreBackup(const char *savePath) {
    char backupPath[MAX_QPATH];
    Com_sprintf(backupPath, sizeof(backupPath), &quot;%s.bak&quot;, savePath);
    
    if (FS_FileExists(backupPath)) {
        return FS_CopyFile(backupPath, savePath);
    }
    return qfalse;
}
```</p><p><strong>Checksum Validation:</strong>
```c
uint32_t Save_CalculateChecksum(const void *data, size_t size) {
    uint32_t checksum = 0;
    const uint32_t <em>words = (const uint32_t </em>)data;
    size_t wordCount = size / sizeof(uint32_t);
    
    for (size_t i = 0; i &lt; wordCount; i++) {
        checksum ^= words[i];
        checksum = (checksum &lt;&lt; 1) | (checksum &gt;&gt; 31);
    }
    return checksum;
}
```</p><p><h2>QVM Compatibility</h2></p><p>See <a href="QVM_COMPATIBILITY.md">QVM Compatibility Documentation</a> for detailed information.</p><p><h3>Key Points</h3></p><p>1. <strong>Always Maintain QVM Support</strong>: QVM is the fallback for all mods
2. <strong>Extension Syscalls</strong>: New features via extensions, not standard syscalls
3. <strong>Feature Detection</strong>: QVMs query for extension availability
4. <strong>Graceful Degradation</strong>: Missing extensions fail gracefully</p><p><h3>Extension System</h3></p><p>```c
// Query for extension availability
qboolean VM_Ext_HasFeature(vm_t <em>vm, const char </em>featureName);</p><p>// Get extension version
int VM_Ext_GetVersion(vm_t <em>vm, const char </em>featureName);</p><p>// Example usage in QVM
if (VM_Ext_HasFeature(vm, &quot;CVar_SetDescription&quot;)) {
    trap_Cvar_SetDescription_Q3E(name, description);
} else {
    // Fallback: just set the CVar
    trap_Cvar_Set(name, value);
}
```</p><p><h2>Asset Format Compatibility</h2></p><p><h3>Asset Versioning</h3></p><p><strong>Manifest Format:</strong>
```json
{
  &quot;manifestVersion&quot;: 1,
  &quot;bundleVersion&quot;: &quot;1.0.0&quot;,
  &quot;gameName&quot;: &quot;mymod&quot;,
  &quot;assets&quot;: [
    {
      &quot;path&quot;: &quot;textures/test.tga&quot;,
      &quot;hash&quot;: &quot;abc123...&quot;,
      &quot;formatVersion&quot;: 1,
      &quot;dependencies&quot;: []
    }
  ]
}
```</p><p><h3>Format Detection</h3></p><p>```c
// Detect asset format version
int Asset_DetectFormatVersion(const char *filename);</p><p>// Read with version handling
qboolean Asset_LoadVersioned(const char <em>filename, int expectedVersion, void </em>data);
```</p><p><h3>Format Migration</h3></p><p><strong>Texture Formats:</strong>
<ul><li>Support legacy formats (TGA, JPG, PNG)</li>
<li>Auto-convert to modern formats when possible</li>
<li>Preserve originals for compatibility</li></ul></p><p><strong>Model Formats:</strong>
<ul><li>Support MD3, ASE, OBJ</li>
<li>Convert to optimized formats</li>
<li>Maintain source compatibility</li></ul></p><p><strong>Shader Formats:</strong>
<ul><li>Support legacy shader syntax</li>
<li>Auto-upgrade where possible</li>
<li>Document breaking changes</li></ul></p><p><h2>API Versioning</h2></p><p><h3>Engine API Version</h3></p><p>```c
// Engine API version
#define ENGINE_API_VERSION_MAJOR 1
#define ENGINE_API_VERSION_MINOR 0
#define ENGINE_API_VERSION_PATCH 0</p><p>// Get engine API version
void Engine_GetAPIVersion(int <em>major, int </em>minor, int *patch);
```</p><p><h3>Module API Versioning</h3></p><p><strong>Syscall Registry:</strong>
```c
// Register syscall with version
void Syscall_Register(const char *name, int number, int minVersion, int maxVersion);</p><p>// Check syscall availability
qboolean Syscall_IsAvailable(const char *name, int apiVersion);
```</p><p><h3>Plugin API Versioning</h3></p><p>```c
// Plugin API version check
typedef struct {
    int apiVersion;
    const char *engineVersion;
    uint32_t featureFlags;
} pluginAPIInfo_t;</p><p>qboolean Plugin_CheckAPIVersion(pluginAPIInfo_t *info);
```</p><p><h2>Feature Detection</h2></p><p><h3>Runtime Feature Detection</h3></p><p><strong>Engine Features:</strong>
```c
typedef enum {
    FEATURE_VULKAN_RENDERER,
    FEATURE_TRACY_PROFILER,
    FEATURE_MEMORY_TRACKING,
    FEATURE_HOT_RELOAD,
    FEATURE_EVENT_SYSTEM,
    FEATURE_STRUCTURED_LOGGING,
    // ...
} engineFeature_t;</p><p>qboolean Engine_HasFeature(engineFeature_t feature);
const char *Engine_GetFeatureVersion(engineFeature_t feature);
```</p><p><strong>Renderer Features:</strong>
```c
qboolean R_HasExtension(const char *extension);
int R_GetMaxTextureSize(void);
qboolean R_SupportsCompressedTextures(void);
```</p><p><strong>Network Features:</strong>
```c
qboolean NET_HasFeature(int protocolVersion, uint32_t featureFlag);
qboolean NET_SupportsCompression(void);
```</p><p><h3>Capability Queries</h3></p><p><strong>Server Capabilities:</strong>
```c
typedef struct {
    int protocolVersion;
    uint32_t featureFlags;
    int maxClients;
    qboolean pure;
    // ...
} serverCapabilities_t;</p><p>qboolean CL_GetServerCapabilities(netadr_t <em>server, serverCapabilities_t </em>caps);
```</p><p><strong>Client Capabilities:</strong>
```c
typedef struct {
    int protocolVersion;
    uint32_t featureFlags;
    const char *renderer;
    // ...
} clientCapabilities_t;</p><p>void CL_SendCapabilities(clientCapabilities_t *caps);
```</p><p><h2>Deprecation Policy</h2></p><p><h3>Deprecation Timeline</h3></p><p>1. <strong>Announcement</strong>: Feature marked as deprecated in documentation
2. <strong>Warning Period</strong>: 2-3 engine versions with warnings
3. <strong>Removal</strong>: Feature removed after deprecation period</p><p><h3>Deprecation Macros</h3></p><p>```c
// Mark function as deprecated
#define DEPRECATED(msg) __attribute__((deprecated(msg)))</p><p>// Example
DEPRECATED(&quot;Use NewFunction() instead&quot;)
void OldFunction(void);</p><p>// Compile-time warning
#if defined(__GNUC__) || defined(__clang__)
    #define DEPRECATED_FUNCTION(name, replacement) \
        __attribute__((deprecated(&quot;Use &quot; replacement &quot; instead&quot;)))
#else
    #define DEPRECATED_FUNCTION(name, replacement)
#endif
```</p><p><h3>Runtime Deprecation Warnings</h3></p><p>```c
// Warn on deprecated feature use
void Com_DeprecatedWarning(const char <em>feature, const char </em>replacement) {
    static qboolean warned = qfalse;
    if (!warned) {
        Com_Printf(&quot;WARNING: %s is deprecated. Use %s instead.\n&quot;, 
                   feature, replacement);
        warned = qtrue;
    }
}
```</p><p><h2>Testing Strategy</h2></p><p><h3>Compatibility Test Suite</h3></p><p><strong>Automated Tests:</strong>
```c
// Test protocol compatibility
TEST(protocol_compatibility_v66) {
    // Test with protocol version 66
    ASSERT_TRUE(NET_ConnectWithProtocol(PROTOCOL_VERSION_66));
}</p><p>// Test save game migration
TEST(save_migration_v1_to_v2) {
    // Create v1 save
    Save_CreateV1Save(&quot;test_v1.save&quot;);
    
    // Migrate to v2
    ASSERT_TRUE(Save_Migrate(&quot;test_v1.save&quot;, 2));
    
    // Verify migration
    ASSERT_TRUE(Save_Load(&quot;test_v1.save&quot;));
}
```</p><p><h3>Legacy Content Testing</h3></p><p><strong>Test Matrix:</strong>
<ul><li>Old QVM mods (Urban Terror, Defrag, OpenArena)</li>
<li>Old save games (various versions)</li>
<li>Old network protocols (66, 67, 68)</li>
<li>Old asset formats (legacy textures, models)</li></ul></p><p><strong>CI Integration:</strong>
```yaml
<h1>Test legacy compatibility</h1>
<ul><li>name: Test Legacy QVMs</li>
  </ul>run: |
    ./tools/test_legacy_qvms.sh
<ul><li>name: Test Save Game Migration</li>
  </ul>run: |
    ./tools/test_save_migration.sh
```</p><p><h3>Golden File Testing</h3></p><p><strong>Save Golden Files:</strong>
<ul><li>Known-good save files for each version</li>
<li>Test loading and migration</li>
<li>Verify data integrity</li></ul></p><p><strong>Protocol Golden Packets:</strong>
<ul><li>Capture network packets from old versions</li>
<li>Test parsing and compatibility</li>
<li>Verify feature negotiation</li></ul></p><p><h2>Migration Tools</h2></p><p><h3>Save Game Migration Tool</h3></p><p>```bash
<h1>Command-line tool for migrating save games</h1>
./tools/migrate_save.sh old_save.save new_version
```</p><p><strong>Implementation:</strong>
```c
int main(int argc, char <em></em>argv) {
    if (argc &lt; 3) {
        printf(&quot;Usage: migrate_save &lt;savefile&gt; &lt;target_version&gt;\n&quot;);
        return 1;
    }
    
    const char *savePath = argv[1];
    int targetVersion = atoi(argv[2]);
    
    if (Save_Migrate(savePath, targetVersion)) {
        printf(&quot;Successfully migrated %s to version %d\n&quot;, savePath, targetVersion);
        return 0;
    } else {
        printf(&quot;Failed to migrate %s\n&quot;, savePath);
        return 1;
    }
}
```</p><p><h3>Protocol Compatibility Checker</h3></p><p>```bash
<h1>Check protocol compatibility</h1>
./tools/check_protocol_compat.sh server_address
```</p><p><h3>Asset Format Converter</h3></p><p>```bash
<h1>Convert assets to new format</h1>
./tools/convert_assets.sh --from-version 1 --to-version 2 mod_directory
```</p><p><h2>Implementation Priorities</h2></p><p><h3>Phase 1: Foundation (High Priority)</h3></p><p>1. <strong>Protocol Negotiation</strong>
<ul><li>Implement feature flags</li>
<li>Add protocol capability queries</li>
<li>Support multiple protocol versions</li></ul></p><p>2. <strong>Save Game Framework</strong>
<ul><li>Unified save format header</li>
<li>Version detection</li>
<li>Basic migration framework</li></ul></p><p>3. <strong>Feature Detection</strong>
<ul><li>Engine feature queries</li>
<li>Renderer capability checks</li>
<li>Network feature flags</li></ul></p><p><h3>Phase 2: Migration (Medium Priority)</h3></p><p>1. <strong>Save Migration</strong>
<ul><li>Automatic migration functions</li>
<li>Backup/restore system</li>
<li>Corruption recovery</li></ul></p><p>2. <strong>Asset Migration</strong>
<ul><li>Format converters</li>
<li>Version detection</li>
<li>Compatibility layers</li></ul></p><p>3. <strong>Protocol Migration</strong>
<ul><li>Legacy protocol support</li>
<li>Feature negotiation</li>
<li>Graceful degradation</li></ul></p><p><h3>Phase 3: Tooling (Lower Priority)</h3></p><p>1. <strong>Migration Tools</strong>
<ul><li>Save game migrator</li>
<li>Asset converter</li>
<li>Compatibility checker</li></ul></p><p>2. <strong>Testing Framework</strong>
<ul><li>Automated compatibility tests</li>
<li>Legacy content testing</li>
<li>Golden file validation</li></ul></p><p><h2>Best Practices</h2></p><p><h3>For Developers</h3></p><p>1. <strong>Version Everything</strong>: Always include version numbers
2. <strong>Feature Detection</strong>: Query before using features
3. <strong>Graceful Degradation</strong>: Provide fallbacks
4. <strong>Document Changes</strong>: Update compatibility docs
5. <strong>Test Legacy Content</strong>: Verify with old mods/saves</p><p><h3>For Mod Developers</h3></p><p>1. <strong>Check Features</strong>: Query for feature availability
2. <strong>Version Checks</strong>: Verify protocol/save versions
3. <strong>Fallbacks</strong>: Provide legacy code paths
4. <strong>Test Compatibility</strong>: Test with multiple engine versions
5. <strong>Report Issues</strong>: Report compatibility problems</p><p><h2>Related Documentation</h2>
<ul><li><a href="QVM_COMPATIBILITY.md">QVM Compatibility</a> - QVM-specific compatibility</li>
<li><a href="C_CPP_BOUNDARY_RULES.md">C/C++ Boundary Rules</a> - C/C++ interop rules</li>
<li><a href="entity_oop_plan.md">Entity OOP Plan</a> - OOP compatibility strategy</li>
<li><a href="ASSET_VALIDATION.md">Asset Validation</a> - Asset compatibility checking</li></ul></p><p><h2>Summary</h2></p><p><strong>Key Strategies:</strong>
1. ✅ Version all formats (protocol, save, assets, APIs)
2. ✅ Feature detection over assumptions
3. ✅ Graceful degradation for missing features
4. ✅ Migration frameworks for data formats
5. ✅ Deprecation policies with timelines
6. ✅ Comprehensive testing of legacy content
7. ✅ Migration tools for users</p><p>Following these strategies ensures that the engine maintains backwards compatibility while allowing for innovation and improvement.
</p>
</div>