<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>C/C++ Boundary Rules</h1></p><p><h2>Overview</h2></p><p>The id Tech 3 engine uses a hybrid C/C++ architecture where:
<ul><li><strong>Engine core</strong> is primarily C</li>
<li><strong>New gamecode</strong> can use C++ (OOP entities, ECS systems)</li>
<li><strong>QVM compatibility</strong> requires a stable C ABI</li>
<li><strong>Network/save serialization</strong> must use C-compatible layouts</li></ul></p><p>This document defines the rules and patterns for safely crossing the C/C++ boundary.</p><p><h2>Table of Contents</h2></p><p>1. <a href="#core-principles">Core Principles</a>
2. <a href="#function-boundaries">Function Boundaries</a>
3. <a href="#data-structure-boundaries">Data Structure Boundaries</a>
4. <a href="#memory-management">Memory Management</a>
5. <a href="#exception-handling">Exception Handling</a>
6. <a href="#rtti-and-virtual-functions">RTTI and Virtual Functions</a>
7. <a href="#examples">Examples</a>
8. <a href="#best-practices">Best Practices</a>
9. <a href="#common-pitfalls">Common Pitfalls</a></p><p><h2>Core Principles</h2></p><p><h3>1. Stable C ABI</h3>
All functions called from C code (including QVM) must be declared with `extern &quot;C&quot;` and use C-compatible calling conventions.</p><p><h3>2. POD Structs for Network/Save</h3>
Structures used for network snapshots, save games, or shared between C and C++ must be <strong>Plain Old Data (POD)</strong>:
<ul><li>No virtual functions</li>
<li>No constructors/destructors (or trivial ones)</li>
<li>No non-POD members</li>
<li>Standard layout (no access specifiers affecting layout)</li>
<li>Trivially copyable</li></ul></p><p><h3>3. No Exceptions Across Boundaries</h3>
C++ exceptions must never propagate across C boundaries. Catch all exceptions at the boundary and convert to error codes or logging.</p><p><h3>4. No RTTI Across Boundaries</h3>
Runtime Type Information (RTTI) cannot be used across C boundaries. Use explicit type tags or function pointers instead.</p><p><h2>Function Boundaries</h2></p><p><h3>Header Pattern</h3></p><p>All headers that may be included from both C and C++ must use this pattern:</p><p>```c
#ifndef __MODULE_NAME_H__
#define __MODULE_NAME_H__</p><p>#include &quot;q_shared.h&quot;</p><p>#ifdef __cplusplus
extern &quot;C&quot; {
#endif</p><p>// C-compatible function declarations
void Module_Init(void);
void Module_Shutdown(void);
qboolean Module_DoSomething(int param);</p><p>#ifdef __cplusplus
} // extern &quot;C&quot;
#endif</p><p>#endif // __MODULE_NAME_H__
```</p><p><h3>Implementation Pattern</h3></p><p>In C++ implementation files:</p><p>```cpp
#include &quot;module_name.h&quot;</p><p>#ifdef __cplusplus
extern &quot;C&quot; {
#endif</p><p>void Module_Init(void) {
    // Implementation can use C++ features internally
    // but must be callable from C
}</p><p>#ifdef __cplusplus
}
#endif
```</p><p><h3>Example: OOP Bridge</h3></p><p>See `mymod/gamesrc/game/g_oop.h`:</p><p>```c
#ifdef __cplusplus
extern &quot;C&quot; {
#endif</p><p>// C-callable functions for C++ entity system
qboolean G_OOP_CallSpawn(gentity_t <em>ent, const char </em>classname);
void G_OOP_RunFrame(int msec);</p><p>#ifdef __cplusplus
} // extern &quot;C&quot;
#endif
```</p><p><h2>Data Structure Boundaries</h2></p><p><h3>POD Requirements</h3></p><p>Structures used across boundaries must be POD. Examples:</p><p><strong>✅ Valid POD Struct:</strong>
```c
typedef struct {
    int number;
    int eType;
    vec3_t origin;
    vec3_t angles;
    int modelindex;
} entityState_t;  // Used in network snapshots
```</p><p><strong>❌ Invalid (Non-POD):</strong>
```cpp
class EntityState {  // Cannot cross C boundary
    virtual void Serialize();  // Virtual function
    std::string name;  // Non-POD member
};
```</p><p><h3>Network/Save Structs</h3></p><p>Critical structures that must remain POD:
<ul><li>`gentity_t` - Game entity structure</li>
<li>`playerState_t` - Player state for networking</li>
<li>`entityState_t` - Entity state for snapshots</li>
<li>`usercmd_t` - User commands</li>
<li>`snapshot_t` - Network snapshots</li></ul></p><p><strong>Rule</strong>: These structures must never contain:
<ul><li>Virtual functions</li>
<li>C++ classes with constructors/destructors</li>
<li>`std::string`, `std::vector`, or other STL containers</li>
<li>Smart pointers (`std::unique_ptr`, `std::shared_ptr`)</li>
<li>References</li></ul></p><p><h3>C++ Wrapper Pattern</h3></p><p>When you need C++ features, wrap POD structs:</p><p>```cpp
// POD struct (C-compatible)
struct DamageInfo {
    float amount;
    int mod;
    vec3_t direction;
    int sourceEntity;
};</p><p>// C++ wrapper (internal use only)
class DamageInfoWrapper {
    DamageInfo info;
    std::string sourceName;  // OK - internal only
    
public:
    DamageInfoWrapper(const DamageInfo&amp; base) : info(base) {}
    const DamageInfo&amp; GetPOD() const { return info; }
};
```</p><p><h2>Memory Management</h2></p><p><h3>Allocator Boundaries</h3></p><p><strong>Rule</strong>: Use the engine&#039;s zone allocator (`Z_TagMalloc`/`Z_Free`) for memory that crosses boundaries.</p><p>```c
// C side
void* ptr = Z_TagMalloc(size, TAG_GENERAL);</p><p>// C++ side (wrapped)
extern &quot;C&quot; void* AllocateEntity(int size) {
    return Z_TagMalloc(size, TAG_ENTITY);
}
```</p><p><strong>Avoid</strong>:
<ul><li>Mixing `new`/`delete` with `Z_TagMalloc`/`Z_Free` for the same object</li>
<li>Using `malloc`/`free` for boundary-crossing memory</li>
<li>STL allocators that don&#039;t use zone allocator</li></ul></p><p><h3>Smart Pointers</h3></p><p>Smart pointers (`std::unique_ptr`, `std::shared_ptr`) are fine for <strong>internal C++ code</strong> but cannot cross C boundaries:</p><p>```cpp
// ✅ OK - Internal C++ use
class EntityManager {
    std::vector&lt;std::unique_ptr&lt;BaseEntity&gt;&gt; entities;
};</p><p>// ❌ BAD - Cannot return to C
extern &quot;C&quot; std::unique_ptr&lt;BaseEntity&gt; CreateEntity();  // WRONG</p><p>// ✅ OK - Return raw pointer, manage internally
extern &quot;C&quot; BaseEntity* CreateEntity() {
    auto entity = std::make_unique&lt;BaseEntity&gt;();
    // Store in internal registry
    return entity.release();  // Transfer ownership to registry
}
```</p><p><h2>Exception Handling</h2></p><p><h3>Boundary Exception Handling</h3></p><p><strong>Rule</strong>: Catch all exceptions at C/C++ boundaries and convert to error codes:</p><p>```cpp
extern &quot;C&quot; qboolean G_OOP_CallSpawn(gentity_t <em>ent, const char </em>classname) {
    try {
        // C++ code that might throw
        return EntityRegistry::Spawn(ent, classname) ? qtrue : qfalse;
    }
    catch (const std::exception&amp; e) {
        Com_Printf(&quot;ERROR: Exception in G_OOP_CallSpawn: %s\n&quot;, e.what());
        return qfalse;
    }
    catch (...) {
        Com_Printf(&quot;ERROR: Unknown exception in G_OOP_CallSpawn\n&quot;);
        return qfalse;
    }
}
```</p><p><h3>No-Exception Builds</h3></p><p>For gamecode, consider compiling with `-fno-exceptions`:</p><p>```cmake
<h1>In CMakeLists.txt</h1>
if(BUILD_GAMECODE_CPP)
    target_compile_options(gamecode PRIVATE -fno-exceptions -fno-rtti)
endif()
```</p><p>This ensures exceptions cannot be thrown, making boundary safety easier to verify.</p><p><h2>RTTI and Virtual Functions</h2></p><p><h3>Virtual Functions</h3></p><p>Virtual functions are <strong>allowed</strong> in C++ code but cannot be called across C boundaries:</p><p>```cpp
// ✅ OK - Internal C++ use
class BaseEntity {
public:
    virtual void Think(float dt) = 0;
    virtual void Spawn() = 0;
};</p><p>// ❌ BAD - Cannot call virtual from C
extern &quot;C&quot; void Entity_Think(void* entity) {
    static_cast&lt;BaseEntity*&gt;(entity)-&gt;Think(0.016f);  // WRONG - virtual call
}</p><p>// ✅ OK - Use function pointer or type tag
extern &quot;C&quot; void Entity_Think(void* entity, int entityType) {
    switch (entityType) {
        case ENTITY_DOOR:
            static_cast&lt;DoorEntity*&gt;(entity)-&gt;Think(0.016f);
            break;
        // ...
    }
}
```</p><p><h3>Type Information</h3></p><p>Use explicit type tags instead of RTTI:</p><p>```cpp
enum EntityType {
    ENTITY_DOOR,
    ENTITY_TRIGGER,
    ENTITY_NPC,
    // ...
};</p><p>struct EntityHeader {
    EntityType type;
    // ... POD fields
};
```</p><p><h2>Examples</h2></p><p><h3>Example 1: C++ Entity System with C Bridge</h3></p><p><strong>Header (`g_oop.h`):</strong>
```c
#ifdef __cplusplus
extern &quot;C&quot; {
#endif</p><p>qboolean G_OOP_CallSpawn(gentity_t <em>ent, const char </em>classname);
void G_OOP_RunFrame(int msec);</p><p>#ifdef __cplusplus
}
#endif
```</p><p><strong>Implementation (`g_oop.cpp`):</strong>
```cpp
#include &quot;g_oop.h&quot;
#include &quot;g_oop.hpp&quot;  // C++ headers</p><p>extern &quot;C&quot; {
    qboolean G_OOP_CallSpawn(gentity_t <em>ent, const char </em>classname) {
        try {
            return EntityRegistry::Spawn(ent, classname) ? qtrue : qfalse;
        }
        catch (...) {
            Com_Printf(&quot;ERROR: Exception in G_OOP_CallSpawn\n&quot;);
            return qfalse;
        }
    }
    
    void G_OOP_RunFrame(int msec) {
        EntitySystem::Update(msec);
    }
}
```</p><p><h3>Example 2: POD Struct for Network</h3></p><p><strong>Network struct (must be POD):</strong>
```c
typedef struct {
    int number;
    vec3_t origin;
    vec3_t angles;
    int modelindex;
    // ... only POD types
} entityState_t;
```</p><p><strong>C++ wrapper (internal use):</strong>
```cpp
class EntityStateWrapper {
    entityState_t state;
    
public:
    EntityStateWrapper(const entityState_t&amp; s) : state(s) {}
    
    // C++ convenience methods
    vec3_t GetOrigin() const { return state.origin; }
    void SetOrigin(const vec3_t&amp; origin) {
        VectorCopy(origin, state.origin);
    }
    
    // Get POD for network serialization
    const entityState_t&amp; GetPOD() const { return state; }
};
```</p><p><h3>Example 3: Error Handling</h3></p><p>```cpp
extern &quot;C&quot; qboolean LoadEntityData(const char<em> filename, void</em> buffer, int size) {
    try {
        std::ifstream file(filename, std::ios::binary);
        if (!file) {
            return qfalse;
        }
        
        file.read(static_cast&lt;char*&gt;(buffer), size);
        return file.good() ? qtrue : qfalse;
    }
    catch (const std::ios_base::failure&amp; e) {
        Com_Printf(&quot;ERROR: File I/O error: %s\n&quot;, e.what());
        return qfalse;
    }
    catch (...) {
        Com_Printf(&quot;ERROR: Unknown error loading entity data\n&quot;);
        return qfalse;
    }
}
```</p><p><h2>Best Practices</h2></p><p><h3>1. Header Guards</h3></p><p>Always use include guards and `extern &quot;C&quot;`:</p><p>```c
#ifndef __MODULE_H__
#define __MODULE_H__</p><p>#ifdef __cplusplus
extern &quot;C&quot; {
#endif</p><p>// ... declarations</p><p>#ifdef __cplusplus
}
#endif</p><p>#endif
```</p><p><h3>2. Separate C and C++ Headers</h3></p><p>For complex modules, consider separate headers:
<ul><li>`module.h` - C-compatible API</li>
<li>`module.hpp` - C++-only API (internal use)</li></ul></p><p><h3>3. Type Safety</h3></p><p>Use strong types for boundary parameters:</p><p>```c
// ✅ Good - explicit types
typedef struct {
    int x, y, z;
} vec3i_t;</p><p>void SetPosition(vec3i_t pos);</p><p>// ❌ Bad - ambiguous
void SetPosition(int x, int y, int z);  // Easy to mix up parameters
```</p><p><h3>4. Documentation</h3></p><p>Document boundary-crossing functions:</p><p>```c
/<em></em>
 * Spawns an entity using the C++ OOP system.
 * 
 * @param ent Pointer to gentity_t (POD struct, C-compatible)
 * @param classname Entity classname string
 * @return qtrue if spawned successfully, qfalse otherwise
 * 
 * @note This function catches all C++ exceptions and converts to qfalse.
 * @note The gentity_t structure must remain POD-compatible.
 */
extern &quot;C&quot; qboolean G_OOP_CallSpawn(gentity_t <em>ent, const char </em>classname);
```</p><p><h3>5. Testing</h3></p><p>Test boundary functions from both C and C++:</p><p>```cpp
// C++ test
TEST(cpp_boundary_test) {
    gentity_t ent;
    ASSERT_TRUE(G_OOP_CallSpawn(&amp;ent, &quot;func_door&quot;));
}</p><p>// C test (if possible)
void test_c_boundary(void) {
    gentity_t ent;
    qboolean result = G_OOP_CallSpawn(&amp;ent, &quot;func_door&quot;);
    assert(result == qtrue);
}
```</p><p><h2>Common Pitfalls</h2></p><p><h3>❌ Pitfall 1: Virtual Functions in POD Structs</h3></p><p>```cpp
// WRONG
struct EntityState {
    virtual void Serialize();  // Makes struct non-POD
};
```</p><p><strong>Fix</strong>: Use function pointers or separate serialization functions.</p><p><h3>❌ Pitfall 2: Exceptions Crossing Boundaries</h3></p><p>```cpp
// WRONG
extern &quot;C&quot; void DoSomething() {
    throw std::runtime_error(&quot;error&quot;);  // Exception crosses boundary
}
```</p><p><strong>Fix</strong>: Catch exceptions at boundary:</p><p>```cpp
extern &quot;C&quot; void DoSomething() {
    try {
        // ... code that might throw
    }
    catch (...) {
        Com_Printf(&quot;ERROR: Exception caught\n&quot;);
    }
}
```</p><p><h3>❌ Pitfall 3: STL Containers in POD Structs</h3></p><p>```cpp
// WRONG
struct NetworkPacket {
    std::vector&lt;char&gt; data;  // Non-POD member
};
```</p><p><strong>Fix</strong>: Use C arrays or pointers:</p><p>```c
struct NetworkPacket {
    char data[MAX_PACKET_SIZE];
    int size;
};
```</p><p><h3>❌ Pitfall 4: Mixing Allocators</h3></p><p>```cpp
// WRONG
extern &quot;C&quot; void* CreateEntity() {
    return new Entity();  // Uses new/delete, not zone allocator
}
```</p><p><strong>Fix</strong>: Use zone allocator:</p><p>```cpp
extern &quot;C&quot; void* CreateEntity() {
    return Z_TagMalloc(sizeof(Entity), TAG_ENTITY);
}
```</p><p><h3>❌ Pitfall 5: Missing extern &quot;C&quot;</h3></p><p>```cpp
// WRONG - Missing extern &quot;C&quot;
void Module_Init(void);  // C++ name mangling breaks C calls
```</p><p><strong>Fix</strong>: Use extern &quot;C&quot;:</p><p>```cpp
#ifdef __cplusplus
extern &quot;C&quot; {
#endif
void Module_Init(void);
#ifdef __cplusplus
}
#endif
```</p><p><h2>Compiler Flags</h2></p><p>Recommended flags for C++ gamecode:</p><p>```cmake
<h1>Disable exceptions and RTTI for boundary safety</h1>
target_compile_options(gamecode PRIVATE
    -fno-exceptions
    -fno-rtti
    -Wall
    -Wextra
)</p><p><h1>Ensure standard layout</h1>
target_compile_definitions(gamecode PRIVATE
    -DUSE_STD_LAYOUT=1
)
```</p><p><h2>Verification</h2></p><p><h3>Static Analysis</h3></p><p>Use `static_assert` to verify POD requirements:</p><p>```cpp
#include &lt;type_traits&gt;</p><p>static_assert(std::is_pod_v&lt;entityState_t&gt;, 
    &quot;entityState_t must be POD for network compatibility&quot;);
static_assert(std::is_trivially_copyable_v&lt;gentity_t&gt;,
    &quot;gentity_t must be trivially copyable&quot;);
```</p><p><h3>Runtime Checks</h3></p><p>Add runtime validation in debug builds:</p><p>```cpp
#ifdef _DEBUG
void ValidatePODStruct(const void* ptr, size_t size) {
    // Check alignment, padding, etc.
    assert(reinterpret_cast&lt;uintptr_t&gt;(ptr) % alignof(max_align_t) == 0);
}
#endif
```</p><p><h2>Related Documentation</h2>
<ul><li><a href="entity_oop_plan.md">Entity OOP Plan</a> - OOP entity system design</li>
<li><a href="QVM_COMPATIBILITY.md">QVM Compatibility</a> - QVM-specific considerations</li>
<li><a href="MODERN_CPP_FEATURES.md">Modern C++ Features</a> - C++ features usage guidelines</li></ul></p><p><h2>Summary</h2></p><p><strong>Key Rules:</strong>
1. ✅ Use `extern &quot;C&quot;` for all C-callable functions
2. ✅ Keep network/save structs as POD
3. ✅ Catch exceptions at boundaries
4. ✅ Use zone allocator for boundary memory
5. ✅ Avoid RTTI/virtual functions across boundaries
6. ✅ Document boundary functions clearly
7. ✅ Test from both C and C++ sides</p><p>Following these rules ensures safe, maintainable C/C++ interoperation while preserving QVM compatibility and network protocol stability.
</p>
</div>