<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Configurable Application Naming Tutorial</h1></p><p>This tutorial explains how to use the idTech3 engine&#039;s configurable naming system to create branded applications for different games and mods.</p><p><h2>🎯 Overview</h2></p><p>The idTech3 engine supports configurable application naming, allowing you to:
<ul><li>Remove hardcoded Quake3/Quake3e references</li>
<li>Brand the engine for specific games or mods</li>
<li>Create proper package names for app stores</li>
<li>Maintain separate data directories for different applications</li></ul></p><p><h2>📋 Prerequisites</h2>
<ul><li>idTech3 engine source code</li>
<li>CMake (3.20+)</li>
<li>Platform-specific build tools (Visual Studio, Xcode, Android NDK, etc.)</li></ul></p><p><h2>🚀 Quick Start</h2></p><p><h3>Basic Usage</h3></p><p>```bash
<h1>Build with default idTech3 branding</h1>
cmake -S . -B build
cmake --build build</p><p><h1>Build with custom mod name</h1>
cmake -S . -B build -DMOD_NAME=&quot;MyGame&quot;
cmake --build build
```</p><p><h3>Android Builds</h3></p><p>```bash
<h1>Use the automated Android build script</h1>
./build_android.sh &quot;MyAwesomeGame&quot; Release</p><p><h1>Or configure manually</h1>
cmake -S . -B build \
    -DMOD_NAME=&quot;MyAwesomeGame&quot; \
    -DUSE_ANDROID=ON \
    -DUSE_VULKAN=ON
cmake --build build
```</p><p><h2>🔧 Configuration Options</h2></p><p><h3>CMake Variables</h3></p><p>| Variable | Description | Default | Example |
|----------|-------------|---------|---------|
| `MOD_NAME` | Game/mod display name | (none) | `&quot;SpaceRunner&quot;` |
| `ENGINE_NAME` | Engine display name | `&quot;idTech3&quot;` | `&quot;MyEngine&quot;` |
| `APP_DISPLAY_NAME` | Application display name | `ENGINE_NAME` | `&quot;Space Runner&quot;` |
| `APP_PACKAGE_NAME` | Android package name | `&quot;com.idtech3.engine&quot;` | `&quot;com.spacestudio.runner&quot;` |
| `CNAME` | Executable/library name | `&quot;idtech3&quot;` | `&quot;spacerunner&quot;` |
| `DNAME` | Dedicated server name | `&quot;idtech3.server&quot;` | `&quot;spacerunner.server&quot;` |</p><p><h3>Build Script Parameters</h3></p><p>The `build_android.sh` script accepts:</p><p>```bash
./build_android.sh [mod_name] [build_type]
```
<ul><li>`mod_name`: Display name for your game/mod (default: &quot;idTech3&quot;)</li>
<li>`build_type`: CMake build type - Debug/Release (default: &quot;Release&quot;)</li></ul></p><p><h2>📱 Platform-Specific Examples</h2></p><p><h3>Desktop (Windows/Linux/macOS)</h3></p><p><h4>Example 1: Custom Game Branding</h4></p><p>```bash
<h1>Configure for a space-themed game</h1>
cmake -S . -B build \
    -DMOD_NAME=&quot;SpaceRunner&quot; \
    -DAPP_DISPLAY_NAME=&quot;Space Runner&quot; \
    -DCMAKE_BUILD_TYPE=Release</p><p><h1>Build</h1>
cmake --build build --config Release</p><p><h1>Result: Executable named &quot;spacerunner.exe&quot; (Windows) or &quot;spacerunner&quot; (Linux/macOS)</h1>
```</p><p><h4>Example 2: Tournament Mod</h4></p><p>```bash
<h1>Configure for competitive gameplay</h1>
cmake -S . -B build \
    -DMOD_NAME=&quot;ArenaMasters&quot; \
    -DAPP_DISPLAY_NAME=&quot;Arena Masters Tournament&quot; \
    -DCMAKE_BUILD_TYPE=Release</p><p><h1>Build</h1>
cmake --build build --config Release
```</p><p><h3>Android Mobile</h3></p><p><h4>Using Build Script (Recommended)</h4></p><p>```bash
<h1>Simple build</h1>
./build_android.sh &quot;RacingChamp&quot; Release</p><p><h1>This automatically:</h1>
<h1>- Sets display name to &quot;RacingChamp&quot;</h1>
<h1>- Creates package name &quot;com.racingchamp.game&quot;</h1>
<h1>- Updates Android manifest</h1>
<h1>- Renames Java activity class</h1>
<h1>- Configures build settings</h1>
```</p><p><h4>Manual CMake Configuration</h4></p><p>```bash
<h1>Advanced configuration</h1>
cmake -S . -B build \
    -DMOD_NAME=&quot;RacingChamp&quot; \
    -DAPP_DISPLAY_NAME=&quot;Racing Championship&quot; \
    -DAPP_PACKAGE_NAME=&quot;com.racingstudio.championship&quot; \
    -DUSE_ANDROID=ON \
    -DUSE_VULKAN=ON \
    -DCMAKE_BUILD_TYPE=Release</p><p><h1>Build APK</h1>
cmake --build build --config Release
```</p><p><h4>iOS/tvOS</h4></p><p>```bash
<h1>Configure for iOS</h1>
cmake -S . -B build \
    -DMOD_NAME=&quot;PuzzleQuest&quot; \
    -DAPP_DISPLAY_NAME=&quot;Puzzle Quest Adventures&quot; \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_ARCHITECTURES=&quot;arm64;x86_64&quot; \
    -DUSE_METAL=ON</p><p><h1>Build Xcode project</h1>
cmake --build build --config Release
```</p><p><h2>📁 File Structure Changes</h2></p><p>When you build with a custom mod name, the following files are automatically updated:</p><p><h3>Android Files</h3>
```
android/
├── AndroidManifest.xml          # Package name updated
├── IdTech3Activity.java         # Renamed to [ModName]Activity.java
└── ...
```</p><p><h3>Build Outputs</h3>
```
build/
├── idtech3                      # Default executable
├── spacerunner                  # Custom named executable
├── spacerunner.server           # Custom named server
└── ...
```</p><p><h3>Data Directories (Runtime)</h3>
```
<h1>Android</h1>
/sdcard/Android/data/com.spacerunner.game/files/
/sdcard/Android/data/com.spacerunner.game/cache/</p><p><h1>Desktop (varies by platform)</h1>
~/spacerunner/                    # User data directory
spacerunner/                      # Working directory
```</p><p><h2>🛠️ Advanced Configuration</h2></p><p><h3>Custom Package Names</h3></p><p>```cmake
<h1>Advanced Android configuration</h1>
set(MOD_NAME &quot;MyGame&quot; CACHE STRING &quot;Game name&quot;)
set(APP_PACKAGE_NAME &quot;com.mystudio.mygame&quot; CACHE STRING &quot;Android package&quot;)
set(APP_DISPLAY_NAME &quot;My Awesome Game&quot; CACHE STRING &quot;Display name&quot;)</p><p><h1>Generate version codes</h1>
set(APP_VERSION_CODE 100 CACHE STRING &quot;Android version code&quot;)
set(APP_VERSION_NAME &quot;1.0.0&quot; CACHE STRING &quot;Android version name&quot;)
```</p><p><h3>Multi-Platform Branding</h3></p><p>```bash
#!/bin/bash
<h1>build_all_platforms.sh</h1></p><p>MOD_NAME=&quot;EpicQuest&quot;
BUILD_TYPE=&quot;Release&quot;</p><p>echo &quot;Building $MOD_NAME for all platforms...&quot;</p><p><h1>Android</h1>
./build_android.sh &quot;$MOD_NAME&quot; &quot;$BUILD_TYPE&quot;</p><p><h1>Windows</h1>
cmake -S . -B build_windows \
    -DMOD_NAME=&quot;$MOD_NAME&quot; \
    -DCMAKE_BUILD_TYPE=&quot;$BUILD_TYPE&quot; \
    -G &quot;Visual Studio 17 2022&quot;
cmake --build build_windows --config &quot;$BUILD_TYPE&quot;</p><p><h1>Linux</h1>
cmake -S . -B build_linux \
    -DMOD_NAME=&quot;$MOD_NAME&quot; \
    -DCMAKE_BUILD_TYPE=&quot;$BUILD_TYPE&quot;
cmake --build build_linux</p><p><h1>macOS</h1>
cmake -S . -B build_macos \
    -DMOD_NAME=&quot;$MOD_NAME&quot; \
    -DCMAKE_BUILD_TYPE=&quot;$BUILD_TYPE&quot; \
    -DCMAKE_OSX_ARCHITECTURES=&quot;arm64;x86_64&quot;
cmake --build build_macos
```</p><p><h3>CI/CD Integration</h3></p><p>```yaml
<h1>.github/workflows/build.yml</h1>
name: Build Game
on: [push, pull_request]</p><p>jobs:
  build:
    strategy:
      matrix:
        mod: [&quot;BaseGame&quot;, &quot;Tournament&quot;, &quot;CustomMod&quot;]
        platform: [&quot;windows&quot;, &quot;linux&quot;, &quot;android&quot;]</p><p>    steps:
<ul><li>uses: actions/checkout@v3</li>
<li>name: Configure CMake</li>
      </ul>run: |
        cmake -S . -B build \
          -DMOD_NAME=&quot;${{ matrix.mod }}&quot; \
          -DCMAKE_BUILD_TYPE=Release
<ul><li>name: Build</li>
      </ul>run: cmake --build build --config Release
<ul><li>name: Package</li>
      </ul>run: |
        # Create platform-specific packages
        # with proper naming
```</p><p><h2>🔍 Troubleshooting</h2></p><p><h3>Common Issues</h3></p><p><h4>1. &quot;MOD_NAME variable not recognized&quot;</h4></p><p><strong>Problem</strong>: CMake doesn&#039;t recognize the MOD_NAME variable.</p><p><strong>Solution</strong>: Make sure you&#039;re using CMake 3.20+ and the variable is set before the project() command or use -DMOD_NAME=&quot;Value&quot; on the command line.</p><p><h4>2. Android package name conflicts</h4></p><p><strong>Problem</strong>: Package name already exists on device.</p><p><strong>Solution</strong>: Use a unique package name:</p><p>```bash
./build_android.sh &quot;MyGame&quot; Release
<h1>Creates: com.mygame.game</h1></p><p><h1>Or specify custom package:</h1>
cmake -DAPP_PACKAGE_NAME=&quot;com.mystudio.mygame&quot; ...
```</p><p><h4>3. Java class not found</h4></p><p><strong>Problem</strong>: Android build fails with missing Java class.</p><p><strong>Solution</strong>: The build script automatically renames Java classes. If building manually, ensure the AndroidManifest.xml references the correct class name.</p><p><h4>4. Data directory conflicts</h4></p><p><strong>Problem</strong>: Multiple games using same data directory.</p><p><strong>Solution</strong>: Each mod gets its own package name and data directory automatically. No manual intervention needed.</p><p><h3>Debug Information</h3></p><p>```bash
<h1>Check current configuration</h1>
cmake -S . -B build -LA | grep -E &quot;(MOD_NAME|APP_|ENGINE_NAME)&quot;</p><p><h1>Verify Android package</h1>
grep -n &quot;package=&quot; android/AndroidManifest.xml</p><p><h1>Check executable names</h1>
ls -la build/ | grep -E &quot;(idtech3|${MOD_NAME_LOWER})&quot;
```</p><p><h3>Reset to Defaults</h3></p><p>```bash
<h1>Clear CMake cache</h1>
rm -rf build/CMakeCache.txt build/CMakeFiles/</p><p><h1>Rebuild with defaults</h1>
cmake -S . -B build
```</p><p><h2>📋 Best Practices</h2></p><p><h3>Naming Conventions</h3></p><p>1. <strong>Use PascalCase for display names</strong>: `&quot;SpaceRunner&quot;` not `&quot;space runner&quot;`
2. <strong>Use lowercase for package names</strong>: `&quot;com.studio.game&quot;` not `&quot;com.Studio.Game&quot;`
3. <strong>Keep names descriptive</strong>: `&quot;ZombieSurvival&quot;` not `&quot;ZS&quot;`
4. <strong>Avoid special characters</strong>: Use only letters, numbers, and underscores</p><p><h3>Package Name Guidelines</h3>
<ul><li>Start with reverse domain: `com.company.game`</li>
<li>Use unique identifiers: `com.studio.gamename`</li>
<li>Keep consistent across platforms</li>
<li>Follow app store guidelines</li></ul></p><p><h3>Build Organization</h3></p><p>```bash
<h1>Recommended directory structure</h1>
project/
├── build_default/     # Default idTech3 build
├── build_my_game/     # Custom game build
├── build_android/     # Android-specific build
└── build_server/     # Dedicated server build
```</p><p><h3>Version Management</h3></p><p>```cmake
<h1>Version configuration</h1>
set(GAME_VERSION_MAJOR 1)
set(GAME_VERSION_MINOR 0)
set(GAME_VERSION_PATCH 0)</p><p>set(APP_VERSION_NAME &quot;${GAME_VERSION_MAJOR}.${GAME_VERSION_MINOR}.${GAME_VERSION_PATCH}&quot;)
set(APP_VERSION_CODE ${GAME_VERSION_MAJOR}${GAME_VERSION_MINOR}${GAME_VERSION_PATCH})
```</p><p><h2>🎮 Example Game Configurations</h2></p><p><h3>First-Person Shooter</h3></p><p>```bash
./build_android.sh &quot;BattleZone&quot; Release
<h1>Package: com.battlezone.game</h1>
<h1>Display: BattleZone</h1>
```</p><p><h3>Racing Game</h3></p><p>```bash
./build_android.sh &quot;SpeedRacer&quot; Release
<h1>Package: com.speedracer.game</h1>
<h1>Display: SpeedRacer</h1>
```</p><p><h3>Puzzle Game</h3></p><p>```bash
./build_android.sh &quot;MindBender&quot; Release
<h1>Package: com.mindbender.game</h1>
<h1>Display: MindBender</h1>
```</p><p><h3>Strategy Game</h3></p><p>```bash
./build_android.sh &quot;EmpireBuilder&quot; Release
<h1>Package: com.empirebuilder.game</h1>
<h1>Display: EmpireBuilder</h1>
```</p><p><h2>📚 Related Documentation</h2>
<ul><li><a href="BUILD.md">BUILD.md</a> - General build instructions</li>
<li><a href="android/README.md">Android Build Guide</a> - Android-specific setup</li>
<li><a href="cmake/README.md">CMake Configuration</a> - Advanced CMake usage</li>
<li><a href="modding/README.md">Modding Guide</a> - Creating custom content</li></ul></p><p><h2>🤝 Contributing</h2></p><p>When adding new configuration options:</p><p>1. Update this document with new examples
2. Test on all supported platforms
3. Verify Android package naming works correctly
4. Update CI/CD pipelines if needed</p><p><h2>📞 Support</h2></p><p>For issues with configurable naming:</p><p>1. Check the troubleshooting section above
2. Verify CMake version (3.20+ required)
3. Test with default configuration first
4. Check platform-specific documentation</p><p>---</p><p><strong>The configurable naming system makes idTech3 a true multi-purpose engine capable of powering any game or mod with proper branding and professional presentation!</strong> 🎮✨
</p>
</div>