<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Entity OOP Plan (C++-first)</h1></p><p>Goal: adopt a Half-Life–style entity OOP model using C++ for new gamecode while keeping compatibility with existing C/QVM entry points via a stable C ABI shim.</p><p><h2>Boundary Rules</h2>
<ul><li>Engine/VM ↔ gamecode surface stays `extern &quot;C&quot;` with POD structs (no RTTI/exceptions across the boundary).</li>
<li>Net/save structs (`gentity_t`, `playerState_t`, snapshots) remain C-compatible layouts.</li>
<li>No C++ exceptions crossing the C boundary; treat gamecode as `-fno-exceptions` (or catch/translate internally).</li>
<li>Keep allocator and logging calls in the C ABI layer to avoid mixing allocators across boundaries.</li></ul></p><p><h2>Core Types (C++)</h2>
<ul><li>`class BaseEntity` with virtuals: `Spawn()`, `Precache()`, `Think(float dt)`, `ScheduleNextThink(int msec)`, `Touch(BaseEntity<em>)`, `Use(BaseEntity</em>)`, `TakeDamage(const DamageInfo&amp;)`, `OnPain(const DamageInfo&amp;)`, `OnDeath(const DamageInfo&amp;)`, `Save(SaveWriter&amp;)`, `Load(SaveReader&amp;)`.</li>
<li>`struct EntityClass` descriptor: `const char* classname`, factory func, optional flags/caps, pointer to a field table for net/save (offset, type, version, default).</li>
<li>`struct DamageInfo`, `struct EventContext` as small PODs usable from C.</li></ul></p><p><h2>Factory/Registry</h2>
<ul><li>A global registry mapping classname → `EntityClass`.</li>
<li>Fallback path calls legacy C spawn funcs when no registered class exists.</li>
<li>Registration via a small macro/helper to avoid static-init order hazards (explicit `RegisterEntities()` call).</li></ul></p><p><h2>Mixins/Reuse</h2>
<ul><li>Prefer mixins/components for common behaviors (movement modes, doors/triggers, health/damage handling, render binding) instead of deep inheritance.</li>
<li>Keep base class small; store class-local state via composition inside each derived type.</li></ul></p><p><h2>Messaging/Event Bus</h2>
<ul><li>Lightweight `FireOutput(name, payload)` and `OnInput(name, payload)` with optional filters.</li>
<li>Simple event bus to decouple entities (publish/subscribe within the level).</li></ul></p><p><h2>Net/Save Descriptors</h2>
<ul><li>Per-class field table reused for both snapshot encode/decode and save/load.</li>
<li>Include versioning/defaulting to allow schema evolution.</li></ul></p><p><h2>Rollout Plan</h2>
1) Add C ABI shim headers (`extern &quot;C&quot;`) that expose spawn/think hooks calling into C++.
2) Implement registry + `BaseEntity` skeleton in C++.
3) Bridge legacy entities: start with `func_door`, `trigger_multiple`, one NPC; keep a cvar to toggle legacy vs new path.
4) Verify snapshot/save compatibility; add regression tests for serialization.
5) Gradually move shared behaviors into mixins; keep legacy path intact until confidence is high.</p><p><h2>Backward Compatibility</h2>
<ul><li>Default behavior stays on the legacy C/QVM path; new C++ entities only engage when explicitly enabled (cvar or build flag).</li>
<li>Fallback: if a classname is unregistered in the C++ registry, spawn falls back to the legacy C spawn function.</li>
<li>Snapshot/save format remains unchanged; new per-class field tables must map onto existing serialized fields or supply defaults when absent.</li>
<li>Keep QVM builds untouched: C ABI shims are headers-only for QVM; C++ code is only built for native gamecode targets.</li>
<li>Provide a kill-switch cvar (e.g., `g_oopEntities 0/1`) to toggle C++ entities at runtime for A/B validation.</li></ul></p><p><h2>Build Notes</h2>
<ul><li>Build new gamecode objects as C++; keep engine-side build unchanged.</li>
<li>Ensure headers included from C code are guarded for C++ (`extern &quot;C&quot;` on APIs, C-compatible PODs only).</li>
<li>Consider `-fno-exceptions -fno-rtti` for gamecode to keep binaries small and boundary-safe.</li></ul></p><p></p>
</div>