<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Complete Font Setup Guide for mymod</h1></p><p><h2>Quick Start (5 Minutes)</h2></p><p><h3>Step 1: Download Fonts</h3>
1. Go to <a href="https://fonts.google.com/">Google Fonts</a>
2. Download <strong>Roboto</strong> (Regular + Bold) or <strong>Noto Sans</strong> (Regular + Bold)
3. Extract `.ttf` files</p><p><h3>Step 2: Place Fonts</h3>
```
mymod/
└── fonts/
    ├── roboto-regular.ttf
    ├── roboto-bold.ttf
    └── fonts.cfg
```</p><p><h3>Step 3: Configure</h3>
Edit `mymod/fonts/fonts.cfg`:
```
font &quot;fonts/roboto-regular.ttf&quot; 18
smallFont &quot;fonts/roboto-regular.ttf&quot; 14
bigFont &quot;fonts/roboto-bold.ttf&quot; 24
```</p><p><h3>Step 4: Set Quality</h3>
Add to `mymod.cfg` or `autoexec.cfg`:
```
set r_fontDPI 120
set r_fontKerning 1
set r_fontAntialiasing 1
set r_fontAtlasSize 512
```</p><p><h3>Step 5: Test</h3>
Launch: `./quake3e +set fs_game mymod`
Check console for &quot;Loaded font&quot; messages.</p><p><h2>Detailed Configuration</h2></p><p><h3>Font Sizes Guide</h3></p><p>| Use Case | Recommended Size | Example |
|----------|------------------|---------|
| Menu titles | 24-32pt | Big, bold headers |
| Menu items | 16-20pt | Navigation, buttons |
| HUD text | 14-18pt | Health, ammo, scores |
| Small text | 12-14pt | Lists, tooltips |
| Console | 12-14pt | Debug output |</p><p><h3>Font Quality Settings</h3></p><p><h4>DPI (r_fontDPI)</h4>
<ul><li><strong>72</strong> - Standard (default)</li>
<li><strong>96</strong> - Windows standard</li>
<li><strong>120</strong> - High DPI displays (recommended)</li>
<li><strong>144</strong> - Very high DPI (may use more memory)</li></ul></p><p><h4>Atlas Size (r_fontAtlasSize)</h4>
<ul><li><strong>256</strong> - Low memory, good for small fonts</li>
<li><strong>512</strong> - Balanced (recommended)</li>
<li><strong>1024</strong> - High quality, more memory</li></ul></p><p><h4>Hinting (r_fontHinting)</h4>
<ul><li><strong>0</strong> - None (smooth but blurry at small sizes)</li>
<li><strong>1</strong> - Light (subtle optimization)</li>
<li><strong>2</strong> - Normal (recommended)</li>
<li><strong>3</strong> - Strong (sharp but may look distorted)</li></ul></p><p><h4>Antialiasing (r_fontAntialiasing)</h4>
<ul><li><strong>0</strong> - Disabled (pixelated)</li>
<li><strong>1</strong> - Enabled (recommended, smooth)</li></ul></p><p><h4>Kerning (r_fontKerning)</h4>
<ul><li><strong>0</strong> - Disabled (uniform spacing)</li>
<li><strong>1</strong> - Enabled (recommended, better readability)</li></ul></p><p><h2>Font Recommendations</h2></p><p><h3>For Modern Look</h3>
<ul><li><strong>Roboto</strong> - Clean, modern, excellent readability</li>
<li><strong>Open Sans</strong> - Professional, versatile</li>
<li><strong>Lato</strong> - Friendly, approachable</li></ul></p><p><h3>For International Support</h3>
<ul><li><strong>Noto Sans</strong> - Best Unicode coverage (CJK, Arabic, etc.)</li>
<li><strong>Noto Emoji</strong> - For emoji support</li>
<li><strong>DejaVu Sans</strong> - Good fallback option</li></ul></p><p><h3>For Retro/Classic Look</h3>
<ul><li><strong>DejaVu Sans</strong> - Classic terminal feel</li>
<li><strong>Liberation Sans</strong> - Windows-like</li>
<li><strong>Ubuntu</strong> - Linux-style</li></ul></p><p><h2>Advanced: Font Fallback Chains</h2></p><p>When full fallback support is implemented, you can use:</p><p>```
fontFallback &quot;fonts/roboto-regular.ttf&quot; 18 &quot;fonts/noto-sans.ttf&quot; &quot;fonts/noto-emoji.ttf&quot;
```</p><p>This ensures:
1. Try Roboto first
2. If character missing, try Noto Sans
3. If still missing, try Noto Emoji
4. Finally fall back to bitmap fonts</p><p><h2>Troubleshooting</h2></p><p><h3>Fonts Not Loading</h3>
<strong>Symptoms:</strong> Console shows &quot;Fonts config not found&quot; or no font messages</p><p><strong>Solutions:</strong>
1. Check `fonts/fonts.cfg` exists
2. Verify file paths are correct (relative to mod root)
3. Check font files exist in `fonts/` directory
4. Ensure FreeType is enabled in engine build</p><p><h3>Poor Font Quality</h3>
<strong>Symptoms:</strong> Text looks blurry or pixelated</p><p><strong>Solutions:</strong>
1. Increase `r_fontDPI` to 120-144
2. Enable `r_fontAntialiasing`
3. Increase `r_fontAtlasSize` to 512 or 1024
4. Try different hinting modes (0-3)</p><p><h3>Missing Characters</h3>
<strong>Symptoms:</strong> Some characters show as boxes or missing</p><p><strong>Solutions:</strong>
1. Use fonts with better Unicode coverage (Noto Sans)
2. Configure fallback chains (when implemented)
3. Check font file supports required character sets
4. Verify font file isn&#039;t corrupted</p><p><h3>Performance Issues</h3>
<strong>Symptoms:</strong> Slow menu loading or frame drops</p><p><strong>Solutions:</strong>
1. Reduce `r_fontAtlasSize` to 256
2. Lower `r_fontDPI` to 96
3. Disable `r_fontAntialiasing` (if needed)
4. Don&#039;t load too many fonts</p><p><h2>Best Practices</h2></p><p>1. <strong>Use appropriate font sizes</strong> - Don&#039;t go too large (wastes memory)
2. <strong>Test on target resolution</strong> - Fonts look different at different sizes
3. <strong>Keep font count low</strong> - Each font uses memory
4. <strong>Use system fonts when possible</strong> - Better compatibility
5. <strong>Include font licenses</strong> - Required for distribution
6. <strong>Test fallback behavior</strong> - Ensure bitmap fonts work as backup</p><p><h2>Performance Tips</h2>
<ul><li><strong>Atlas size 512</strong> is usually best balance</li>
<li><strong>DPI 120</strong> works well for most displays</li>
<li><strong>Kerning</strong> has minimal performance impact</li>
<li><strong>Antialiasing</strong> slightly impacts performance but worth it</li>
<li><strong>Multiple fonts</strong> each use memory - keep count reasonable</li></ul></p><p><h2>Font Licensing</h2></p><p><strong>Always check licenses before distributing:</strong>
<ul><li><strong>Roboto</strong> - Apache 2.0 ✅ Free to use</li>
<li><strong>Noto Sans</strong> - SIL OFL ✅ Free to use  </li>
<li><strong>Open Sans</strong> - Apache 2.0 ✅ Free to use</li>
<li><strong>DejaVu Sans</strong> - Public Domain ✅ Free to use</li></ul></p><p><strong>Include license files</strong> when distributing your mod!</p><p><h2>Example Configurations</h2></p><p><h3>Minimal Setup</h3>
```
font &quot;fonts/roboto-regular.ttf&quot; 16
smallFont &quot;fonts/roboto-regular.ttf&quot; 12
bigFont &quot;fonts/roboto-bold.ttf&quot; 20
```</p><p><h3>High Quality Setup</h3>
```
font &quot;fonts/noto-sans-regular.ttf&quot; 18
smallFont &quot;fonts/noto-sans-regular.ttf&quot; 14
bigFont &quot;fonts/noto-sans-bold.ttf&quot; 24</p><p>fontFallback &quot;fonts/noto-sans-regular.ttf&quot; 18 &quot;fonts/noto-emoji.ttf&quot;
```</p><p><h3>Performance-Optimized Setup</h3>
```
font &quot;fonts/roboto-regular.ttf&quot; 16
smallFont &quot;fonts/roboto-regular.ttf&quot; 12
bigFont &quot;fonts/roboto-bold.ttf&quot; 20</p><p>// In config:
set r_fontDPI 96
set r_fontAtlasSize 256
set r_fontAntialiasing 1
```</p><p><h2>Next Steps</h2></p><p>1. ✅ Download fonts
2. ✅ Configure `fonts.cfg`
3. ✅ Set quality CVars
4. ✅ Test in game
5. ✅ Adjust sizes as needed
6. ✅ Document your font choices</p><p><h2>Support</h2></p><p>If you encounter issues:
1. Check console for error messages
2. Verify font files aren&#039;t corrupted
3. Test with default fonts first
4. Check engine FreeType support
5. Review this guide for common issues</p><p></p>
</div>