<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Engine Improvements Implementation Plan</h1></p><p>This document tracks the systematic implementation of improvements identified in the architecture analysis.</p><p><h2>Phase 1: Critical Fixes (Week 1-2)</h2></p><p><h3>1.1 Fix Dynamic Renderer Loading ✓ IN PROGRESS</h3>
<strong>Problem:</strong> SDL backend Vulkan functions not properly exported to dynamically loaded renderers</p><p><strong>Root Cause:</strong>
<ul><li>Functions defined in `sdl_glimp.c`, compiled into `q3ui` OBJECT library</li>
<li>Main executable needs `-rdynamic` (present) BUT functions must be actually linked into executable</li>
<li>Current: q3ui is OBJECT library, its objects linked into executable</li>
<li>Issue: Conditional compilation means functions may not exist at all</li></ul></p><p><strong>Solution:</strong>
1. Ensure `USE_VULKAN` and `USE_SDL` are both defined for client target ✓ (already done)
2. Verify q3ui objects are properly linked into main executable
3. Add explicit symbol export macros for Vulkan functions
4. Add runtime validation that pointers are set correctly</p><p><strong>Files to Modify:</strong>
<ul><li>`src/sdl/sdl_glw.h` - Add export macros</li>
<li>`src/sdl/sdl_glimp.c` - Mark functions for export</li>
<li>`src/client/cl_main.c` - Add validation</li>
<li>`CMakeLists.txt` - Verify linking</li></ul></p><p><h3>1.2 Standardize Feature Flags</h3>
<strong>Problem:</strong> USE_VULKAN vs USE_VULKAN_API confusion</p><p><strong>Solution:</strong>
1. Audit all uses of both flags
2. Choose ONE canonical flag (recommend: `USE_VULKAN`)
3. Replace all instances consistently
4. Update CMake to only set one flag</p><p><strong>Impact:</strong> ~50 files to update</p><p><h3>1.3 Add Critical Validation</h3>
<strong>Problem:</strong> NULL function pointers cause crashes</p><p><strong>Solution:</strong>
1. Add validation macro for refimport_t assignment
2. Check all function pointers before GetRefAPI call
3. Provide clear error messages</p><p><h2>Phase 2: Build System Modernization (Week 3-4)</h2></p><p><h3>2.1 Split CMakeLists.txt</h3>
<strong>Current:</strong> 2,707 lines in one file
<strong>Target:</strong> Modular structure</p><p><strong>New Structure:</strong>
```
cmake/
  ├── PlatformDetection.cmake
  ├── CompilerFlags.cmake
  ├── Dependencies.cmake
  ├── Renderers.cmake
  ├── Server.cmake
  ├── Client.cmake
  └── Tests.cmake
```</p><p><h3>2.2 Simplify Feature Flags</h3>
<strong>Actions:</strong>
<ul><li>Document each flag purpose</li>
<li>Remove redundant flags</li>
<li>Create flag dependency graph</li></ul></p><p><h2>Phase 3: Memory Safety (Week 5-6)</h2></p><p><h3>3.1 String Operation Audit</h3>
<strong>Scope:</strong> 1,540 instances</p><p><strong>Priority Files:</strong>
1. Network code (msg.c, net_chan.c)
2. File parsing (files.c, unzip.c)
3. Command handling (cmd.c, cvar.c)</p><p><strong>Actions:</strong>
<ul><li>Add Q_strncpyz_s with validation</li>
<li>Replace unsafe operations</li>
<li>Add compile-time size checks</li></ul></p><p><h3>3.2 Network Buffer Validation</h3>
<strong>Scope:</strong> 556 MSG_* calls</p><p><strong>Actions:</strong>
<ul><li>Add bounds checking macros</li>
<li>Implement overflow detection</li>
<li>Add fuzzing tests</li></ul></p><p><h2>Phase 4: Code Organization (Week 7-10)</h2></p><p><h3>4.1 Refactor files.c</h3>
<strong>Current:</strong> 6,851 lines
<strong>Target:</strong> 4-5 modules ~1,500 lines each</p><p><strong>Modules:</strong>
<ul><li>`vfs_core.c` - Core VFS API</li>
<li>`vfs_pak.c` - PK3/PAK loading</li>
<li>`vfs_mount.c` - Mount table management</li>
<li>`vfs_cache.c` - Path/existence caching</li>
<li>`vfs_search.c` - File search operations</li></ul></p><p><h3>4.2 Standardize Error Handling</h3>
<strong>Current:</strong> 4 different error patterns
<strong>Target:</strong> Unified error handling</p><p><strong>New Pattern:</strong>
```c
typedef enum {
    ERR_LEVEL_INFO,
    ERR_LEVEL_WARNING,
    ERR_LEVEL_RECOVERABLE,
    ERR_LEVEL_FATAL
} errorLevel_t;</p><p>qboolean Err_Handle(errorLevel_t level, const char *fmt, ...);
```</p><p><h2>Phase 5: Platform Abstraction (Week 11-12)</h2></p><p><h3>5.1 Create Platform Abstraction Layer</h3>
<strong>Target:</strong> Reduce 95 #ifdef blocks to ~20</p><p><strong>Structure:</strong>
```
src/platform/
  ├── platform.h          - Common interface
  ├── platform_linux.c
  ├── platform_windows.c
  ├── platform_macos.c
  └── platform_ios.c
```</p><p><strong>Abstracted Functions:</strong>
<ul><li>Window management</li>
<li>Input handling  </li>
<li>File system ops</li>
<li>Threading primitives</li></ul></p><p><h2>Phase 6: Testing Infrastructure (Week 13-14)</h2></p><p><h3>6.1 Increase Test Coverage</h3>
<strong>Current:</strong> &lt;5% (7 test files)
<strong>Target:</strong> 20%+ critical path coverage</p><p><strong>New Tests:</strong>
<ul><li>`test_msg_parsing.c` - Network protocol</li>
<li>`test_renderer_init.c` - Renderer loading</li>
<li>`test_vfs.c` - File system operations</li>
<li>`test_string_safety.c` - String operations</li>
<li>`test_allocators.c` - Memory management</li></ul></p><p><h3>6.2 Add Integration Tests</h3>
<ul><li>Renderer initialization sequence</li>
<li>Network packet handling</li>
<li>File loading workflows</li></ul></p><p><h3>6.3 Add Fuzzing</h3>
<ul><li>Network packet fuzzer</li>
<li>PK3 file fuzzer</li>
<li>Console command fuzzer</li></ul></p><p><h2>Success Metrics</h2></p><p><h3>Critical (Must Have)</h3>
<ul><li>[ ] Zero NULL function pointer crashes</li>
<li>[ ] All network inputs bounds-checked</li>
<li>[ ] CMake builds complete under 5 minutes</li></ul></p><p><h3>High Priority (Should Have)</h3>
<ul><li>[ ] Test coverage &gt;20%</li>
<li>[ ] files.c split into modules</li>
<li>[ ] Platform #ifdefs reduced by 50%</li></ul></p><p><h3>Medium Priority (Nice to Have)</h3>
<ul><li>[ ] All files &lt;2000 lines</li>
<li>[ ] Unified error handling</li>
<li>[ ] Documentation updated</li></ul></p><p><h2>Timeline Summary</h2></p><p>| Phase | Duration | Priority | Status |
|-------|----------|----------|--------|
| 1. Critical Fixes | 2 weeks | P0 | IN PROGRESS |
| 2. Build System | 2 weeks | P1 | PLANNED |
| 3. Memory Safety | 2 weeks | P0 | PLANNED |
| 4. Code Organization | 4 weeks | P1 | PLANNED |
| 5. Platform Abstraction | 2 weeks | P2 | PLANNED |
| 6. Testing | 2 weeks | P1 | PLANNED |</p><p><strong>Total Estimated Duration:</strong> 14 weeks (3.5 months)</p><p><h2>Next Actions</h2></p><p>1. Complete renderer loading fix
2. Validate with test compilation
3. Move to feature flag standardization
4. Begin CMake refactoring</p><p>---</p><p><em>Updated: 2024</em></p><p></p>
</div>