<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>iOS and macOS Platform Support</h1></p><p><h2>Overview</h2></p><p>This document describes the platform-specific support for iOS and macOS in the id Tech 3 engine, including window management, app lifecycle, and platform integration.</p><p><h2>Architecture</h2></p><p><h3>Platform Abstraction Layer</h3></p><p>The platform abstraction layer (`macos_platform.h` / `macos_platform.mm`) provides a unified interface for both iOS and macOS platforms:
<ul><li><strong>Window/View Management</strong>: Create and manage windows (macOS) or views (iOS)</li>
<li><strong>File System</strong>: Access to base path, user path, and resource path</li>
<li><strong>System Information</strong>: CPU count, system info, Retina display detection</li>
<li><strong>Platform Capabilities</strong>: Metal feature detection and support</li></ul></p><p><h3>iOS Support</h3></p><p><h4>App Lifecycle</h4></p><p>iOS applications use `UIApplicationDelegate` to handle app lifecycle events:
<ul><li><strong>didFinishLaunchingWithOptions</strong>: Initialize engine and create main view</li>
<li><strong>applicationWillResignActive</strong>: Pause game when app goes to background</li>
<li><strong>applicationDidEnterBackground</strong>: Save state when app enters background</li>
<li><strong>applicationWillEnterForeground</strong>: Resume game when app comes to foreground</li>
<li><strong>applicationDidBecomeActive</strong>: Resume game when app becomes active</li>
<li><strong>applicationWillTerminate</strong>: Cleanup when app terminates</li>
<li><strong>applicationDidReceiveMemoryWarning</strong>: Handle memory warnings</li></ul></p><p><h4>View Management</h4></p><p>iOS uses `UIView` for rendering:</p><p>```objective-c
// Create view
void* view = Platform_CreateView(width, height);</p><p>// Set view size
Platform_SetViewSize(view, width, height);</p><p>// Get view size
int width, height;
Platform_GetViewSize(view, &amp;width, &amp;height);
```</p><p><h3>macOS Support</h3></p><p><h4>Window Management</h4></p><p>macOS uses `NSWindow` for window management:</p><p>```objective-c
// Create window
void* window = Platform_CreateWindow(&quot;Game Title&quot;, width, height, fullscreen);</p><p>// Set window size
Platform_SetWindowSize(window, width, height);</p><p>// Get window size
int width, height;
Platform_GetWindowSize(window, &amp;width, &amp;height);</p><p>// Set window title
Platform_SetWindowTitle(window, &quot;New Title&quot;);</p><p>// Toggle fullscreen
Platform_SetWindowFullscreen(window, qtrue);
```</p><p><h4>Main Loop</h4></p><p>macOS uses `NSApplication` main loop:</p><p>```objective-c
NSApplication* app = [NSApplication sharedApplication];
[app run];
```</p><p><h2>Building</h2></p><p><h3>iOS Build</h3></p><p>For iOS builds, use CMake with iOS toolchain:</p><p>```bash
cmake .. \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_SYSROOT=iphoneos \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DUSE_METAL=ON
```</p><p>Or use Xcode project generation:</p><p>```bash
cmake .. -G Xcode -DUSE_METAL=ON
```</p><p><h3>macOS Build</h3></p><p>Standard macOS build:</p><p>```bash
cmake .. -DUSE_METAL=ON
make
```</p><p><h2>Platform Detection</h2></p><p>The platform abstraction layer automatically detects:
<ul><li><strong>iOS vs macOS</strong>: Uses `TARGET_OS_IPHONE` preprocessor define</li>
<li><strong>Metal Support</strong>: Checks for Metal device availability</li>
<li><strong>Metal 2.0+ Features</strong>: Argument buffers, indirect command buffers</li>
<li><strong>Metal 3.0+ Features</strong>: Ray tracing support</li>
<li><strong>Retina Display</strong>: Detects high-DPI displays</li>
<li><strong>Variable Refresh Rate</strong>: ProMotion support (iOS 15+, macOS 12+)</li></ul></p><p><h2>File System Paths</h2></p><p><h3>Base Path</h3></p><p>Returns the application bundle path:
<ul><li><strong>iOS</strong>: `/path/to/App.app`</li>
<li><strong>macOS</strong>: `/path/to/App.app/Contents/MacOS`</li></ul></p><p><h3>User Path</h3></p><p>Returns the user application support directory:
<ul><li><strong>iOS</strong>: `~/Library/Application Support/AppName`</li>
<li><strong>macOS</strong>: `~/Library/Application Support/AppName`</li></ul></p><p><h3>Resource Path</h3></p><p>Returns the application resource directory:
<ul><li><strong>iOS</strong>: `/path/to/App.app/`</li>
<li><strong>macOS</strong>: `/path/to/App.app/Contents/Resources`</li></ul></p><p><h2>Integration with Metal Renderer</h2></p><p>The platform abstraction layer integrates seamlessly with the Metal renderer:</p><p>1. <strong>Window/View Creation</strong>: Platform creates window/view, Metal renderer attaches CAMetalLayer
2. <strong>Size Management</strong>: Platform handles window/view resizing, Metal renderer updates swap chain
3. <strong>Event Processing</strong>: Platform processes system events, engine handles game events</p><p><h2>Example Usage</h2></p><p><h3>iOS</h3></p><p>```objective-c
// In AppDelegate
<ul><li>(BOOL)application:(UIApplication *)application </li>
    </ul>didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    // Create main view
    void* view = Platform_CreateView(1024, 768);
    
    // Initialize engine
    Com_Init(argc, argv);
    
    // Initialize Metal renderer with view
    Metal_InitWindow(view);
    
    return YES;
}
```</p><p><h3>macOS</h3></p><p>```objective-c
int main(int argc, char *argv[]) {
    // Initialize platform
    Platform_Init();
    
    // Create window
    void* window = Platform_CreateWindow(&quot;id Tech 3&quot;, 1024, 768, qfalse);
    
    // Initialize engine
    Com_Init(argc, argv);
    
    // Initialize Metal renderer with window
    Metal_InitWindow(window);
    
    // Run main loop
    [NSApp run];
    
    return 0;
}
```</p><p><h2>Troubleshooting</h2></p><p><h3>iOS Build Issues</h3>
<ul><li><strong>Missing UIKit</strong>: Ensure iOS SDK is properly configured</li>
<li><strong>App Delegate Not Found</strong>: Check that `ios_appdelegate.mm` is included in build</li>
<li><strong>Metal Not Available</strong>: Verify device supports Metal (iPhone 5s or later)</li></ul></p><p><h3>macOS Build Issues</h3>
<ul><li><strong>Missing AppKit</strong>: Ensure macOS SDK is properly configured</li>
<li><strong>Window Not Showing</strong>: Check that `[window makeKeyAndOrderFront:nil]` is called</li>
<li><strong>Metal Not Available</strong>: Verify Mac supports Metal (2012 or later)</li></ul></p><p><h2>See Also</h2>
<ul><li><a href="metal-support.md">Metal Renderer Support</a></li>
<li><a href="BUILD.md">Build Instructions</a></li></ul></p><p></p>
</div>