<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Material System Capacity Limits</h1></p><p><h2>Overview</h2></p><p>The Vulkan renderer includes a runtime material parameter system that allows dynamic modification of material properties (wetness, damage, magic effects, etc.). This system has a fixed capacity that determines how many unique materials can be active simultaneously.</p><p><h2>Current Configuration</h2>
<ul><li><strong>Capacity</strong>: 2048 materials</li>
<li><strong>Memory per material</strong>: 168 bytes (CPU + GPU)</li>
<li><strong>Total memory usage</strong>: 336KB CPU + 336KB GPU</li></ul></p><p><h2>Capacity Constraints</h2></p><p><h3>1. MAX_DRAWIMAGES Limit (2048)</h3></p><p>The material system capacity is tied to `MAX_DRAWIMAGES`, which limits the total number of textures/images the renderer can handle.</p><p><strong>Files to modify for increase:</strong>
<ul><li>`src/renderer/tr_local.h`</li>
<li>`src/renderervk/tr_local.h`</li></ul></p><p><strong>Impact of increasing:</strong>
<ul><li>Scales Vulkan descriptor pool allocation automatically</li>
<li>Linear memory scaling: `new_memory = old_memory × (new_capacity ÷ 2048)`</li>
<li>May require testing on lower-end hardware</li></ul></p><p><h3>2. Vulkan Storage Buffer Limits</h3></p><p>The material parameters are stored in a GPU storage buffer.</p><p><strong>Hardware-specific limits:</strong>
<ul><li>`maxStorageBufferRange`: Typically 128MB - 2GB</li>
<li>Current usage (344KB) is well within all hardware limits</li></ul></p><p><strong>Theoretical maximum capacity:</strong>
<ul><li>128MB limit: ~786,432 materials</li>
<li>2GB limit: ~12.5 million materials</li>
<li>Practical limit lower due to descriptor constraints</li></ul></p><p><h3>3. Descriptor Pool Limits</h3></p><p>The Vulkan descriptor pool allocates descriptors based on `MAX_DRAWIMAGES`:
<ul><li>Combined image samplers: `MAX_DRAWIMAGES + overhead`</li>
<li>Storage buffers: 1 (material parameter buffer)</li>
<li>Pool scales automatically with `MAX_DRAWIMAGES`</li></ul></p><p><h3>4. Memory Constraints</h3>
<ul><li><strong>CPU memory</strong>: Zone-allocated material parameter storage</li>
<li><strong>GPU memory</strong>: Storage buffer for shader access</li>
<li><strong>No additional per-material GPU resources</strong></li></ul></p><p><h2>Increasing Capacity</h2></p><p><h3>Step-by-Step Process</h3></p><p>1. <strong>Update MAX_DRAWIMAGES</strong> in both header files:
   ```c
   #define MAX_DRAWIMAGES 4096  // or desired value
   ```</p><p>2. <strong>Rebuild engine</strong> - descriptor pools scale automatically</p><p>3. <strong>Test on target hardware</strong> for:
<ul><li>Storage buffer size limits</li>
<li>Descriptor pool availability</li>
<li>Memory pressure</li></ul></p><p><h3>Memory Scaling Calculator</h3></p><p>For new capacity `N`:
<ul><li>CPU memory: `336KB × (N ÷ 2048)`</li>
<li>GPU memory: `336KB × (N ÷ 2048)`</li>
<li>Descriptor overhead: Scales with `MAX_DRAWIMAGES`</li></ul></p><p><h3>Recommended Capacities</h3>
<ul><li><strong>2048</strong> (current): Sufficient for most games</li>
<li><strong>4096</strong>: Good for large open-world games with many material variants</li>
<li><strong>8192</strong>: High-end applications with extensive material variation</li>
<li><strong>16384+</strong>: Specialized applications (may hit hardware limits)</li></ul></p><p><h2>Hardware Compatibility</h2></p><p><h3>Minimum Requirements</h3>
<ul><li>Vulkan 1.1+ capable GPU</li>
<li>Storage buffer support (ubiquitous on modern hardware)</li></ul></p><p><h3>Memory Requirements</h3>
<ul><li>Additional ~688KB per 2048 materials</li>
<li>Linear scaling with capacity</li></ul></p><p><h3>Performance Impact</h3>
<ul><li>Minimal CPU overhead (zone allocation only during init)</li>
<li>GPU overhead: One storage buffer bind per frame</li>
<li>Shader access: Fast constant-time lookups</li></ul></p><p><h2>Troubleshooting</h2></p><p><h3>Descriptor Pool Exhaustion</h3>
If you hit descriptor limits, reduce `MAX_DRAWIMAGES` or optimize descriptor usage.</p><p><h3>Storage Buffer Limits</h3>
If initialization fails on specific hardware, the storage buffer may exceed `maxStorageBufferRange`. Reduce capacity or implement fallback.</p><p><h3>Memory Pressure</h3>
Monitor total GPU memory usage. Material system uses minimal memory compared to textures/geometry.</p><p><h2>Future Considerations</h2></p><p>The material system could be extended with:
<ul><li>Dynamic capacity growth (reallocation)</li>
<li>Compressed parameter storage</li>
<li>Material streaming/paging</li>
<li>CPU-side caching to reduce GPU buffer size</li></ul></p>
</div>