<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Metal Renderer Support</h1></p><p><h2>Overview</h2></p><p>The id Tech 3 engine provides integration with Apple&#039;s Metal graphics API, enabling native rendering on both macOS and iOS. This renderer delivers a modern GPU-accelerated experience for Apple hardware, with a unified codebase across desktop and mobile.</p><p>---</p><p><h2>Implementation Progress</h2></p><p><h3>Features &amp; Status</h3></p><p>| Feature                         | Status   |
|----------------------------------|----------|
| Metal device/context creation    | ✅       |
| Swap chain (CAMetalLayer)        | ✅       |
| Render pipeline setup            | ✅       |
| Command buffer management        | ✅       |
| Triple buffering                 | ✅       |
| Metal shader compilation         | ✅       |
| UI/2D render path &amp; shaders      | ✅       |
| 2D projection matrix             | ✅       |
| Resource management (basic)      | ✅       |
| State tracking (color, depth)    | ✅       |
| Vertex buffer pooling            | 🚧       |
| Texture management/loading       | 🚧       |
| Shader system integration        | 🚧       |
| Model/world rendering            | ⏳       |
| Ray tracing (Metal 3.0)          | ⏳       |</p><p><strong>Recent improvements:</strong>
<ul><li>UI render pipeline state (`uiPipelineState`)</li>
<li>Dynamic orthographic projection for 2D rendering</li>
<li>Separate depth-stencil state for 2D/UI</li>
<li>Enhanced UI shaders (attribute layout, color modulation)</li>
<li>State tracking (color, projection, buffer clearing)</li>
<li>Drawable management (`currentDrawable`) and improved frame presentation</li></ul></p><p><strong>Current development focus:</strong>
<ul><li>Vertex buffer management for 2D/3D pipelines</li>
<li>Texture support (format conversion, image loading, binding)</li>
<li>Shader system connection/integration</li>
<li>Support for structured draw calls &amp; simple models</li>
<li>Extended resource tracking</li></ul></p><p><strong>Future/Planned:</strong>
<ul><li>Full mesh and model rendering</li>
<li>BSP/world rendering pipeline</li>
<li>Lighting, post-processing, and advanced effects</li>
<li>Metal 3 ray tracing and acceleration structures</li></ul></p><p>---</p><p><h2>Requirements</h2></p><p><h3>macOS</h3>
<ul><li>macOS 10.13 (High Sierra) or later (11.0 recommended)</li>
<li>Xcode 9.0+ with Metal tools</li>
<li>Metal-compatible Mac GPU</li></ul></p><p><h3>iOS</h3>
<ul><li>iOS 11.0 or later (13.0+ recommended)</li>
<li>Xcode 9.0+ (with iOS SDK)</li>
<li>Metal-compatible iPhone/iPad</li></ul></p><p>---</p><p><h2>Building</h2></p><p><h3>CMake (macOS and iOS)</h3></p><p>To enable Metal support:</p><p>```bash
cmake .. -DUSE_METAL=ON
make
```</p><p>For iOS:</p><p>```bash
cmake .. \
  -DCMAKE_SYSTEM_NAME=iOS \
  -DCMAKE_OSX_SYSROOT=iphoneos \
  -DCMAKE_OSX_ARCHITECTURES=arm64 \
  -DUSE_METAL=ON
```</p><p>Or generate Xcode project:</p><p>```bash
cmake .. -G Xcode -DUSE_METAL=ON
```</p><p>Build options:
<ul><li>`USE_METAL`: Enable/disable Metal renderer (default ON for Apple platforms)</li>
<li>`USE_RENDERER_DLOPEN`: Build renderer as a dynamic library</li></ul></p><p>---</p><p><h2>Usage</h2>
<ul><li>To use Metal at runtime:</li>
  </ul>```
  /r_renderer metal
  ```
<ul><li>Or set as default in configuration:</li>
  </ul>```
  set r_renderer metal
  ```</p><p>Main CVar:  
<ul><li>`r_renderer`: {opengl, vulkan, d3d12, metal}</li></ul></p><p>---</p><p><h2>Architecture</h2></p><p>    src/renderermetal/
    ├── metal.h          # Metal context structure &amp; API
    ├── metal.mm         # Objective-C++ Metal implementation
    ├── tr_local.h       # Renderer internal definitions
    ├── tr_common.h      # Renderer common/shared data
    ├── tr_init.c        # Renderer initialization
    ├── tr_main.c        # Public renderer interface
    └── shaders/
        ├── default.metal   # Main 3D shaders
        └── ui.metal        # 2D/UI shaders</p><p>Key components:
<ul><li><strong>Metal context:</strong> device, command queue, CAMetalLayer, pipeline state, depth-stencil state</li>
<li><strong>Renderer entry points:</strong> initialization, frame, shutdown; model/shader/texture registration</li>
<li><strong>Shader system:</strong> Metal shaders compiled to `.metallib` at build time</li></ul></p><p>---</p><p><h2>Platform-Specific Notes</h2></p><p><strong>macOS:</strong>
<ul><li>Uses `NSWindow` and AppKit for windowing</li>
<li>Metal layer attached to window content view</li></ul></p><p><strong>iOS:</strong>
<ul><li>Uses `UIView` and UIKit</li>
<li>Metal layer as sublayer</li>
<li>Supports app lifecycle and device rotation</li></ul></p><p>---</p><p><h2>Troubleshooting</h2></p><p><strong>Shader compile errors:</strong>
<ul><li>Ensure Xcode CLI and `xcrun metal` are available</li>
<li>Check shader files in `src/renderermetal/shaders/`</li></ul></p><p><strong>Renderer startup errors:</strong>
<ul><li>Metal-capable hardware required</li>
<li>Correct OS/iOS version needed</li></ul></p><p><strong>Build problems:</strong>
<ul><li>Confirm Xcode, SDKs, and CMake setup</li></ul></p><p>---</p><p><h2>Related Documentation</h2>
<ul><li><a href="BUILD.md">Build Instructions</a></li>
<li><a href="directx12-support.md">DirectX 12 Support</a></li>
<li><a href="https://developer.apple.com/metal/">Metal Programming Guide (Apple)</a></li></ul></p><p>---</p><p></p>
</div>