<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Modern C/C++ Features Adoption</h1></p><p>This document outlines the adoption of modern C/C++ language features in the id Tech 3 codebase, improving code quality, safety, and maintainability.</p><p><h2>Adopted Features</h2></p><p><h3>C23 Features</h3></p><p><h4>1. `nullptr` instead of `NULL`</h4>
<ul><li><strong>Files Modified</strong>: `src/common/common.c`</li>
<li><strong>Rationale</strong>: `nullptr` provides better type safety than `NULL`</li>
<li><strong>Compatibility</strong>: C23 supports `nullptr` natively</li>
<li><strong>Examples</strong>:</li>
  </ul>```c
  // Before
  rd_buffer = NULL;
  return NULL;</p><p>  // After
  rd_buffer = nullptr;
  return nullptr;
  ```</p><p><h4>2. Designated Initializers</h4>
<ul><li><strong>Files Modified</strong>: `src/common/vm.c`</li>
<li><strong>Rationale</strong>: Designated initializers improve code readability and maintainability</li>
<li><strong>Examples</strong>:</li>
  </ul>```c
  // Before
  { 4, -8, 2, JUMP }, // eq</p><p>  // After
  { .size = 4, .stack = -8, .nargs = 2, .flags = JUMP }, // eq
  ```</p><p><h4>3. Static Assertions</h4>
<ul><li><strong>Files Modified</strong>: `src/common/q_shared.h`, `src/common/qcommon.h`</li>
<li><strong>Rationale</strong>: Compile-time verification of critical assumptions</li>
<li><strong>Examples</strong>:</li>
  </ul>```c
  // Structure size verification
  static_assert(sizeof(vec3_t) == 12, &quot;vec3_t must be 12 bytes for network compatibility&quot;);</p><p>  // Protocol version ordering
  static_assert(PROTOCOL_VERSION_66 &lt; PROTOCOL_VERSION_67, &quot;Protocol versions must be sequential&quot;);
  ```</p><p><h3>C++23 Features</h3></p><p><h4>1. `auto` Type Deduction</h4>
<ul><li><strong>Status</strong>: Already in use throughout Qt code</li>
<li><strong>Examples</strong>:</li>
  </ul>```cpp
  auto* layout = new QVBoxLayout(&amp;dlg);
  auto* button = new QPushButton(&quot;OK&quot;, &amp;dlg);
  ```</p><p><h4>2. Range-based Initialization</h4>
<ul><li><strong>Status</strong>: Already in use throughout Qt code</li>
<li><strong>Examples</strong>:</li>
  </ul>```cpp
  const QStringList exts = {QStringLiteral(&quot;<em>.tga&quot;), QStringLiteral(&quot;</em>.jpg&quot;)};
  const char* modeNames[] = {&quot;None&quot;, &quot;Box&quot;, &quot;Gizmo&quot;};
  ```</p><p><h4>3. Standard Library Usage</h4>
<ul><li><strong>Status</strong>: Already using modern STL features</li>
<li><strong>Examples</strong>:</li>
  </ul>```cpp
  const int w = std::max(1, width());
  snapped.setX(std::round(snapped.x() / grid) * grid);
  ```</p><p><h2>Planned Features</h2></p><p><h3>C23 Features to Adopt</h3></p><p><h4>1. `_Generic` Selections</h4>
<ul><li><strong>Use Case</strong>: Type-generic programming for math utilities</li>
<li><strong>Example</strong>:</li>
  </ul>```c
  #define min(a, b) _Generic((a), \
      int: min_int, \
      float: min_float, \
      double: min_double)(a, b)
  ```</p><p><h4>2. `typeof` Operator</h4>
<ul><li><strong>Use Case</strong>: Generic macro definitions</li>
<li><strong>Example</strong>:</li>
  </ul>```c
  #define SWAP(a, b) do { \
      typeof(a) temp = a; \
      a = b; \
      b = temp; \
  } while(0)
  ```</p><p><h4>3. Binary Literals</h4>
<ul><li><strong>Use Case</strong>: Bit flag definitions</li>
<li><strong>Example</strong>:</li>
  </ul>```c
  #define FLAG_READ    0b0001
  #define FLAG_WRITE   0b0010
  #define FLAG_EXECUTE 0b0100
  ```</p><p><h3>C++23 Features to Adopt</h3></p><p><h4>1. `constexpr` Functions</h4>
<ul><li><strong>Use Case</strong>: Compile-time computation for configuration</li>
<li><strong>Example</strong>:</li>
  </ul>```cpp
  constexpr int CalculateBufferSize(int elements, int elementSize) {
      return elements * elementSize + 16; // Header overhead
  }
  ```</p><p><h4>2. Smart Pointers</h4>
<ul><li><strong>Use Case</strong>: Automatic memory management in Qt code</li>
<li><strong>Example</strong>:</li>
  </ul>```cpp
  auto dialog = std::make_unique&lt;QDialog&gt;(this);
  auto layout = std::make_unique&lt;QVBoxLayout&gt;(dialog.get());
  ```</p><p><h4>3. Range-based `for` Loops</h4>
<ul><li><strong>Use Case</strong>: Container iteration</li>
<li><strong>Example</strong>:</li>
  </ul>```cpp
  for (const auto&amp; item : itemList) {
      processItem(item);
  }
  ```</p><p><h4>4. Lambda Expressions</h4>
<ul><li><strong>Use Case</strong>: Event handlers and algorithms</li>
<li><strong>Example</strong>:</li>
  </ul>```cpp
  connect(button, &amp;QPushButton::clicked, [this]() {
      handleButtonClick();
  });
  ```</p><p><h2>Compiler Requirements</h2></p><p><h3>Current Requirements</h3>
<ul><li><strong>C Standard</strong>: C23 (ISO/IEC 9899:2023)</li>
<li><strong>C++ Standard</strong>: C++23 (ISO/IEC 14882:2023)</li>
<li><strong>Compiler Support</strong>:</li>
<li>GCC 15.0+ (C23, C++23)</li>
<li>Clang 18.0+ (C23, C++23)</li>
<li>MSVC 19.40+ (partial C++23)</li></ul></p><p><h3>Feature Detection</h3>
```cmake
<h1>C23 feature detection</h1>
if(CMAKE_C_COMPILER_ID MATCHES &quot;GNU|Clang&quot;)
    add_compile_options(-std=c2x)  # C23 draft
endif()</p><p><h1>C++23 feature detection</h1>
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```</p><p><h2>Migration Strategy</h2></p><p><h3>Phase 1: Core Adoption (Completed)</h3>
<ul><li>[x] `nullptr` in C code</li>
<li>[x] Designated initializers</li>
<li>[x] Static assertions</li>
<li>[x] Modern Qt/C++ features</li></ul></p><p><h3>Phase 2: Advanced Features (Planned)</h3>
<ul><li>[ ] `_Generic` selections for type-generic utilities</li>
<li>[ ] `constexpr` functions where applicable</li>
<li>[ ] Smart pointers in Qt code</li>
<li>[ ] Enhanced lambda usage</li></ul></p><p><h3>Phase 3: Optimization (Future)</h3>
<ul><li>[ ] Compile-time computation for configuration</li>
<li>[ ] Template metaprogramming where beneficial</li>
<li>[ ] Advanced C++23 features as compiler support matures</li></ul></p><p><h2>Compatibility Considerations</h2></p><p><h3>Backward Compatibility</h3>
<ul><li><strong>QVM Interface</strong>: Maintains C ABI compatibility</li>
<li><strong>Network Protocol</strong>: No changes to wire formats</li>
<li><strong>Save Files</strong>: No changes to persistent data structures</li></ul></p><p><h3>Compiler Compatibility</h3>
<ul><li><strong>Legacy Builds</strong>: CMake options to disable modern features if needed</li>
<li><strong>Fallback Code</strong>: Provide C89/C++11 fallbacks where critical</li>
<li><strong>Feature Detection</strong>: Runtime detection of available features</li></ul></p><p><h2>Benefits</h2></p><p><h3>Code Quality</h3>
<ul><li><strong>Type Safety</strong>: `nullptr` prevents NULL pointer confusion</li>
<li><strong>Clarity</strong>: Designated initializers self-document structure fields</li>
<li><strong>Correctness</strong>: Static assertions catch structural issues at compile time</li></ul></p><p><h3>Maintainability</h3>
<ul><li><strong>Readability</strong>: Modern syntax reduces boilerplate</li>
<li><strong>Consistency</strong>: Standardized initialization patterns</li>
<li><strong>Future-Proofing</strong>: Foundation for further modernization</li></ul></p><p><h3>Performance</h3>
<ul><li><strong>Compile-time Verification</strong>: Static assertions prevent runtime errors</li>
<li><strong>Optimization</strong>: Modern features enable better compiler optimizations</li>
<li><strong>Debugging</strong>: Better error messages and debugging information</li></ul></p><p><h2>Testing and Validation</h2></p><p><h3>Feature Testing</h3>
```c
// Test nullptr support
void *ptr = nullptr;
assert(ptr == NULL);  // Should work in C23</p><p>// Test designated initializers
struct Test { int a, b, c; };
struct Test t = { .a = 1, .b = 2, .c = 3 };</p><p>// Test static assertions
static_assert(sizeof(int) &gt;= 4, &quot;int must be at least 32-bit&quot;);
```</p><p><h3>CI Integration</h3>
```yaml
<h1>Test modern features</h1>
<ul><li>name: Test C23 features</li>
  </ul>run: |
    gcc -std=c2x -c test_nullptr.c
    gcc -std=c2x -c test_designated.c
<ul><li>name: Test C++23 features</li>
  </ul>run: |
    g++ -std=c++23 -c test_auto.cpp
    g++ -std=c++23 -c test_constexpr.cpp
```</p><p><h2>Documentation</h2></p><p><h3>Developer Guidelines</h3>
1. <strong>Use `nullptr`</strong> instead of `NULL` in new C code
2. <strong>Use designated initializers</strong> for structure initialization
3. <strong>Add static assertions</strong> for critical size/alignment requirements
4. <strong>Use modern C++ features</strong> in Qt code where appropriate</p><p><h3>Code Review Checklist</h3>
<ul><li>[ ] `nullptr` used instead of `NULL` in C code</li>
<li>[ ] Designated initializers used for clarity</li>
<li>[ ] Static assertions added for critical constraints</li>
<li>[ ] Modern C++ features used appropriately</li>
<li>[ ] Compiler compatibility maintained</li></ul></p><p>This modernization effort brings id Tech 3&#039;s codebase in line with contemporary C/C++ best practices while maintaining the stability and compatibility required for a mature game engine.</p>
</div>