<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>NetRadiant Features Implementation Plan</h1></p><p><h2>Overview</h2>
This document outlines the implementation plan for porting NetRadiant-inspired features into the Qt6 Radiant editor.</p><p><h2>Feature Priority &amp; Status</h2></p><p><h3>1. Unhardcoded Engine Path in Gamepacks ⚠️ IN PROGRESS</h3>
<strong>Status</strong>: Starting implementation
<strong>Files to modify</strong>:
<ul><li>`radiant/qt/qt_env.cpp` - Path expansion utility</li>
<li>`radiant/qt/path_expander.h` - NEW: Path expansion class</li>
<li>`radiant/qt/path_expander.cpp` - NEW: Implementation</li>
<li>Gamepack loading code (TBD: locate gamepack parser)</li></ul></p><p><strong>Implementation steps</strong>:
1. Create `PathExpander` utility class supporting:
<ul><li>`%VAR%` (Windows-style) and `${VAR}` (Unix-style) expansion</li>
<li>`~` home directory expansion</li>
<li>XDG environment variables (`${XDG_CONFIG_HOME}`, `${XDG_DATA_HOME}`, `${XDG_CACHE_HOME}`)</li>
<li>Windows special paths (`%ProgramFiles%`, `%AppData%`, etc.)</li>
<li>Fallback handling (leave token unchanged + warn if var missing)</li>
<li>Path normalization (resolve `..`, normalize slashes)</li>
</ul>2. Integrate into `qt_env.cpp` for engine/game path resolution
3. Update gamepack schema/docs with examples
4. Add unit tests for path expansion</p><p><strong>Dependencies</strong>: None
<strong>Estimated effort</strong>: 2-3 hours</p><p>---</p><p><h3>2. User Path Change (Windows AppData / Cross-platform Config Dirs) ⏳ PENDING</h3>
<strong>Status</strong>: Not started
<strong>Files to modify</strong>:
<ul><li>`radiant/qt/qt_env.cpp` - Change `tempPath` to use XDG/AppData</li>
<li>`radiant/qt/config_migration.cpp` - NEW: Migration logic</li>
<li>`radiant/qt/config_migration.h` - NEW: Migration header</li>
<li>`radiant/qt/main_qt.cpp` - Add `--no-migrate` flag</li></ul></p><p><strong>Implementation steps</strong>:
1. Update `InitQtRadiantEnv()` to use:
<ul><li>Windows: `%AppData%/QtRadiant` (Roaming)</li>
<li>Linux: `$XDG_CONFIG_HOME/qtradiant` (default: `~/.config/qtradiant`)</li>
<li>macOS: `~/Library/Application Support/QtRadiant`</li>
</ul>2. Implement migration from `~/.radiant/`:
<ul><li>Detect old directory</li>
<li>Copy/move files (timestamp/size heuristic to avoid overwriting newer)</li>
<li>Log migration summary + failures</li>
</ul>3. Add `--no-migrate` CLI flag
4. Ensure separate folder names to avoid conflicts with other forks</p><p><strong>Dependencies</strong>: Feature 1 (path expansion)
<strong>Estimated effort</strong>: 3-4 hours</p><p>---</p><p><h3>3. Modifiable Camera Field of View (FOV) ⏳ PENDING</h3>
<strong>Status</strong>: UI exists, not connected
<strong>Files to modify</strong>:
<ul><li>`radiant/qt/vk_viewport.cpp` - Replace hardcoded 75.0f with preference value</li>
<li>`radiant/qt/preferences_dialog.cpp` - Already has FOV spinbox (line 113-116)</li>
<li>`radiant/qt/preferences_dialog.h` - Already has `m_fovSpin` member</li></ul></p><p><strong>Implementation steps</strong>:
1. Load FOV from QSettings in `VkViewportWidget` constructor
2. Replace hardcoded `75.0f` values (lines 368, 1260, 1783) with loaded value
3. Connect preference change signal to viewport update
4. Ensure correct behavior with mouse-look/fly mode
5. Add validation (60-120 range, or justify different range)</p><p><strong>Dependencies</strong>: None
<strong>Estimated effort</strong>: 1 hour</p><p>---</p><p><h3>4. DDS Prefix Support (Editor Asset Lookup) ⏳ PENDING</h3>
<strong>Status</strong>: Not started
<strong>Files to modify</strong>:
<ul><li>Texture loading code (TBD: locate texture loader)</li>
<li>Gamepack config - Add DDS prefix option</li>
<li>`radiant/qt/texture_extractor.cpp` - May need updates</li></ul></p><p><strong>Implementation steps</strong>:
1. Locate texture/material file resolution code
2. Implement fallback: `textures/foo/bar.tga` → `dds/textures/foo/bar.dds`
3. Make configurable per-gamepack
4. Add diagnostics (log once per session when DDS fallback resolves)
5. Ensure non-destructive (don&#039;t change canonical shader path)</p><p><strong>Dependencies</strong>: Feature 1 (gamepack config)
<strong>Estimated effort</strong>: 2-3 hours</p><p>---</p><p><h3>5. q3map2: IQM Model Baking ⏳ PENDING</h3>
<strong>Status</strong>: Not started
<strong>Files to modify</strong>:
<ul><li>`radiant/tools/quake3/q3map2/model.c` - Add IQM parsing</li>
<li>`radiant/tools/quake3/q3map2/q3map2.h` - Add IQM-related structures</li>
<li>`radiant/tools/quake3/q3map2/bsp.c` - Bake geometry into BSP</li>
<li>`radiant/tools/quake3/q3map2/light.c` - Lightmap baked geometry</li></ul></p><p><strong>Implementation steps</strong>:
1. Research IQM format specification
2. Add IQM parser to `model.c`
3. Implement geometry baking into BSP at compile time
4. Add lightmapping support for baked geometry
5. Maintain `misc_anim_model` fallback (engine-rendered)
6. Add CLI switches: `--bake-iqm`, `--no-bake-iqm`
7. Create test map + IQM fixture in `/testdata/`
8. Add CI script to compile test map</p><p><strong>Dependencies</strong>: None (standalone tool)
<strong>Estimated effort</strong>: 8-12 hours (complex)</p><p>---</p><p><h3>6. Clickable Linux Binary / Packaging Sanity ⏳ PENDING</h3>
<strong>Status</strong>: Not started
<strong>Files to modify</strong>:
<ul><li>`radiant/CMakeLists.txt` - Ensure correct ELF type</li>
<li>`tools/verify_binary.sh` - NEW: Verification script</li>
<li>`docs/BUILD.md` or `docs/TOOLS.md` - Packaging notes</li></ul></p><p><strong>Implementation steps</strong>:
1. Verify CMake produces `ET_EXEC` or PIE, not `ET_DYN` mis-detected
2. Ensure executable bit is set
3. Create/verify `.desktop` file + icon (if project packages one)
4. Create `verify_binary.sh` script checking:
<ul><li>`file &lt;binary&gt;` contains &quot;executable&quot;</li>
<li>Runtime Qt plugin paths are correct</li>
</ul>5. Add packaging notes for AppImage/Flatpak/zip</p><p><strong>Dependencies</strong>: None
<strong>Estimated effort</strong>: 1-2 hours</p><p>---</p><p><h2>System Locations Found</h2></p><p><h3>Gamepack Loading</h3>
<ul><li><strong>Location</strong>: TBD (need to search for `.game` file parser)</li>
<li><strong>References</strong>: `radiant/radiant/gtkdlgs.cpp` mentions `.game` files</li>
<li><strong>Action</strong>: Search for gamepack loading code</li></ul></p><p><h3>Preferences/Config</h3>
<ul><li><strong>Qt</strong>: `radiant/qt/preferences_dialog.cpp` (QSettings-based)</li>
<li><strong>GTK</strong>: `radiant/radiant/preferences.cpp` (XML-based)</li>
<li><strong>User dir</strong>: `radiant/qt/qt_env.cpp` (currently `~/.radiant/`)</li></ul></p><p><h3>Camera/Viewport</h3>
<ul><li><strong>Viewport</strong>: `radiant/qt/vk_viewport.cpp`</li>
<li><strong>FOV</strong>: Hardcoded `75.0f` at lines 368, 1260, 1783</li>
<li><strong>Preferences</strong>: `radiant/qt/preferences_dialog.cpp` (FOV spinbox exists)</li></ul></p><p><h3>Texture Loading</h3>
<ul><li><strong>Location</strong>: TBD (need to search)</li>
<li><strong>References</strong>: `radiant/qt/texture_extractor.cpp` exists</li>
<li><strong>Action</strong>: Search for texture file resolution code</li></ul></p><p><h3>q3map2</h3>
<ul><li><strong>Location</strong>: `radiant/tools/quake3/q3map2/`</li>
<li><strong>Model handling</strong>: `model.c` exists</li>
<li><strong>BSP writing</strong>: `bsp.c`, `writebsp.c` exist</li></ul></p><p>---</p><p><h2>Implementation Order</h2></p><p>1. ✅ <strong>Feature 1</strong> (Path Expansion) - Starting now
2. <strong>Feature 3</strong> (FOV) - Quick win, UI already exists
3. <strong>Feature 2</strong> (User Paths) - Depends on Feature 1
4. <strong>Feature 4</strong> (DDS Prefix) - Depends on Feature 1
5. <strong>Feature 6</strong> (Packaging) - Independent, can do anytime
6. <strong>Feature 5</strong> (IQM Baking) - Most complex, do last</p><p>---</p><p><h2>Notes</h2>
<ul><li><strong>Wayland Safety</strong>: Ensure Qt surfaces/resources are destroyed properly to avoid proxy leaks</li>
<li><strong>Cross-platform</strong>: All features must work on Linux/Windows/macOS unless explicitly OS-specific</li>
<li><strong>Documentation</strong>: Each feature needs docs in `/docs/` or nearest existing docs location</li>
<li><strong>Testing</strong>: Add small regression tests or validation steps for each feature</li>
</ul></p>
</div>