<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Performance Tuning Guide</h1></p><p><h2>Overview</h2></p><p>This guide provides comprehensive information on optimizing id Tech 3 engine performance, including profiling tools, optimization techniques, CVar tuning, and best practices for developers and end users.</p><p><h2>Table of Contents</h2></p><p>1. <a href="#performance-profiling">Performance Profiling</a>
2. <a href="#cpu-optimization">CPU Optimization</a>
3. <a href="#gpu-optimization">GPU Optimization</a>
4. <a href="#memory-optimization">Memory Optimization</a>
5. <a href="#network-optimization">Network Optimization</a>
6. <a href="#filesystem-optimization">Filesystem Optimization</a>
7. <a href="#cvar-reference">CVar Reference</a>
8. <a href="#benchmarking">Benchmarking</a>
9. <a href="#troubleshooting">Troubleshooting</a></p><p><h2>Performance Profiling</h2></p><p><h3>Built-in Performance Counters</h3></p><p>The engine includes built-in performance counters accessible via console command:</p><p>```
/perf
```</p><p><strong>Metrics Displayed:</strong>
<ul><li>FPS (current and average)</li>
<li>CPU Frame Time (current, average, min, max)</li>
<li>GPU Frame Time (when available)</li>
<li>Draw Calls (current, average, min, max, total)</li></ul></p><p><strong>ImGui Overlay:</strong>
Enable the profiler overlay for real-time monitoring:
```
/set cl_imgui_debug_profiler 1
```</p><p><h3>Tracy Profiler</h3></p><p>For detailed profiling, use Tracy Profiler:</p><p><strong>Build with Tracy:</strong>
```bash
cmake .. -DUSE_TRACY=ON
make
```</p><p><strong>Usage:</strong>
1. Run the engine
2. Connect Tracy client to capture profiling data
3. Analyze hotspots and bottlenecks</p><p><strong>Integration Points:</strong>
<ul><li>`PROF_ZONE_BEGIN()` / `PROF_ZONE_END()` macros throughout codebase</li>
<li>Automatic zones for major subsystems (Com_Printf, Z_TagMalloc, Event Processing)</li></ul></p><p><h3>GPU Timing Queries</h3></p><p>GPU frame time is automatically measured using Vulkan timestamp queries and integrated into performance counters. This provides accurate GPU-side timing separate from CPU timing.</p><p><strong>View GPU Timing:</strong>
```
/perf
```</p><p>Or enable ImGui profiler overlay to see CPU/GPU ratio.</p><p><h2>CPU Optimization</h2></p><p><h3>Frame Time Targets</h3>
<ul><li><strong>60 FPS</strong>: 16.67ms per frame</li>
<li><strong>120 FPS</strong>: 8.33ms per frame</li>
<li><strong>144 FPS</strong>: 6.94ms per frame</li></ul></p><p><h3>Optimization Strategies</h3></p><p><h4>1. Reduce Draw Calls</h4></p><p><strong>Problem</strong>: High draw call count increases CPU overhead.</p><p><strong>Solutions:</strong>
<ul><li>Enable VBO caching for static geometry</li>
<li>Use instanced rendering where possible</li>
<li>Batch similar geometry together</li>
<li>Reduce overdraw with proper culling</li></ul></p><p><strong>Monitor:</strong>
```
/perf  # Check draw call count
/set r_speeds 1  # Detailed renderer stats
```</p><p><h4>2. Optimize Hot Paths</h4></p><p><strong>Identify Hot Paths:</strong>
<ul><li>Use Tracy Profiler to find functions taking &gt;1ms</li>
<li>Enable performance counters to track frame time spikes</li>
<li>Profile with `-DENABLE_COVERAGE=ON` to find frequently executed code</li></ul></p><p><strong>Common Hot Paths:</strong>
<ul><li>`Com_Printf()` - Use structured logging with filtering</li>
<li>`Z_TagMalloc()` / `Z_Free()` - Minimize allocations per frame</li>
<li>Event processing - Batch events, use deferred processing</li>
<li>String operations - Use cached paths, avoid repeated allocations</li></ul></p><p><h4>3. Reduce Memory Allocations</h4></p><p><strong>Problem</strong>: Frequent allocations cause frame time spikes.</p><p><strong>Solutions:</strong>
<ul><li>Pre-allocate buffers at startup</li>
<li>Use memory pools for frequent allocations</li>
<li>Reuse temporary buffers</li>
<li>Minimize string allocations</li></ul></p><p><strong>Monitor:</strong>
```
/memstats  # Check memory allocation patterns
```</p><p><h4>4. Optimize String Operations</h4></p><p><strong>Filesystem Caching:</strong>
```
/set fs_pathNormCache 1  # Cache normalized paths (~30-40% reduction)
/set fs_pathCache 1      # Cache path lookups (~50-60% reduction)
/set fs_existenceCache 1 # Cache file existence checks (~70-80% reduction)
```</p><p><strong>Best Practices:</strong>
<ul><li>Use `Q_strncpyz()` instead of `strcpy()`</li>
<li>Cache frequently accessed strings</li>
<li>Avoid repeated path normalization</li></ul></p><p><h2>GPU Optimization</h2></p><p><h3>Renderer Settings</h3></p><p><h4>Vulkan Renderer</h4></p><p><strong>Recommended Settings:</strong>
```
/set r_renderer vulkan
/set r_vk_msaa 4          # 4x MSAA (adjust based on GPU)
/set r_vk_anisotropy 16   # 16x anisotropic filtering
/set r_vk_shadows 1       # Enable shadows
```</p><p><h4>OpenGL Renderer</h4></p><p><strong>Recommended Settings:</strong>
```
/set r_renderer opengl
/set r_ext_multisample 1
/set r_ext_anisotropic 1
/set r_ext_texture_filter_anisotropic 16
```</p><p><h3>Texture Optimization</h3></p><p><strong>Compression:</strong>
<ul><li>Use compressed texture formats (DXT/BC, ASTC, ETC2)</li>
<li>Enable `r_ext_compressed_textures 1`</li>
<li>Pre-compress textures in asset pipeline</li></ul></p><p><strong>Mipmaps:</strong>
<ul><li>Always generate mipmaps for textures</li>
<li>Use appropriate mipmap filtering</li>
<li>Set `r_textureMode GL_LINEAR_MIPMAP_LINEAR`</li></ul></p><p><strong>Size:</strong>
<ul><li>Use appropriate texture sizes (power of 2)</li>
<li>Avoid oversized textures</li>
<li>Use texture atlases where possible</li></ul></p><p><h3>Shader Optimization</h3></p><p><strong>Best Practices:</strong>
<ul><li>Minimize texture samples</li>
<li>Use texture arrays instead of multiple textures</li>
<li>Optimize shader math (use `mad` instructions)</li>
<li>Avoid dynamic branching in hot paths</li>
<li>Use appropriate precision (mediump vs highp)</li></ul></p><p><strong>Shader Caching:</strong>
<ul><li>Enable persistent pipeline cache (Vulkan)</li>
<li>Pre-warm shaders at level load</li>
<li>Monitor shader compilation time</li></ul></p><p><h3>Culling and Occlusion</h3></p><p><strong>Enable Culling:</strong>
```
/set r_cull 1              # Frustum culling
/set r_occlusion 1        # Occlusion culling (if available)
```</p><p><strong>Optimize BSP:</strong>
<ul><li>Ensure proper BSP compilation</li>
<li>Use `-vis` for visibility optimization</li>
<li>Use `-light` for lighting optimization</li></ul></p><p><h3>Draw Call Optimization</h3></p><p><strong>Monitor Draw Calls:</strong>
```
/perf  # Check draw call statistics
/set r_speeds 1  # Detailed renderer information
```</p><p><strong>Reduce Draw Calls:</strong>
<ul><li>Enable VBO caching: `r_vbo_cache 1`</li>
<li>Use instanced rendering for repeated geometry</li>
<li>Batch similar materials together</li>
<li>Reduce overdraw with proper depth testing</li></ul></p><p><h2>Memory Optimization</h2></p><p><h3>Memory Tracking</h3></p><p><strong>Enable Memory Tracking:</strong>
```
/set memtrack_enable 1
/set memtrack_report_leaks 1
```</p><p><strong>View Statistics:</strong>
```
/memstats  # Detailed memory statistics by tag
```</p><p><strong>ImGui Overlay:</strong>
```
/set cl_imgui_debug_memory 1
```</p><p><h3>Memory Allocation Strategies</h3></p><p><h4>Zone Allocator</h4></p><p>The zone allocator (`Z_TagMalloc`/`Z_Free`) is optimized for game workloads:</p><p><strong>Tags:</strong>
<ul><li>`TAG_GENERAL` - General allocations</li>
<li>`TAG_RENDERER` - Renderer-specific</li>
<li>`TAG_SOUND` - Audio system</li>
<li>`TAG_TEMP` - Temporary allocations</li></ul></p><p><strong>Best Practices:</strong>
<ul><li>Use appropriate tags for tracking</li>
<li>Free temporary allocations promptly</li>
<li>Avoid memory leaks (use `memtrack_enable`)</li></ul></p><p><h4>Memory Pools</h4></p><p>For frequent allocations, consider memory pools:
<ul><li>Pre-allocate pools at startup</li>
<li>Reuse pool allocations</li>
<li>Monitor pool usage with `memstats`</li></ul></p><p><h3>Memory Leak Detection</h3></p><p><strong>Development Builds:</strong>
```bash
cmake .. -DENABLE_SANITIZERS=ON
make
```</p><p><strong>Runtime Detection:</strong>
```
/set memtrack_enable 1
/set memtrack_report_leaks 1
/set memtrack_log_leaks 1
```</p><p><strong>Valgrind:</strong>
```bash
./tools/run_valgrind.sh ./idtech3.x86_64
```</p><p><h2>Network Optimization</h2></p><p><h3>Bandwidth Optimization</h3></p><p><strong>Snapshot Rate:</strong>
```
/set sv_fps 20   # Server frame rate (default: 20)
/set cl_maxpackets 125  # Client packet rate
```</p><p><strong>Compression:</strong>
<ul><li>Enable network compression</li>
<li>Use delta compression for snapshots</li>
<li>Minimize snapshot size</li></ul></p><p><h3>Latency Optimization</h3></p><p><strong>Client Prediction:</strong>
<ul><li>Enable client-side prediction</li>
<li>Reduce input lag</li>
<li>Optimize interpolation</li></ul></p><p><strong>Server Optimization:</strong>
<ul><li>Minimize server frame time</li>
<li>Optimize entity updates</li>
<li>Use efficient networking code paths</li></ul></p><p><h3>Monitoring</h3></p><p><strong>Network Stats:</strong>
```
/set cl_imgui_debug_network 1  # Network overlay
/net_stats  # Network statistics (if available)
```</p><p><h2>Filesystem Optimization</h2></p><p><h3>Caching</h3></p><p><strong>Enable All Caches:</strong>
```
/set fs_pathNormCache 1   # Path normalization cache
/set fs_pathCache 1       # Path lookup cache
/set fs_existenceCache 1  # File existence cache
```</p><p><strong>Cache Sizes:</strong>
```
/set fs_cacheSize 1024    # Path cache size (default: 1024)
```</p><p><strong>Impact:</strong>
<ul><li>Path normalization: ~30-40% reduction</li>
<li>Path lookup: ~50-60% reduction</li>
<li>File existence: ~70-80% reduction in stat() calls</li></ul></p><p><h3>File Access Patterns</h3></p><p><strong>Best Practices:</strong>
<ul><li>Keep file paths short</li>
<li>Use relative paths</li>
<li>Minimize file opens/closes</li>
<li>Batch file operations</li>
<li>Use SSD storage when possible</li></ul></p><p><strong>Handle Caching:</strong>
<ul><li>File handles are cached automatically (max 384 handles)</li>
<li>Reduces open/close overhead</li>
<li>Monitor with filesystem profiling</li></ul></p><p><h2>CVar Reference</h2></p><p><h3>Performance-Related CVars</h3></p><p><h4>Renderer</h4>
```
r_renderer          - Renderer backend (opengl/vulkan)
r_vk_msaa          - Vulkan MSAA samples (0/2/4/8)
r_vk_anisotropy    - Anisotropic filtering (0-16)
r_vbo_cache        - Enable VBO caching (0/1)
r_cull             - Enable frustum culling (0/1)
r_speeds           - Renderer performance stats (0-6)
```</p><p><h4>Filesystem</h4>
```
fs_pathNormCache   - Path normalization cache (0/1)
fs_pathCache       - Path lookup cache (0/1)
fs_existenceCache  - File existence cache (0/1)
fs_cacheSize       - Path cache size (default: 1024)
```</p><p><h4>Memory</h4>
```
memtrack_enable        - Enable memory tracking (0/1)
memtrack_report_leaks - Report leaks on shutdown (0/1)
memtrack_log_leaks     - Log leaks to file (0/1)
```</p><p><h4>Performance Counters</h4>
```
cl_imgui_debug_performance - Performance overlay (0/1)
cl_imgui_debug_profiler    - Profiler overlay (0/1)
```</p><p><h4>Network</h4>
```
sv_fps           - Server frame rate (default: 20)
cl_maxpackets    - Client packet rate (default: 125)
```</p><p><h2>Benchmarking</h2></p><p><h3>Built-in Benchmarks</h3></p><p><strong>Run Benchmarks:</strong>
```bash
./tools/run_benchmarks.sh
```</p><p><strong>Metrics:</strong>
<ul><li>Startup time</li>
<li>Memory usage</li>
<li>Binary size</li>
<li>Build time</li></ul></p><p><h3>Custom Benchmarking</h3></p><p><strong>Frame Time Measurement:</strong>
```
/timedemo &lt;demo&gt;  # Run timedemo
/perf             # View performance counters
```</p><p><strong>Profiling:</strong>
1. Enable Tracy Profiler
2. Capture profiling session
3. Analyze hotspots
4. Compare before/after optimizations</p><p><h3>Performance Regression Testing</h3></p><p><strong>CI Integration:</strong>
<ul><li>Automated benchmarks in CI</li>
<li>Performance regression gates</li>
<li>Threshold-based failure (fail if &gt;X% regression)</li></ul></p><p><strong>Local Testing:</strong>
```bash
<h1>Run benchmarks</h1>
./tools/run_benchmarks.sh</p><p><h1>Compare results</h1>
diff benchmark_before.txt benchmark_after.txt
```</p><p><h2>Troubleshooting</h2></p><p><h3>High CPU Usage</h3></p><p><strong>Symptoms:</strong>
<ul><li>Low FPS despite low GPU usage</li>
<li>High frame time variance</li>
<li>CPU bottleneck</li></ul></p><p><strong>Diagnosis:</strong>
1. Enable performance counters: `/perf`
2. Check draw call count
3. Profile with Tracy
4. Check memory allocation patterns: `/memstats`</p><p><strong>Solutions:</strong>
<ul><li>Reduce draw calls</li>
<li>Optimize hot paths</li>
<li>Reduce memory allocations</li>
<li>Enable filesystem caches</li></ul></p><p><h3>High GPU Usage</h3></p><p><strong>Symptoms:</strong>
<ul><li>High GPU utilization</li>
<li>Low FPS with high GPU usage</li>
<li>GPU bottleneck</li></ul></p><p><strong>Diagnosis:</strong>
1. Check GPU frame time: `/perf`
2. Enable renderer stats: `/set r_speeds 1`
3. Check texture memory usage
4. Monitor draw calls</p><p><strong>Solutions:</strong>
<ul><li>Reduce texture sizes</li>
<li>Lower MSAA samples</li>
<li>Reduce shadow quality</li>
<li>Optimize shaders</li>
<li>Enable culling</li></ul></p><p><h3>Memory Issues</h3></p><p><strong>Symptoms:</strong>
<ul><li>Memory leaks</li>
<li>High memory usage</li>
<li>Out of memory errors</li></ul></p><p><strong>Diagnosis:</strong>
1. Enable memory tracking: `/set memtrack_enable 1`
2. Check memory stats: `/memstats`
3. Run with sanitizers: `-DENABLE_SANITIZERS=ON`
4. Use Valgrind: `./tools/run_valgrind.sh`</p><p><strong>Solutions:</strong>
<ul><li>Fix memory leaks</li>
<li>Reduce memory allocations</li>
<li>Use memory pools</li>
<li>Optimize data structures</li></ul></p><p><h3>Network Issues</h3></p><p><strong>Symptoms:</strong>
<ul><li>High latency</li>
<li>Packet loss</li>
<li>Network lag</li></ul></p><p><strong>Diagnosis:</strong>
1. Enable network overlay: `/set cl_imgui_debug_network 1`
2. Check network stats
3. Monitor packet rates</p><p><strong>Solutions:</strong>
<ul><li>Adjust snapshot rate</li>
<li>Optimize network code</li>
<li>Reduce snapshot size</li>
<li>Enable compression</li></ul></p><p><h2>Best Practices</h2></p><p><h3>Development</h3></p><p>1. <strong>Profile First</strong>: Always profile before optimizing
2. <strong>Measure Changes</strong>: Benchmark before/after optimizations
3. <strong>Use Tools</strong>: Leverage Tracy, sanitizers, and built-in counters
4. <strong>Monitor Metrics</strong>: Track FPS, frame time, memory, draw calls
5. <strong>Test Thoroughly</strong>: Ensure optimizations don&#039;t break functionality</p><p><h3>Code Optimization</h3></p><p>1. <strong>Hot Paths</strong>: Optimize frequently executed code first
2. <strong>Memory</strong>: Minimize allocations, use pools, fix leaks
3. <strong>Caching</strong>: Enable filesystem caches, cache computations
4. <strong>Batching</strong>: Batch operations, reduce draw calls
5. <strong>Algorithms</strong>: Use efficient algorithms and data structures</p><p><h3>User Configuration</h3></p><p>1. <strong>Hardware</strong>: Use appropriate settings for hardware
2. <strong>Resolution</strong>: Match resolution to GPU capability
3. <strong>Quality</strong>: Balance quality vs performance
4. <strong>Monitoring</strong>: Use performance overlays to identify bottlenecks
5. <strong>Updates</strong>: Keep drivers and engine updated</p><p><h2>Related Documentation</h2>
<ul><li><a href="optimization-and-stability.md">Optimization and Stability</a> - Existing optimizations</li>
<li><a href="MEMORY_SAFETY_WORKFLOWS.md">Memory Safety Workflows</a> - Memory debugging</li>
<li><a href="CODE_COVERAGE.md">Code Coverage</a> - Finding hot paths</li>
<li><a href="STATIC_ANALYSIS_WORKFLOW.md">Static Analysis Workflow</a> - Code quality</li></ul></p><p><h2>Summary</h2></p><p><strong>Key Performance Metrics:</strong>
<ul><li><strong>FPS</strong>: Target 60+ FPS (16.67ms frame time)</li>
<li><strong>Draw Calls</strong>: Minimize per frame (&lt;1000 ideal)</li>
<li><strong>Memory</strong>: Track leaks, optimize allocations</li>
<li><strong>GPU Time</strong>: Monitor GPU frame time vs CPU frame time</li></ul></p><p><strong>Essential Tools:</strong>
<ul><li>Built-in performance counters (`/perf`)</li>
<li>Tracy Profiler (detailed profiling)</li>
<li>Memory tracking (`/memstats`)</li>
<li>ImGui debug overlays</li></ul></p><p><strong>Quick Wins:</strong>
1. Enable filesystem caches
2. Enable VBO caching
3. Reduce draw calls
4. Fix memory leaks
5. Optimize hot paths</p><p>Following this guide will help achieve optimal performance while maintaining code quality and stability.
</p>
</div>