<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>GTK Radiant Plugin Compatibility for Qt Radiant</h1></p><p><h2>Overview</h2></p><p>Qt Radiant aims to maintain compatibility with GTK Radiant plugins to allow users to use existing plugins without modification. This document describes the compatibility layer and implementation status.</p><p><h2>GTK Radiant Plugin System</h2></p><p>GTK Radiant uses the <strong>Synapse</strong> plugin system:
<ul><li>Plugins are shared libraries (`.so` on Linux, `.dll` on Windows)</li>
<li>Plugins export `Synapse_EnumerateInterfaces()` function</li>
<li>Plugins implement function tables (e.g., `_QERPluginTable`, `_QERFuncTable_1`)</li>
<li>Plugins are loaded from `plugins/` and `modules/` directories</li>
<li>Plugins can provide multiple APIs (IMAGE_MAJOR, PLUGIN_MAJOR, TOOLBAR_MAJOR, etc.)</li></ul></p><p><h2>Plugin Loading Locations</h2></p><p>GTK Radiant loads plugins from:
1. `&lt;appPath&gt;/plugins/` - Application plugins directory
2. `&lt;gameToolsPath&gt;/plugins/` - Game-specific plugins directory
3. `&lt;appPath&gt;/modules/` - Application modules directory (if different from plugins)
4. `&lt;gameToolsPath&gt;/modules/` - Game-specific modules directory</p><p><h2>Implementation Status</h2></p><p><h3>✅ Completed</h3>
<ul><li>Plugin loader framework (`radiant/qt/plugin_loader.h`)</li>
<li>Basic plugin discovery and loading structure</li></ul></p><p><h3>🚧 In Progress</h3>
<ul><li>Synapse API compatibility layer</li>
<li>GTK-to-Qt function call bridging</li></ul></p><p><h3>⏳ Pending</h3>
<ul><li>Full Synapse server/client implementation</li>
<li>GTK widget API bridging (for plugins that create UI)</li>
<li>OpenGL context bridging (for plugins that render)</li>
<li>File system API compatibility</li>
<li>Entity/brush API compatibility</li></ul></p><p><h2>Plugin API Compatibility</h2></p><p><h3>Core APIs Required</h3></p><p>1. <strong>RADIANT_MAJOR</strong> - Core editor functionality
<ul><li>Brush creation/manipulation</li>
<li>Selection management</li>
<li>Texture operations</li>
<li>Map operations</li></ul></p><p>2. <strong>PLUGIN_MAJOR</strong> - Plugin menu commands
<ul><li>`QERPlug_Init()`</li>
<li>`QERPlug_GetName()`</li>
<li>`QERPlug_GetCommandList()`</li>
<li>`QERPlug_Dispatch()`</li></ul></p><p>3. <strong>IMAGE_MAJOR</strong> - Image format support
<ul><li>Texture loading</li>
<li>Image format handlers</li></ul></p><p>4. <strong>QGL_MAJOR</strong> - OpenGL operations
<ul><li>OpenGL function table</li>
<li>Context management</li></ul></p><p>5. <strong>UI_MAJOR / UIGTK_MAJOR</strong> - User interface
<ul><li>Window creation</li>
<li>Widget management</li>
<li><strong>Note</strong>: GTK-specific APIs need Qt equivalents</li></ul></p><p><h3>GTK-to-Qt Bridging</h3></p><p>Many plugins use GTK-specific APIs that need Qt equivalents:</p><p>| GTK API | Qt Equivalent | Status |
|---------|---------------|--------|
| `gtk_MessageBox` | `QMessageBox` | ✅ Easy |
| `file_dialog` | `QFileDialog` | ✅ Easy |
| `color_dialog` | `QColorDialog` | ✅ Easy |
| `gtk_glwidget_*` | `QOpenGLWidget` | 🚧 Needs work |
| `GtkWidget<em>` | `QWidget</em>` | 🚧 Needs adapter |
| `g_pMainWidget` | `QMainWindow*` | ✅ Easy |</p><p><h2>Usage</h2></p><p><h3>Loading Plugins</h3></p><p>```cpp
#include &quot;plugin_loader.h&quot;</p><p>PluginLoader loader;
int count = loader.loadPlugins(appPath, gameToolsPath);
qDebug() &lt;&lt; &quot;Loaded&quot; &lt;&lt; count &lt;&lt; &quot;plugins&quot;;
```</p><p><h3>Accessing Plugin Commands</h3></p><p>```cpp
QStringList plugins = loader.loadedPlugins();
for (const QString&amp; name : plugins) {
    QString commands = loader.getPluginCommands(name);
    // Parse commands and add to menu
}
```</p><p><h3>Dispatching Commands</h3></p><p>```cpp
loader.dispatchCommand(&quot;plugin_name&quot;, &quot;CommandName&quot;);
```</p><p><h2>Implementation Notes</h2></p><p><h3>Synapse Compatibility</h3></p><p>The Synapse plugin system is complex and requires:
<ul><li>Full Synapse server implementation (or reuse from `radiant/libs/synapse`)</li>
<li>API descriptor management</li>
<li>Function table population</li>
<li>Dependency resolution</li></ul></p><p><strong>Option 1</strong>: Reuse existing Synapse code from `radiant/libs/synapse/`
<ul><li>Pros: Full compatibility, less code to maintain</li>
<li>Cons: Depends on GLib, libxml, GTK dependencies</li></ul></p><p><strong>Option 2</strong>: Implement minimal Synapse compatibility layer
<ul><li>Pros: Qt-native, no external dependencies</li>
<li>Cons: May not support all plugins, more work</li></ul></p><p><h3>Recommended Approach</h3></p><p>1. <strong>Phase 1</strong>: Implement basic plugin loading
<ul><li>Load `.so`/`.dll` files</li>
<li>Find `Synapse_EnumerateInterfaces` symbol</li>
<li>Basic function table population</li></ul></p><p>2. <strong>Phase 2</strong>: Implement core API bridges
<ul><li>RADIANT_MAJOR (brush/texture/map operations)</li>
<li>PLUGIN_MAJOR (menu commands)</li>
<li>Basic UI dialogs (message box, file dialog)</li></ul></p><p>3. <strong>Phase 3</strong>: Advanced compatibility
<ul><li>OpenGL context bridging</li>
<li>GTK widget to Qt widget adapters</li>
<li>Full Synapse server (if needed)</li></ul></p><p><h2>Testing</h2></p><p>To test plugin compatibility:</p><p>1. Place a GTK Radiant plugin in `plugins/` directory
2. Start Qt Radiant
3. Check console for plugin load messages
4. Verify plugin commands appear in menu
5. Test plugin functionality</p><p><h2>Known Limitations</h2>
<ul><li><strong>GTK Widget APIs</strong>: Plugins that create GTK widgets directly won&#039;t work without adapters</li>
<li><strong>OpenGL Context</strong>: Plugins that manage their own OpenGL contexts may have issues</li>
<li><strong>Threading</strong>: Some plugins may assume GTK&#039;s threading model</li>
<li><strong>File System</strong>: VFS (Virtual File System) plugins may need special handling</li></ul></p><p><h2>Future Enhancements</h2>
<ul><li>Plugin manager UI (enable/disable plugins)</li>
<li>Plugin dependency resolution</li>
<li>Plugin API versioning</li>
<li>Hot-reload plugins (for development)</li>
<li>Plugin sandboxing (security)</li>
</ul></p>
</div>