<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Quake3e</h1>
&lt;html&gt;
&lt;p&gt;
This client aims to be fully compatible with original baseq3 and other mods
while trying to be fast, reliable and bug-free.
&lt;br&gt;
It is based on ioquake3-r1160 (latest non-SDL revision) with upstream patches an many custom improvements.&lt;br&gt;
&lt;br&gt;
&lt;b&gt;Common changes/additions:&lt;/b&gt;
&lt;ul&gt;
&lt;li&gt;a lot of security, performance and bug fixes&lt;/li&gt;
&lt;li&gt;much improved autocompletion (map, demo, exec and other commands), in-game &lt;b&gt;\callvote&lt;/b&gt; argument autocompletion&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\com_affinityMask&lt;/b&gt; - bind Quake3e process to bitmask-specified CPU core(s)&lt;/li&gt;
&lt;li&gt;raized filesystem limits, much faster startup with 1000+ pk3 files in use, level restart times were also reduced as well&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\fs_locked&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - keep opened pk3 files locked or not, removes pk3 file limit when unlocked&lt;/li&gt;
&lt;/ul&gt;
&lt;b&gt;Client-specific changes/additions:&lt;/b&gt;
&lt;ul&gt;
&lt;li&gt;raw mouse input support, enabled automatically instead of DirectInput(&lt;b&gt;\in_mouse 1&lt;/b&gt;) on Windows XP and newer windows operating systems&lt;/li&gt;
&lt;li&gt;unlagged mouse processing, can be reverted by setting &lt;b&gt;\in_lagged 1&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;MOUSE4 and MOUSE5 works in &lt;b&gt;\in_mouse -1&lt;/b&gt; mode&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\minimize&lt;/b&gt; in-game command to minimize main window, can be used with binds/scripting&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;#in_minimize&quot;&gt;&lt;b&gt;\in_minimize&lt;/b&gt;&lt;a&gt; - hotkey for minimize/restore main window (direct replacement for Q3Minimizer)&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\in_forceCharset&lt;/b&gt; &lt;font color=silver&gt;0|&lt;b&gt;1&lt;/b&gt;|2&lt;/font&gt; - try to translate non-ASCII chars in keyboard input (&lt;b&gt;1&lt;/b&gt;) or force EN/US keyboard layout (2)&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\in_nograb&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - do not capture mouse in game, may be useful during online streaming&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\s_muteWhenUnfocused&lt;/b&gt; &lt;font color=silver&gt;0|&lt;b&gt;1&lt;/b&gt;&lt;/font&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\s_muteWhenMinimized&lt;/b&gt; &lt;font color=silver&gt;0|&lt;b&gt;1&lt;/b&gt;&lt;/font&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\s_device&lt;/b&gt; - linux-only, specified sound device to use with ALSA, enter &lt;font color=green&gt;aplay -L&lt;/font&gt; in your shell to see all available options&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\screenshotBMP&lt;/b&gt; and &lt;b&gt;\screenshotBMP clipboard&lt;/b&gt; commands&lt;/li&gt;
&lt;li&gt;hardcoded PrintScreen key - for &quot;\screenshotBMP clipboard&quot;&lt;/li&gt;
&lt;li&gt;hardcoded Shift+PrintScreen - for &quot;\screenshotBMP&quot;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\com_maxfpsUnfocused&lt;/b&gt; - will save cpu when inactive,set to your desktop refresh rate, for example&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\com_skipIdLogo&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt;- skip playing idlogo movie at startup&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\com_yieldCPU &lt;/b&gt;&amp;lt;milliseconds&amp;gt; - try to sleep specified amout of time between rendered frames when game is active, this will greatly reduce CPU load, use &lt;b&gt;0&lt;/b&gt; only if you&#039;re experiencing some lags (also it is usually reduces performance on integrated graphics because CPU steals GPU&#039;s power budget)&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_defaultImage&lt;/b&gt; &lt;font color=silver&gt;&amp;lt;filename&amp;gt;|#rgb|#rrggbb&lt;/font&gt; - replace default (missing) image texture by either exact file or solid #rgb|#rrggbb background color&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_vbo&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - use Vertex Buffer Objects to cache static map geometry, may improve FPS on modern GPUs, increases hunk memory usage by 15-30MB (map-dependent)&lt;/li&gt;
&lt;div id=&quot;r_fbo&quot;&gt;&lt;/div&gt;
&lt;li&gt;&lt;b&gt;\r_fbo&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - use framebuffer objects, enables gamma correction in windowed mode and allows arbitrary size (i.e. greater than logical desktop resolution) screenshot/video capture, required for bloom, hdr rendering, anti-aliasing, greyscale effects, OpenGL 3.0+ required&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_hdr&lt;/b&gt; &lt;font color=silver&gt;-1|&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - select texture format for framebuffer:&lt;br&gt;
&amp;nbsp;&amp;nbsp;-1 - 4-bit, for testing purposes, heavy color banding, might not work on all systems&lt;br&gt;
&amp;nbsp;&amp;nbsp; 0 - 8 bit, default, moderate color banding with multi-stage shaders&lt;br&gt;
&amp;nbsp;&amp;nbsp; 1 - 16 bit, enhanced blending precision, no color banding, might decrease performance on AMD/Intel GPUs&lt;br&gt;
&lt;/li&gt;
&lt;li&gt;&lt;b&gt;&lt;a href=&quot;#r_bloom&quot;&gt;\r_bloom&lt;/a&gt;&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1|2&lt;/font&gt; - high-quality light bloom postprocessing effect&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_dlightMode&lt;/b&gt; &lt;font color=silver&gt;0|&lt;b&gt;1&lt;/b&gt;|2&lt;/font&gt; - dynamic light mode&lt;/li&gt;
&amp;nbsp;&amp;nbsp; 0 - VQ3 &#039;fake&#039; dynamic lights&lt;br&gt;
&amp;nbsp;&amp;nbsp; 1 - new high-quality per-pixel dynamic lights, slightly faster than VQ3&#039;s on modern hardware&lt;br&gt;
&amp;nbsp;&amp;nbsp; 2 - same as 1 but applies to all MD3 models too&lt;br&gt;
&lt;li&gt;&lt;b&gt;\r_modeFullscreen&lt;/b&gt; - dedicated mode string for fullscreen mode, set to -2 to use desktop resolution, set empty to use &lt;b&gt;\r_mode&lt;/b&gt; in all cases&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_nomip&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt;- apply picmip only on worldspawn textures&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_neatsky&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - nopicmip for skyboxes&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_greyscale&lt;/b&gt; &lt;font color=silver&gt;[&lt;b&gt;0&lt;/b&gt;..1.0]&lt;/font&gt; - desaturates rendered frame, requires &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;, can be changed on 	the fly&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_mapGreyScale&lt;/b&gt; &lt;font color=silver&gt;[-1.0..1.0]&lt;/font&gt; - desaturate world map textures only, works independently from &lt;b&gt;\r_greyscale&lt;/b&gt;, negative values desaturates lightmaps only&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_ext_multisample&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|2|4|6|8&lt;/font&gt; - multi-sample anti-aliasing, requires &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;, can be changed on the fly&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_ext_supersample&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - super-sample anti-aliasing, requires &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_noborder&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - to draw game window without border, hold ALT to drag &amp; drop it with opened console&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\r_noportals&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1|2&lt;/font&gt; - disable in-game portals (1), and mirrors too (2)&lt;/li&gt;
&lt;li&gt;negative &lt;b&gt;\r_overBrightBits&lt;/b&gt; - force hardware gamma in windowed mode &lt;i&gt;(not actual with &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;)&lt;/i&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;#video-pipe&quot;&gt;&lt;b&gt;\video-pipe&lt;/b&gt;&lt;/a&gt;&amp;nbsp;&lt;font color=silver&gt;&amp;lt;filename&amp;gt;&lt;/font&gt; - redirect captured video to ffmpeg input pipe and save encoded file as &amp;lt;filename&amp;gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;#arr&quot;&gt;&lt;b&gt;\r_renderWidth&lt;/b&gt; &amp;amp; &lt;b&gt;\r_renderHeight&lt;/b&gt;&lt;/a&gt; - arbitrary resolution rendering, requires &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\cl_conColor [RRR GGG BBB AAA]&lt;/b&gt; - custom console color, &lt;u&gt;non-archived, use &lt;b&gt;\seta&lt;/b&gt; command to set archive flag and store in config&lt;/u&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\cl_autoNudge&lt;/b&gt; &lt;font color=silver&gt;[&lt;b&gt;0&lt;/b&gt;..1]&lt;/font&gt; - automatic time nudge that uses your average ping as the time nudge, values:&lt;br&gt;
&amp;nbsp;&amp;nbsp; 0 - use fixed &lt;b&gt;\cl_timeNudge&lt;/b&gt;&lt;br&gt;
&amp;nbsp;&amp;nbsp; (0..1] - factor of median average ping to use as timenudge
&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\cl_mapAutoDownload&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - automatic map download for play and demo playback (via automatic &lt;a href=&quot;#dlmap&quot;&gt;&lt;b&gt;\dlmap&lt;/b&gt;&lt;/a&gt; call)&lt;/li&gt;
&lt;li&gt;less spam in console (try to set &quot;\developer 1&quot; to see what important things you missing)&lt;/li&gt;
&lt;/li&gt;
&lt;li&gt;faster shader loading, tolerant to non-fatal errors&lt;/li&gt;
&lt;li&gt;&lt;b&gt;fast client downloads (http/ftp redirection)&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;#dlmap&quot;&gt;&lt;b&gt;\download&lt;/b&gt; and &lt;b&gt;dlmap&lt;/b&gt; commands&lt;/a&gt; - fast client-initiated downloads from specified map server&lt;/li&gt;
&lt;li&gt;&lt;b&gt;you can use \record during \demo playback&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;&lt;a href=&quot;#condstages&quot;&gt;&lt;b&gt;conditional shader stages&lt;/b&gt;&lt;/a&gt;&lt;/li&gt;
&lt;li&gt;&lt;b&gt;linear dynamic lights&lt;/b&gt;&lt;/li&gt;
&lt;/ul&gt;</p><p>&lt;b&gt;Server-specific changes/additions:&lt;/b&gt;
&lt;ul&gt;
&lt;li&gt;&lt;b&gt;\sv_levelTimeReset&lt;/b&gt; &lt;font color=silver&gt;&lt;b&gt;0&lt;/b&gt;|1&lt;/font&gt; - reset or do not reset leveltime after new map loads, when enabled - fixes gfx for clients affected by &quot;frameloss&quot; bug, however it may be necessary disable in case of troubles with GTV&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\sv_maxclientsPerIP&lt;/b&gt; - limit number of simultaneous connections from the same IP address&lt;/li&gt;
&lt;li&gt;much improved DDoS protection&lt;/li&gt;
&lt;li&gt;&lt;b&gt;\sv_minPing&lt;/b&gt; and &lt;b&gt;\sv_maxPing&lt;/b&gt; were removed because of new much better client connecion code&lt;/li&gt;
&lt;li&gt;userinfo filtering system, see docs/filter.txt&lt;/li&gt;
&lt;li&gt;&lt;b&gt;rcon&lt;/b&gt; now is always available on dedicated servers&lt;/li&gt;
&lt;li&gt;&lt;b&gt;rconPassword2&lt;/b&gt; - hidden master rcon password that can be set only from command line, i.e.&lt;br&gt;
&amp;nbsp;&amp;nbsp;&lt;b&gt; +set rconPassword2 &quot;123456&quot;&lt;/b&gt;&lt;br&gt;
can be used to change/revoke compromised &lt;b&gt;rconPassword&lt;/b&gt;&lt;/li&gt;
&lt;li&gt;significally reduced memory usage for client slots&lt;/li&gt;
&lt;/li&gt;
&lt;/ul&gt;</p><p>&lt;hr&gt;
&lt;div id=&quot;in_minimize&quot;&gt;&lt;/div&gt;
&lt;p&gt;&lt;b&gt;\in_minimize&lt;/b&gt;
&lt;br&gt;
&lt;br&gt;
	cvar that specifies hotkey for fast minimize/restore main windows, set values in form &lt;br&gt;
	&amp;nbsp;&amp;nbsp;&lt;b&gt;\in_minimize &lt;font color=&quot;green&quot;&gt;&amp;quot;ctrl+z&amp;quot;&lt;/font&gt;&lt;/b&gt;&lt;br&gt;
	&amp;nbsp;&amp;nbsp;&lt;b&gt;\in_minimize &lt;font color=&quot;green&quot;&gt;&amp;quot;lshift+ralt+\&amp;quot;&lt;/font&gt;&lt;/b&gt;&lt;br&gt;
    &amp;nbsp;&amp;nbsp;or so then do &lt;b&gt;\in_restart&lt;/b&gt; to apply changes.&lt;/li&gt;
&lt;br&gt;
&lt;br&gt;</p><p>&lt;hr&gt;
&lt;p&gt;&lt;b&gt;Fast client downloads&lt;/b&gt;&lt;br&gt;&lt;br&gt;
Usually downloads in Q3 is slow because all dowloaded data is requested/revieced from game server directly.
So called `download redirection&#039; allows very fast downloads because game server just tells you from where you should download all required mods/maps etc. - it can be internet or local http/ftp server&lt;br&gt;
So what you need:
&lt;ul&gt;
&lt;li&gt;set &lt;b&gt;sv_dlURL&lt;/b&gt; cvar to download location, for example:&lt;br&gt;
	&amp;nbsp;&lt;b&gt;sets sv_dlURL &quot;ftp://myftp.com/games/q3&quot;&lt;/b&gt;&lt;br&gt;
	&lt;u&gt;Please note that your link should point on root game directory not particular mod or so&lt;/u&gt;
	&lt;br&gt;
&lt;/li&gt;</p><p>&lt;li&gt;Fill your download location with files.&lt;br&gt;
 &amp;nbsp;&amp;nbsp;Please note that you should post &lt;u&gt;ALL&lt;/u&gt; files that client may download, don&#039;t worry about pk3 overflows etc. on client side as client will download and use only required files
&lt;/li&gt;
&lt;/ul&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;div id=&quot;dlmap&quot;&gt;&lt;/div&gt;
&lt;p&gt;&lt;b&gt;Fast client-initiated downloads&lt;/b&gt;&lt;br&gt;&lt;br&gt;
You can easy download pk3 files you need from any ftp/http/etc resource via following commands: &lt;br&gt;</p><p>&lt;b&gt;\download&lt;/b&gt; &lt;b&gt;filename&lt;/b&gt;[.pk3]&lt;br&gt;
&lt;b&gt;\dlmap&lt;/b&gt; &lt;b&gt;mapname&lt;/b&gt;[.pk3]&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\dlmap&lt;/b&gt; is the same as &lt;b&gt;\download&lt;/b&gt; but also will check for map existence
&lt;br&gt;
&lt;br&gt;
&lt;b&gt;cl_dlURL&lt;/b&gt; cvar must points to download location, where (optional) &lt;b&gt;%1&lt;/b&gt; pattern will be replaced by &lt;b&gt;\download|dlmap&lt;/b&gt; command argument (filename/mapmane) and HTTP header may be analysed to obtain destination filename&lt;br&gt;&lt;br&gt;</p><p>For example: &lt;br&gt;&lt;br&gt;
&amp;nbsp;&amp;nbsp;1) If &lt;b&gt;cl_dlURL&lt;/b&gt; is &lt;b&gt;http://127.0.0.1&lt;/b&gt; and you type &lt;b&gt;\download &lt;u&gt;promaps.pk3&lt;/u&gt;&lt;/b&gt; -
&amp;nbsp;&amp;nbsp;resulting download url will be &lt;b&gt;http://127.0.0.1/promaps.pk3&lt;/b&gt;&lt;br&gt;
&amp;nbsp;&amp;nbsp;2) If &lt;b&gt;cl_dlURL&lt;/b&gt; is &lt;b&gt;http://127.0.0.1/%1&lt;/b&gt; and you type &lt;b&gt;\dlmap dm17&lt;/b&gt; -
&amp;nbsp;&amp;nbsp;resulting download url will be &lt;b&gt;http://127.0.0.1/dm17&lt;/b&gt;&lt;br&gt;
&amp;nbsp;&amp;nbsp;Also in this case HTTP-header will be analysed and resulting filename may be changed&lt;br&gt;</p><p>&lt;br&gt;
To stop download just specify &#039;-&#039; as argument:&lt;br&gt;
&lt;br&gt;
&amp;nbsp;&amp;nbsp;&lt;b&gt;\dlmap -&lt;/b&gt;
&lt;br&gt;&lt;br&gt;
&lt;b&gt;cl_dlDirectory&lt;/b&gt; cvar specifies where to save downloaded files:&lt;br&gt;&lt;br&gt;
&amp;nbsp;&amp;nbsp;&lt;b&gt;0&lt;/b&gt; - save in current game directory&lt;br&gt;
&amp;nbsp;&amp;nbsp;&lt;b&gt;1&lt;/b&gt; - save in fs_basegame (baseq3) directory&lt;br&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;p&gt; &lt;b&gt;Built-in URL-filter&lt;/b&gt;&lt;br&gt;&lt;br&gt;
There is ability to launch Quake3 1.32e client directly from your browser
by just clicking on URL that contains &lt;b&gt;q3a://&lt;/b&gt;
instead of usual &lt;b&gt;http://&lt;/b&gt; or &lt;b&gt;ftp://&lt;/b&gt; protocol headers&lt;br&gt;&lt;br&gt;</p><p>What you need to do:
&lt;ul&gt;
&lt;li&gt;copy &lt;b&gt;q3url_add.cmd&lt;/b&gt;/&lt;b&gt;q3url_rem.cmd&lt;/b&gt; in quake3e.exe directory &lt;/li&gt;
&lt;li&gt;run &lt;b&gt;q3url_add.cmd&lt;/b&gt; if you want to add protocol binding or &lt;b&gt;q3url_add.cmd&lt;/b&gt; if you want to remove it&lt;/li&gt;
&lt;li&gt;type in your browser &lt;a href=&quot;q3a://127.0.0.1&quot;&gt;&lt;b&gt;q3a://&lt;/b&gt;127.0.0.1&lt;/a&gt; and follow it - if you see quake3e launching and trying to connect then everything is fine
&lt;/li&gt;
&lt;/ul&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;p&gt;&lt;b&gt;&lt;div id=&quot;condstages&quot;&gt;&lt;/div&gt;Condifional shader stages&lt;/b&gt;&lt;br&gt;&lt;br&gt;
Optional &quot;if&quot;-&quot;elif&quot;-&quot;else&quot; keywords can be used to control which shaders stages can be loaded depending from some cvar values.&lt;br&gt;
For example, old shader:
&lt;pre&gt;
console
{
 nopicmip
 nomipmaps
 {
  map image1.tga
  blendFunc blend
  tcmod scale 1 1
  }
}
&lt;/pre&gt;
New shader:
&lt;pre&gt;
console
{
 nopicmip
 nomipmaps
 if ( $r_vertexLight == 1 &amp;&amp; $r_dynamicLight )
 {
  map image1.tga
  blendFunc blend
  tcmod scale 1 1
 }
 else
 {
  map image2.tga
  blendFunc add
  tcmod scale 1 1
 }
}
&lt;/pre&gt;
lvalue-only conditions are supported, count of conditions inside if()/elif() is not limited
&lt;br&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;p&gt;&lt;b&gt;&lt;div id=&quot;video-pipe&quot;&gt;&lt;/div&gt;Redurect captured video to ffmpeg input pipe&lt;/b&gt;&lt;br&gt;&lt;br&gt;
In order to use this functionality you need to install ffmpeg package (on linux) or put ffmpeg binary near quake3e executable (on windows).&lt;br&gt;
&lt;br&gt;
Use &lt;b&gt;\cl_aviPipeFormat&lt;/b&gt; to control encoder parameters passed to ffmpeg, see ffmpeg documentation for details, default value is set according to YouTube recommendations:&lt;br&gt;
&lt;pre&gt;
-preset medium -crf 23 -c:v libx264 -flags +cgop -pix_fmt yuvj420p -bf 2 -c:a aac -strict -2 -b:a 160k -movflags faststart&lt;/pre&gt;
If you need higher bitrate - decrease &lt;b&gt;-crf&lt;/b&gt; parameter, if you need better compression at cost of cpu time - set &lt;b&gt;-preset&lt;/b&gt; to &lt;i&gt;slow&lt;/i&gt; or &lt;i&gt;slower&lt;/i&gt;.&lt;br&gt;
&lt;br&gt;
And since ffmpeg can utilize all available CPU cores for faster encoding - make sure you have &lt;b&gt;\com_affinityMask&lt;/b&gt; set to 0.
&lt;br&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;div id=&quot;arr&quot;&gt;&lt;/div&gt;&lt;b&gt;Arbitrary resolution rendering&lt;/b&gt;&lt;br&gt;
&lt;br&gt;
Use &lt;b&gt;\r_renderWidth&lt;/b&gt; and &lt;b&gt;\r_renderHeight&lt;/b&gt; cvars to set persistant rendering resolution, i.e. game frame will be rendered at this resolution and later upscaled/downscaled to window size set by either &lt;b&gt;\r_mode&lt;/b&gt; or &lt;b&gt;\r_modeFullscreen&lt;/b&gt; cvars.&lt;br&gt;
Cvar &lt;b&gt;\r_renderScale&lt;/b&gt; controls upscale/downscale behavior:
&lt;ul&gt;
&lt;li&gt;0 - disabled&lt;/li&gt;
&lt;li&gt;1 - nearest filtering, stretch to full size&lt;/li&gt;
&lt;li&gt;2 - nearest filtering, preserve aspect ratio (black bars on sides)&lt;/li&gt;
&lt;li&gt;3 - linear filtering, stretch to full size&lt;/li&gt;
&lt;li&gt;4 - linear filtering, preserve aspect ratio (black bars on sides)&lt;/li&gt;
&lt;/ul&gt;
It may be useful if you want to render and record 4k+ video on HD display or if you&#039;re preferring playing at low resolution but your monitor or GPU driver can&#039;t set video|scaling mode properly.&lt;br&gt;
&lt;br&gt;
&lt;hr&gt;
&lt;div id=&quot;r_bloom&quot;&gt;&lt;/div&gt;&lt;b&gt;High-Quality Bloom&lt;/b&gt;&lt;br&gt;&lt;br&gt;
Requires &lt;b&gt;&lt;a href=&quot;#r_fbo&quot;&gt;\r_fbo 1&lt;/a&gt;&lt;/b&gt;, available operation modes via &lt;b&gt;\r_bloom&lt;/b&gt; cvar:
&lt;ul&gt;
&lt;li&gt;0 - disabled&lt;/li&gt;
&lt;li&gt;1 - enabled&lt;/li&gt;
&lt;li&gt;2 - enabled + applies to 2D/HUD elements too&lt;/li&gt;
&lt;/ul&gt;
&lt;b&gt;\r_bloom_threshold&lt;/b&gt; - color level to extract to bloom texture, default is 0.6&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\r_bloom_threshold_mode&lt;/b&gt; - color extraction mode:&lt;br&gt;
&lt;ul&gt;
&lt;li&gt;0 - (r|g|b) &gt;= threshold&lt;/li&gt;
&lt;li&gt;1 - (r+g+b)/3 &gt;= threshold&lt;/li&gt;
&lt;li&gt;2 - luma(r,g,b) &gt;= threshold&lt;/li&gt;
&lt;/ul&gt;
&lt;b&gt;\r_bloom_modulate&lt;/b&gt; - modulate extracted color:&lt;br&gt;
&lt;ul&gt;
&lt;li&gt;0 - off (color=color, i.e. no changes)&lt;/li&gt;
&lt;li&gt;1 - by itself (color=color*color)&lt;/li&gt;
&lt;li&gt;2 - by intensity (color=color*luma(color))&lt;/li&gt;
&lt;/ul&gt;
&lt;b&gt;\r_bloom_intensity&lt;/b&gt; - final bloom blend factor, default is 0.5&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\r_bloom_passes&lt;/b&gt; - count of downsampled passes (framebuffers) to blend on final bloom image, default is 5&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\r_bloom_blend_base&lt;/b&gt; - 0-based, topmost downsampled framebuffer to use for final image, high values can be used for stronger haze effect, results in overall weaker intensity&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\r_bloom_filter_size&lt;/b&gt; - filter size of Gaussian Blur effect for each pass, bigger filter size means stronger and wider blur, lower value are faster, default is 6&lt;br&gt;
&lt;br&gt;
&lt;b&gt;\r_bloom_reflection&lt;/b&gt; - bloom lens reflection effect, value is an intensity factor of the effect, negative value means blend only reflection and skip main bloom texture&lt;br&gt;
&lt;br&gt;</p><p>&lt;hr&gt;
End Of Document
&lt;hr&gt;
&lt;/html&gt;
</p>
</div>