<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Fonts Directory</h1></p><p>This directory contains TrueType (.ttf) or OpenType (.otf) font files for use in mymod menus and HUD.</p><p><h2>Recommended Fonts</h2></p><p>For best results, use modern, readable fonts:</p><p><h3>Free Fonts (Recommended)</h3>
<ul><li><strong>Roboto</strong> - Google&#039;s modern sans-serif font (excellent readability)</li>
<li><strong>Open Sans</strong> - Clean, professional sans-serif</li>
<li><strong>Source Sans Pro</strong> - Adobe&#039;s open-source font</li>
<li><strong>Noto Sans</strong> - Google&#039;s font with excellent Unicode support</li>
<li><strong>Inter</strong> - Modern UI font with excellent legibility</li></ul></p><p><h3>Font Files</h3>
Place your font files here with descriptive names:
<ul><li>`roboto-regular.ttf` - Main menu font</li>
<li>`roboto-bold.ttf` - Bold text</li>
<li>`roboto-italic.ttf` - Italic text</li></ul></p><p><h2>Font Configuration</h2></p><p>Fonts are configured in `fonts/fonts.cfg`. See that file for details.</p><p><h2>Font Sizes</h2></p><p>Recommended point sizes:
<ul><li><strong>Small font</strong>: 12-14pt (for UI elements, lists)</li>
<li><strong>Text font</strong>: 16-18pt (for menu items, buttons)</li>
<li><strong>Big font</strong>: 24-28pt (for titles, headers)</li></ul></p><p><h2>Font Rendering Quality</h2></p><p>The engine supports advanced font rendering features:
<ul><li><strong>Kerning</strong>: Automatic character spacing adjustment</li>
<li><strong>Antialiasing</strong>: Smooth text edges</li>
<li><strong>Hinting</strong>: Optimized rendering at small sizes</li>
<li><strong>DPI Scaling</strong>: Automatic scaling based on screen resolution</li></ul></p><p>Configure these via CVars:
<ul><li>`r_fontDPI` - DPI for font rendering (default: 96)</li>
<li>`r_fontKerning` - Enable kerning (default: 1)</li>
<li>`r_fontAntialiasing` - Enable antialiasing (default: 1)</li>
<li>`r_fontHinting` - Hinting mode (0=none, 1=light, 2=normal, 3=strong)</li>
<li>`r_fontAtlasSize` - Texture atlas size (256, 512, or 1024)</li></ul></p><p><h2>Font Fallback</h2></p><p>If a character is not found in the primary font, the engine will automatically use fallback fonts. Configure fallback chains in `fonts/fonts.cfg`.</p><p></p>
</div>