<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Static Analysis Workflow</h1></p><p>This document outlines the static analysis tools and workflows available for id Tech 3 to ensure code quality, catch bugs early, and maintain consistent coding standards.</p><p><h2>Available Tools</h2></p><p><h3>Clang-Tidy</h3>
<ul><li><strong>Purpose</strong>: Advanced static analysis for C/C++ code</li>
<li><strong>Capabilities</strong>: Bug detection, performance issues, code modernization</li>
<li><strong>Configuration</strong>: `.clang-tidy` file in project root</li>
<li><strong>Integration</strong>: CMake build system integration</li></ul></p><p><h3>Cppcheck</h3>
<ul><li><strong>Purpose</strong>: Static analysis tool for C/C++ code</li>
<li><strong>Capabilities</strong>: Bug detection, performance issues, unused code</li>
<li><strong>Configuration</strong>: `cppcheck.cfg` file in project root</li>
<li><strong>Integration</strong>: CMake build system integration</li></ul></p><p><h2>Quick Start</h2></p><p><h3>Automated Analysis (Recommended)</h3></p><p>```bash
<h1>Build with static analysis enabled</h1>
cd build
cmake .. -DENABLE_STATIC_ANALYSIS=ON
make</p><p><h1>Analysis runs automatically during compilation</h1>
```</p><p><h3>Manual Analysis</h3></p><p>```bash
<h1>Run clang-tidy on specific files</h1>
./tools/run_clang_tidy.sh src/common/*.c</p><p><h1>Run cppcheck with HTML report</h1>
./tools/run_cppcheck.sh --html</p><p><h1>Fix issues automatically (where possible)</h1>
./tools/run_clang_tidy.sh --fix src/client/*.c
```</p><p><h3>Selective Analysis</h3></p><p>```bash
<h1>Enable only clang-tidy</h1>
cmake .. -DENABLE_CLANG_TIDY=ON</p><p><h1>Enable only cppcheck</h1>
cmake .. -DENABLE_CPPCHECK=ON
```</p><p><h2>Configuration Files</h2></p><p><h3>.clang-tidy</h3>
The `.clang-tidy` file contains:
<ul><li><strong>Enabled checks</strong>: Bug detection, performance, portability, readability</li>
<li><strong>Disabled checks</strong>: Overly noisy checks inappropriate for game engine code</li>
<li><strong>Check options</strong>: Fine-tuned settings for specific checks</li></ul></p><p><h3>cppcheck.cfg</h3>
The `cppcheck.cfg` file contains:
<ul><li><strong>Enabled checks</strong>: All available checks</li>
<li><strong>Suppressions</strong>: Known false positives and intentional patterns</li>
<li><strong>Include paths</strong>: Proper header file locations</li>
<li><strong>Platform defines</strong>: Build system compatibility</li></ul></p><p><h2>Common Issues and Solutions</h2></p><p><h3>Clang-Tidy Issues</h3></p><p><strong>False Positive: Complex macro usage</strong>
```c
// This may trigger warnings but is necessary for QVM compatibility
#define VM_CALL(func) ((void(*)(void))func)()
```
<strong>Solution</strong>: Suppress with `// NOLINT` comments or adjust `.clang-tidy`</p><p><strong>Performance: Unnecessary copies</strong>
```c
// This might be flagged but may be required for C API compatibility
void SomeFunction(vec3_t out, const vec3_t in) {
    VectorCopy(in, out);  // May trigger performance warnings
}
```</p><p><h3>Cppcheck Issues</h3></p><p><strong>Unused functions in headers</strong>
```c
// QVM bridge functions may appear unused
void vmMain(int command, int arg0, int arg1, int arg2);  // NOLINT
```
<strong>Solution</strong>: Suppressed in `cppcheck.cfg` for known patterns</p><p><strong>Platform-specific code</strong>
```c
#ifdef _WIN32
// Windows-specific code may be flagged as unused on Linux builds
void Win32SpecificFunction() { /<em> ... </em>/ }
#endif
```</p><p><h2>CI/CD Integration</h2></p><p><h3>GitHub Actions Example</h3></p><p>```yaml
<h1>.github/workflows/static-analysis.yml</h1>
name: Static Analysis</p><p>on: [push, pull_request]</p><p>jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
<ul><li>uses: actions/checkout@v3</li>
<li>name: Install clang-tidy</li>
        </ul>run: sudo apt install -y clang-tidy
<ul><li>name: Run clang-tidy</li>
        </ul>run: |
          ./tools/run_clang_tidy.sh --quiet --output=clang_tidy.log
          if grep -q &quot;error:&quot; clang_tidy.log; then
            echo &quot;Clang-tidy found errors:&quot;
            cat clang_tidy.log
            exit 1
          fi</p><p>  cppcheck:
    runs-on: ubuntu-latest
    steps:
<ul><li>uses: actions/checkout@v3</li>
<li>name: Install cppcheck</li>
        </ul>run: sudo apt install -y cppcheck
<ul><li>name: Run cppcheck</li>
        </ul>run: |
          ./tools/run_cppcheck.sh --quiet --text
          if grep -q &quot;error:&quot; cppcheck.log; then
            echo &quot;Cppcheck found errors:&quot;
            cat cppcheck.log
            exit 1
          fi
```</p><p><h3>CMake Integration</h3></p><p>```cmake
<h1>Enable static analysis for CI builds</h1>
if(DEFINED ENV{CI})
    set(ENABLE_STATIC_ANALYSIS ON CACHE BOOL &quot;&quot; FORCE)
endif()</p><p><h1>Treat warnings as errors in CI</h1>
if(DEFINED ENV{CI})
    set(CMAKE_C_CLANG_TIDY &quot;${CLANG_TIDY_EXE}&quot; &quot;--warnings-as-errors=*&quot;)
endif()
```</p><p><h2>Development Workflow</h2></p><p><h3>Pre-commit Analysis</h3></p><p>```bash
<h1>Run quick analysis on staged files</h1>
./tools/run_clang_tidy.sh --quiet $(git diff --cached --name-only | grep &#039;\.c$&#039;)</p><p><h1>Fix issues automatically</h1>
./tools/run_clang_tidy.sh --fix $(git diff --cached --name-only | grep &#039;\.c$&#039;)
```</p><p><h3>Code Review Integration</h3>
<ul><li><strong>Pull Request Checks</strong>: Automated static analysis on PRs</li>
<li><strong>Issue Classification</strong>: Categorize findings by severity</li>
<li><strong>Fix Validation</strong>: Ensure fixes don&#039;t introduce new issues</li></ul></p><p><h3>Performance Considerations</h3>
<ul><li><strong>Incremental Analysis</strong>: Only analyze changed files</li>
<li><strong>Parallel Execution</strong>: Use multiple cores for faster analysis</li>
<li><strong>Caching</strong>: Cache analysis results between runs</li></ul></p><p><h2>Tool-Specific Configuration</h2></p><p><h3>Clang-Tidy Check Categories</h3></p><p><strong>Enabled Categories:</strong>
<ul><li>`bugprone-*`: Detect likely bugs</li>
<li>`performance-*`: Performance improvements</li>
<li>`readability-*`: Code readability</li>
<li>`modernize-*`: Modern C++ features</li>
<li>`portability-*`: Cross-platform issues</li></ul></p><p><strong>Disabled Categories:</strong>
<ul><li>`misc-no-recursion`: Game engines often use recursion appropriately</li>
<li>`readability-magic-numbers`: Game code has many domain-specific constants</li>
<li>`cppcoreguidelines-pro-type-reinterpret-cast`: Necessary for engine internals</li></ul></p><p><h3>Cppcheck Suppressions</h3></p><p><strong>Function Suppressions:</strong>
<ul><li>`unusedFunction:qvm_*`: QVM bridge functions</li>
<li>`unusedFunction:<em>SDL</em>`: SDL functions called via pointers</li>
<li>`unusedFunction:<em>Z_</em>`: Memory management functions</li></ul></p><p><strong>Platform Suppressions:</strong>
<ul><li>`unusedFunction:<em>linux</em>`: Platform-specific code</li>
<li>`unusedFunction:<em>win32</em>`: Windows-specific code</li></ul></p><p><h2>Troubleshooting</h2></p><p><h3>Common Problems</h3></p><p><strong>Clang-tidy is too slow</strong>
<ul><li>Use `--quiet` flag to reduce output</li>
<li>Analyze only changed files</li>
<li>Use parallel jobs: `clang-tidy --jobs=4`</li></ul></p><p><strong>False positives overwhelm results</strong>
<ul><li>Fine-tune `.clang-tidy` configuration</li>
<li>Use `// NOLINT` comments for known false positives</li>
<li>Add suppressions to configuration</li></ul></p><p><strong>Cppcheck misses header files</strong>
<ul><li>Ensure include paths are correct in `cppcheck.cfg`</li>
<li>Check that header files exist and are accessible</li></ul></p><p><strong>Build system conflicts</strong>
<ul><li>Static analysis can conflict with other build tools</li>
<li>Run analysis separately from regular builds</li>
<li>Use different build configurations</li></ul></p><p><h3>Debugging Analysis Issues</h3></p><p>```bash
<h1>Debug clang-tidy configuration</h1>
clang-tidy --dump-config</p><p><h1>Debug cppcheck configuration</h1>
cppcheck --check-config src/some_file.c</p><p><h1>Verbose output</h1>
./tools/run_clang_tidy.sh --verbose src/some_file.c
```</p><p><h2>Integration with Other Tools</h2></p><p><h3>Code Formatting</h3></p><p>Static analysis works alongside clang-format:</p><p>```bash
<h1>Format first, then analyze</h1>
./tools/format_code.sh
./tools/run_clang_tidy.sh
```</p><p><h3>Dynamic Analysis</h3></p><p>Static analysis complements dynamic tools:
<ul><li><strong>ASan/UBSan</strong>: Runtime memory error detection</li>
<li><strong>Valgrind</strong>: Memory leak detection</li>
<li><strong>Static Analysis</strong>: Compile-time bug detection</li></ul></p><p><h3>IDE Integration</h3></p><p><strong>VS Code:</strong>
```json
{
    &quot;clang-tidy.checks&quot;: [&quot;-<em>&quot;, &quot;bugprone-</em>&quot;, &quot;performance-*&quot;],
    &quot;cppcheck.options&quot;: [&quot;--enable=all&quot;, &quot;--suppress=missingIncludeSystem&quot;]
}
```</p><p><strong>CLion:</strong>
<ul><li>Built-in clang-tidy support</li>
<li>Configure cppcheck as external tool</li></ul></p><p><h2>Best Practices</h2></p><p><h3>Code Quality Standards</h3></p><p>1. <strong>Fix critical issues immediately</strong>
2. <strong>Review warnings regularly</strong>
3. <strong>Maintain suppression lists</strong>
4. <strong>Update configurations with new code patterns</strong></p><p><h3>Team Workflow</h3></p><p>1. <strong>Pre-commit hooks</strong>: Run basic analysis before commits
2. <strong>CI checks</strong>: Enforce quality gates on PRs
3. <strong>Regular reviews</strong>: Manual review of analysis results
4. <strong>Training</strong>: Educate team on common patterns</p><p><h3>Maintenance</h3>
<ul><li><strong>Regular updates</strong>: Keep analysis tools updated</li>
<li><strong>Configuration review</strong>: Periodically review and update configs</li>
<li><strong>Performance monitoring</strong>: Track analysis time and effectiveness</li>
<li><strong>Feedback loop</strong>: Use results to improve development practices</li></ul></p><p>This comprehensive static analysis workflow ensures high code quality, early bug detection, and maintainable code standards throughout the id Tech 3 development process.</p>
</div>