<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>Vulkan Shaders Reference</h1></p><p>This document lists all Vulkan shaders available in the id Tech 3 renderer.</p><p><h2>Ray Tracing Shaders</h2></p><p><h3>Ray Generation</h3>
<ul><li><strong>rt_primary_rays.rgen</strong> - Primary ray generation for path tracing</li></ul></p><p><h3>Miss Shaders</h3>
<ul><li><strong>rt_miss.rmiss</strong> - Default miss shader (sky sampling)</li>
<li><strong>rt_shadow.rmiss</strong> - Shadow ray miss (fully lit)</li>
<li><strong>rt_ao.rmiss</strong> - Ambient occlusion miss</li>
<li><strong>rt_reflection.rmiss</strong> - Reflection ray miss (sky reflection)</li>
<li><strong>rt_refraction.rmiss</strong> - Refraction ray miss</li></ul></p><p><h3>Closest Hit Shaders</h3>
<ul><li><strong>rt_closesthit.rchit</strong> - Main closest hit shader with PBR lighting</li>
<li><strong>rt_shadow.rchit</strong> - Shadow ray closest hit (occluded)</li>
<li><strong>rt_ao.rchit</strong> - Ambient occlusion closest hit</li>
<li><strong>rt_reflection.rchit</strong> - Reflection ray closest hit</li>
<li><strong>rt_refraction.rchit</strong> - Refraction ray closest hit</li></ul></p><p><h3>Any Hit Shaders</h3>
<ul><li><strong>rt_anyhit.rahit</strong> - Alpha testing and transparency handling</li></ul></p><p><h3>Intersection Shaders</h3>
<ul><li><strong>rt_intersection.rint</strong> - Procedural geometry intersection (spheres, boxes, cylinders)</li></ul></p><p><h3>Callable Shaders</h3>
<ul><li><strong>rt_callable_material.rchit</strong> - Material evaluation callable shader</li></ul></p><p><h2>Compute Shaders</h2></p><p><h3>Post-Processing</h3>
<ul><li><strong>gamma.comp</strong> - Gamma correction</li>
<li><strong>tonemap.comp</strong> - Tone mapping</li>
<li><strong>taa.comp</strong> - Temporal Anti-Aliasing</li>
<li><strong>fxaa.comp</strong> - Fast Approximate Anti-Aliasing</li>
<li><strong>smaa.comp</strong> - Subpixel Morphological Anti-Aliasing</li>
<li><strong>smaa_edges.comp</strong> - SMAA edge detection pass</li>
<li><strong>cas_sharpen.comp</strong> - Contrast Adaptive Sharpening (AMD FidelityFX)</li>
<li><strong>chromatic_aberration.comp</strong> - Chromatic aberration effect</li>
<li><strong>vignette.comp</strong> - Vignette effect</li>
<li><strong>lens_flare.comp</strong> - Lens flare rendering</li>
<li><strong>color_grading.comp</strong> - Color grading with LUT support</li>
<li><strong>upscale.comp</strong> - Image upscaling (bilinear, Lanczos, FSR-style)</li></ul></p><p><h3>Global Illumination</h3>
<ul><li><strong>ssgi.comp</strong> - Screen Space Global Illumination</li>
<li><strong>ssr.comp</strong> - Screen Space Reflections</li>
<li><strong>gibs_spawn.comp</strong> - GIBS surfel spawning</li>
<li><strong>gibs_update.comp</strong> - GIBS surfel irradiance updates</li></ul></p><p><h3>Effects</h3>
<ul><li><strong>motion_blur.comp</strong> - Motion blur based on velocity buffer</li>
<li><strong>depth_of_field.comp</strong> - Depth of field with bokeh</li>
<li><strong>volumetric_fog.comp</strong> - Volumetric fog/lighting</li>
<li><strong>bloom.comp</strong> - Bloom extraction</li>
<li><strong>blur.comp</strong> - Gaussian blur</li>
<li><strong>blur_subgroup.comp</strong> - Optimized blur using subgroups</li>
<li><strong>blur_gather.frag</strong> - Blur gather pass</li></ul></p><p><h3>Denoising</h3>
<ul><li><strong>rt_relax.comp</strong> - ReLAX denoising for ray tracing</li></ul></p><p><h3>Utility</h3>
<ul><li><strong>histogram.comp</strong> - Luminance histogram generation</li>
<li><strong>auto_exposure.comp</strong> - Automatic exposure adjustment</li>
<li><strong>particles.comp</strong> - GPU particle system update</li></ul></p><p><h3>Mesh Shaders</h3>
<ul><li><strong>meshlet.task</strong> - Task shader for meshlet culling</li>
<li><strong>meshlet.mesh</strong> - Mesh shader for meshlet rendering</li></ul></p><p><h2>Fragment Shaders</h2></p><p><h3>Rendering</h3>
<ul><li><strong>gen_frag.tmpl</strong> - Template for generated fragment shaders</li>
<li><strong>light_frag.tmpl</strong> - Template for lighting fragment shaders</li>
<li><strong>color.frag</strong> - Simple color rendering</li>
<li><strong>dot.frag</strong> - Dot pattern</li>
<li><strong>fog.frag</strong> - Fog rendering</li>
<li><strong>blend.frag</strong> - Blending operations</li>
<li><strong>bloom.frag</strong> - Bloom fragment shader</li>
<li><strong>gamma.frag</strong> - Gamma correction fragment shader</li></ul></p><p><h3>PBR</h3>
<ul><li><strong>brdflut.frag</strong> - BRDF lookup table generation</li>
<li><strong>irradiancecube.frag</strong> - Irradiance map generation</li>
<li><strong>prefilterenvmap.frag</strong> - Prefiltered environment map generation</li>
<li><strong>rt_composite.frag</strong> - Ray tracing composite pass</li></ul></p><p><h2>Vertex Shaders</h2>
<ul><li><strong>gen_vert.tmpl</strong> - Template for generated vertex shaders</li>
<li><strong>light_vert.tmpl</strong> - Template for lighting vertex shaders</li>
<li><strong>color.vert</strong> - Simple color vertex shader</li>
<li><strong>dot.vert</strong> - Dot pattern vertex shader</li>
<li><strong>fog.vert</strong> - Fog vertex shader</li>
<li><strong>gamma.vert</strong> - Gamma correction vertex shader</li></ul></p><p><h2>Geometry Shaders</h2>
<ul><li><strong>filtercube.geom</strong> - Cube map filtering geometry shader</li>
<li><strong>filtercube.vert</strong> - Cube map filtering vertex shader</li></ul></p><p><h2>Helper/Include Files</h2>
<ul><li><strong>rt_defines.glsl</strong> - Ray tracing constants and defines</li>
<li><strong>rt_helpers.glsl</strong> - Ray tracing helper functions</li>
<li><strong>rt_random.glsl</strong> - Random number generation for ray tracing</li>
<li><strong>gibs_surfel.glsl</strong> - GIBS surfel data structures</li>
<li><strong>gibs_sampling.glsl</strong> - GIBS surfel sampling functions</li>
<li><strong>shader_constants.glsl</strong> - Common shader constants</li></ul></p><p><h2>Shader Compilation</h2></p><p>All shaders need to be compiled to SPIR-V before use:</p><p>```bash
cd src/renderervk/shaders
./compile.sh
```</p><p>Or manually:
```bash
glslc shader_name.comp -o shader_name.spv
glslc shader_name.frag -o shader_name.spv
glslc shader_name.vert -o shader_name.spv
glslc shader_name.rgen -o shader_name.spv
glslc shader_name.rchit -o shader_name.spv
glslc shader_name.rmiss -o shader_name.spv
glslc shader_name.rahit -o shader_name.spv
glslc shader_name.rint -o shader_name.spv
```</p><p><h2>Usage Notes</h2>
<ul><li>Ray tracing shaders require `GL_EXT_ray_tracing` extension</li>
<li>Mesh shaders require `GL_EXT_mesh_shader` extension</li>
<li>Compute shaders use local workgroup sizes optimized for modern GPUs</li>
<li>Most post-processing shaders support HDR input/output</li>
<li>Many effects can be chained together in a post-processing pipeline</li></ul></p><p><h2>Performance Considerations</h2>
<ul><li>Use TAA for better quality with lower sample counts</li>
<li>FXAA is fastest but lower quality</li>
<li>SMAA provides best quality but requires multiple passes</li>
<li>CAS sharpening is very efficient and can be used with upscaling</li>
<li>SSGI/SSR are faster than full ray tracing but have limitations</li>
<li>Volumetric effects are expensive - use sparingly</li></ul></p><p></p>
</div>