<!-- Generated by md2html.php - Content Only -->
<div class="doc-content">
<p><h1>WebSocket Support</h1></p><p>This document describes the WebSocket implementation added to the id Tech 3 engine.</p><p><h2>Overview</h2></p><p>WebSocket support enables real-time bidirectional communication between the game client and servers. This is useful for:
<ul><li>Real-time chat systems</li>
<li>Live server updates</li>
<li>Remote administration</li>
<li>Real-time statistics</li>
<li>Push notifications</li></ul></p><p><h2>Implementation</h2></p><p>The WebSocket implementation uses <strong>libwebsockets</strong>, a lightweight C library that provides both client and server capabilities.</p><p><h2>Features</h2></p><p><h3>✅ Implemented</h3></p><p>1. <strong>Client Connections</strong>
<ul><li>Connect to WebSocket servers (ws:// and wss://)</li>
<li>Automatic reconnection with exponential backoff</li>
<li>Connection state management</li></ul></p><p>2. <strong>Message Handling</strong>
<ul><li>Send text messages</li>
<li>Receive messages via callbacks</li>
<li>Event callbacks (connect, disconnect, error)</li></ul></p><p>3. <strong>Configuration</strong>
<ul><li>Enable/disable WebSocket support</li>
<li>Configure auto-reconnect behavior</li>
<li>Multiple concurrent connections (up to 16)</li></ul></p><p>4. <strong>Integration</strong>
<ul><li>Integrated with engine event loop</li>
<li>Automatic service calls every frame</li>
<li>Proper cleanup on shutdown</li></ul></p><p><h2>Installation</h2></p><p><h3>Linux</h3></p><p>```bash
sudo apt-get install libwebsockets-dev
```</p><p><h3>Building from Source</h3></p><p>If your distribution doesn&#039;t have libwebsockets, build from source:</p><p>```bash
git clone https://github.com/warmcat/libwebsockets.git
cd libwebsockets
mkdir build &amp;&amp; cd build
cmake ..
make
sudo make install
```</p><p><h2>Usage</h2></p><p><h3>Basic Example</h3></p><p>```c
#include &quot;cl_net_enhanced.h&quot;</p><p>// Define callbacks
void on_message(const char <em>data, int len, void </em>user_data) {
    Com_Printf(&quot;Received: %.*s\n&quot;, len, data);
}</p><p>void on_connect(void *user_data) {
    Com_Printf(&quot;WebSocket connected!\n&quot;);
}</p><p>void on_disconnect(void *user_data) {
    Com_Printf(&quot;WebSocket disconnected!\n&quot;);
}</p><p>void on_error(const char <em>error, void </em>user_data) {
    Com_Printf(&quot;WebSocket error: %s\n&quot;, error);
}</p><p>// Connect to WebSocket server
net_websocket_t ws;
NET_WebSocket_SetCallbacks(&amp;ws, on_message, on_connect, on_disconnect, on_error, NULL);</p><p>if (NET_WebSocket_Connect(&quot;ws://example.com:8080/chat&quot;, &amp;ws)) {
    Com_Printf(&quot;Connection initiated\n&quot;);
}</p><p>// Send a message
if (NET_WebSocket_IsConnected(&amp;ws)) {
    NET_WebSocket_Send(&amp;ws, &quot;Hello, server!&quot;, 14);
}</p><p>// Disconnect
NET_WebSocket_Disconnect(&amp;ws);
```</p><p><h3>CVars</h3>
<ul><li>`cl_websocket_enable` - Enable WebSocket support (default: 1)</li>
<li>`cl_websocket_auto_reconnect` - Automatically reconnect on disconnect (default: 1)</li></ul></p><p><h3>API Reference</h3></p><p><h4>`NET_WebSocket_Init()`</h4>
Initialize WebSocket support. Called automatically if `cl_websocket_enable` is set.</p><p><h4>`NET_WebSocket_Shutdown()`</h4>
Shutdown WebSocket support and close all connections.</p><p><h4>`NET_WebSocket_Connect(const char <em>url, net_websocket_t </em>ws)`</h4>
Connect to a WebSocket server.</p><p><strong>Parameters:</strong>
<ul><li>`url` - WebSocket URL (must start with `ws://` or `wss://`)</li>
<li>`ws` - Pointer to websocket structure</li></ul></p><p><strong>Returns:</strong> `qtrue` on success, `qfalse` on failure</p><p><h4>`NET_WebSocket_Disconnect(net_websocket_t *ws)`</h4>
Disconnect from a WebSocket server.</p><p><h4>`NET_WebSocket_Send(net_websocket_t <em>ws, const char </em>data, int len)`</h4>
Send a text message to the server.</p><p><strong>Parameters:</strong>
<ul><li>`ws` - WebSocket connection</li>
<li>`data` - Message data</li>
<li>`len` - Message length (max 4096 bytes)</li></ul></p><p><strong>Returns:</strong> `qtrue` on success, `qfalse` on failure</p><p><h4>`NET_WebSocket_IsConnected(net_websocket_t *ws)`</h4>
Check if WebSocket is connected.</p><p><strong>Returns:</strong> `qtrue` if connected, `qfalse` otherwise</p><p><h4>`NET_WebSocket_Service()`</h4>
Process WebSocket events. Called automatically every frame.</p><p><h4>`NET_WebSocket_SetCallbacks(...)`</h4>
Set callback functions for WebSocket events.</p><p><strong>Callbacks:</strong>
<ul><li>`on_message` - Called when a message is received</li>
<li>`on_connect` - Called when connection is established</li>
<li>`on_disconnect` - Called when connection is closed</li>
<li>`on_error` - Called when an error occurs</li>
<li>`user_data` - User data passed to callbacks</li></ul></p><p><h2>URL Format</h2></p><p>WebSocket URLs must follow this format:
<ul><li>`ws://hostname:port/path` - Unencrypted WebSocket</li>
<li>`wss://hostname:port/path` - Encrypted WebSocket (TLS)</li></ul></p><p>Examples:
<ul><li>`ws://localhost:8080/chat`</li>
<li>`wss://example.com:443/api`</li>
<li>`ws://192.168.1.100:9000/game`</li></ul></p><p><h2>Auto-Reconnect</h2></p><p>When auto-reconnect is enabled, the WebSocket will automatically attempt to reconnect after a disconnect. The reconnect delay uses exponential backoff:
<ul><li>Initial delay: 1 second</li>
<li>Maximum delay: 30 seconds</li>
<li>Delay doubles after each failed attempt</li></ul></p><p><h2>Limitations</h2>
<ul><li>Maximum message size: 4096 bytes</li>
<li>Maximum concurrent connections: 16</li>
<li>Text messages only (binary not yet implemented)</li></ul></p><p><h2>Security Considerations</h2>
<ul><li>Use `wss://` (WebSocket Secure) for encrypted connections</li>
<li>Validate all received messages</li>
<li>Implement rate limiting for message sending</li>
<li>Sanitize user input before sending</li></ul></p><p><h2>Troubleshooting</h2></p><p><h3>Connection Fails</h3></p><p>1. Check that `cl_websocket_enable` is set to 1
2. Verify the URL format is correct
3. Ensure the server is running and accessible
4. Check firewall settings
5. For `wss://`, ensure SSL/TLS is properly configured</p><p><h3>Messages Not Received</h3></p><p>1. Ensure `NET_WebSocket_Service()` is being called (automatic in CL_Frame)
2. Check that callbacks are properly set
3. Verify the server is sending messages correctly</p><p><h3>Auto-Reconnect Not Working</h3></p><p>1. Check that `cl_websocket_auto_reconnect` is set to 1
2. Ensure `NET_WebSocket_Service()` is being called regularly
3. Check server logs for connection issues</p><p><h2>Future Enhancements</h2>
<ul><li>Binary message support</li>
<li>Subprotocol support</li>
<li>Compression (permessage-deflate)</li>
<li>Ping/pong keepalive</li>
<li>Connection pooling</li>
<li>Message queuing for offline scenarios</li></ul></p><p><h2>References</h2>
<ul><li><a href="https://libwebsockets.org/lws-api-doc-main/html/index.html">libwebsockets Documentation</a></li>
<li><a href="https://tools.ietf.org/html/rfc6455">WebSocket RFC 6455</a></li>
<li><a href="https://developer.mozilla.org/en-US/docs/Web/API/WebSocket">WebSocket API (MDN)</a></li></ul></p><p></p>
</div>