#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

MOD_DIR="$PROJECT_ROOT/examples/demo_game/mod"
OUTPUT_ROOT="$PROJECT_ROOT/build/asset-pipeline"
RELEASE_ROOT="$PROJECT_ROOT/release"
SKIP_SHADERS=0
SKIP_VALIDATE=0
SKIP_PACKAGE=0

usage() {
  cat <<EOF
Usage: $0 [mod_dir] [options]

Options:
  --output-root <dir>   Cooked output root (default: build/asset-pipeline)
  --release-root <dir>  Shipping package root (default: release)
  --skip-shaders        Skip scripts/compile_shaders.sh
  --skip-validate       Skip scripts/validate_assets.sh
  --skip-package        Skip pk3 creation/copy
  -h, --help            Show this help

Examples:
  $0
  $0 examples/demo_game/mod
  $0 examples/demo_game/mod --skip-shaders
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --output-root)
      OUTPUT_ROOT="$2"
      shift 2
      ;;
    --release-root)
      RELEASE_ROOT="$2"
      shift 2
      ;;
    --skip-shaders)
      SKIP_SHADERS=1
      shift
      ;;
    --skip-validate)
      SKIP_VALIDATE=1
      shift
      ;;
    --skip-package)
      SKIP_PACKAGE=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      if [[ "$MOD_DIR" == "$PROJECT_ROOT/examples/demo_game/mod" ]]; then
        MOD_DIR="$1"
      else
        echo "Unknown argument: $1" >&2
        usage >&2
        exit 1
      fi
      shift
      ;;
  esac
done

if [[ "$MOD_DIR" != /* ]]; then
  MOD_DIR="$PROJECT_ROOT/$MOD_DIR"
fi
if [[ "$OUTPUT_ROOT" != /* ]]; then
  OUTPUT_ROOT="$PROJECT_ROOT/$OUTPUT_ROOT"
fi
if [[ "$RELEASE_ROOT" != /* ]]; then
  RELEASE_ROOT="$PROJECT_ROOT/$RELEASE_ROOT"
fi

if [[ ! -d "$MOD_DIR" ]]; then
  echo "asset_pipeline: mod dir missing: $MOD_DIR" >&2
  exit 1
fi

CONFIG_FILE=""
for candidate in "$MOD_DIR/asset_pipeline.conf" "$(cd "$MOD_DIR/.." && pwd)/asset_pipeline.conf"; do
  if [[ -f "$candidate" ]]; then
    CONFIG_FILE="$candidate"
    break
  fi
done

ASSET_PIPELINE_MOD_NAME=""
ASSET_PIPELINE_EXTRA_DIRS=()
ASSET_PIPELINE_EXTRA_FILES=()
ASSET_PIPELINE_HOT_RELOAD_COMMANDS=()

if [[ -n "$CONFIG_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

MOD_NAME="${ASSET_PIPELINE_MOD_NAME:-$(basename "$MOD_DIR")}"
COOK_ROOT="$OUTPUT_ROOT/$MOD_NAME"
STAGE_DIR="$COOK_ROOT/stage"
PACKAGE_DIR="$COOK_ROOT/package"
LOG_DIR="$COOK_ROOT/logs"
MANIFEST="$COOK_ROOT/manifest.txt"
HOT_RELOAD_CFG="$COOK_ROOT/hot_reload.cfg"
PK3_PATH="$PACKAGE_DIR/$MOD_NAME.pk3"
RELEASE_MOD_DIR="$RELEASE_ROOT/$MOD_NAME"
RELEASE_PK3="$RELEASE_MOD_DIR/$MOD_NAME.pk3"

mkdir -p "$STAGE_DIR" "$PACKAGE_DIR" "$LOG_DIR" "$RELEASE_MOD_DIR"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"

copy_path() {
  local src="$1"
  local dest_rel="$2"
  local dest="$STAGE_DIR/$dest_rel"
  mkdir -p "$(dirname "$dest")"
  if [[ -d "$src" ]]; then
    mkdir -p "$dest"
    cp -R "$src"/. "$dest"/
  else
    cp -f "$src" "$dest"
  fi
}

copy_if_exists() {
  local rel="$1"
  if [[ -e "$MOD_DIR/$rel" ]]; then
    copy_path "$MOD_DIR/$rel" "$rel"
  fi
}

for rel in \
  default.cfg \
  autoexec.cfg \
  gameinfo.txt \
  readme_demo.txt \
  config \
  fonts \
  scripts \
  shaders \
  textures \
  models \
  players \
  ui \
  vm \
  maps \
  levelshots \
  gfx \
  sound \
  animgraph \
  loc \
  world \
  sprites \
  nav \
  fsa \
  grtx \
  mgs \
  ndgi \
  niv \
  nist \
  nslm \
  nvc \
  renderformer \
  vfgi \
  vuda \
  wsp; do
  copy_if_exists "$rel"
done

shopt -s nullglob
for cfg in "$MOD_DIR"/*.cfg; do
  copy_path "$cfg" "$(basename "$cfg")"
done
shopt -u nullglob

for rel in "${ASSET_PIPELINE_EXTRA_DIRS[@]}"; do
  if [[ -e "$PROJECT_ROOT/$rel" ]]; then
    copy_path "$PROJECT_ROOT/$rel" "$(basename "$rel")"
  elif [[ -e "$MOD_DIR/$rel" ]]; then
    copy_path "$MOD_DIR/$rel" "$(basename "$rel")"
  else
    echo "asset_pipeline: warning: extra dir missing: $rel" >&2
  fi
done

for mapping in "${ASSET_PIPELINE_EXTRA_FILES[@]}"; do
  src="${mapping%%:*}"
  dest_rel="${mapping#*:}"
  if [[ "$src" != /* ]]; then
    if [[ -e "$PROJECT_ROOT/$src" ]]; then
      src="$PROJECT_ROOT/$src"
    else
      src="$MOD_DIR/$src"
    fi
  fi
  if [[ -e "$src" ]]; then
    copy_path "$src" "$dest_rel"
  else
    echo "asset_pipeline: warning: extra file missing: $src" >&2
  fi
done

if [[ $SKIP_VALIDATE -eq 0 ]]; then
  "$PROJECT_ROOT/scripts/validate_assets.sh" "$MOD_DIR" | tee "$LOG_DIR/validate-source.log"
  "$PROJECT_ROOT/scripts/validate_assets.sh" "$STAGE_DIR" | tee "$LOG_DIR/validate-stage.log"
fi

if [[ $SKIP_SHADERS -eq 0 ]]; then
  "$PROJECT_ROOT/scripts/compile_shaders.sh" | tee "$LOG_DIR/compile-shaders.log"
fi

cat > "$HOT_RELOAD_CFG" <<EOF
// Generated by scripts/asset_pipeline.sh
// Load with: exec $(basename "$HOT_RELOAD_CFG")
vid_restart keep_window
reloadTtf
script_reload
js_reload
py_reload
cs_reload
EOF

if [[ ${#ASSET_PIPELINE_HOT_RELOAD_COMMANDS[@]} -gt 0 ]]; then
  {
    echo ""
    echo "// Project-specific reload steps"
    for cmd in "${ASSET_PIPELINE_HOT_RELOAD_COMMANDS[@]}"; do
      echo "$cmd"
    done
  } >> "$HOT_RELOAD_CFG"
fi

{
  echo "asset_pipeline_version=1"
  echo "mod_name=$MOD_NAME"
  echo "source_mod=$MOD_DIR"
  echo "stage_dir=$STAGE_DIR"
  echo "package_dir=$PACKAGE_DIR"
  echo "release_pk3=$RELEASE_PK3"
  echo "hot_reload_cfg=$HOT_RELOAD_CFG"
  echo "validate=source,stage"
  if [[ $SKIP_SHADERS -eq 0 ]]; then
    echo "shader_compile=enabled"
  else
    echo "shader_compile=skipped"
  fi
  echo "stage_files_begin"
  (
    cd "$STAGE_DIR"
    find . -type f | LC_ALL=C sort | sed 's|^\./||'
  )
  echo "stage_files_end"
} > "$MANIFEST"

if [[ $SKIP_PACKAGE -eq 0 ]]; then
  rm -f "$PK3_PATH" "$RELEASE_PK3"
  (
    cd "$STAGE_DIR"
    cmake -E tar cf "$PK3_PATH" --format=zip .
  )
  cp -f "$PK3_PATH" "$RELEASE_PK3"
fi

echo "asset_pipeline: source  -> $MOD_DIR"
echo "asset_pipeline: cooked  -> $STAGE_DIR"
echo "asset_pipeline: manifest -> $MANIFEST"
echo "asset_pipeline: hot reload -> $HOT_RELOAD_CFG"
if [[ $SKIP_PACKAGE -eq 0 ]]; then
  echo "asset_pipeline: package -> $PK3_PATH"
  echo "asset_pipeline: shipping -> $RELEASE_PK3"
fi
