#!/usr/bin/env bash
# Lists GLSL compute shaders tagged for WebGPU-class portability (wsp, mgs).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MANIFEST="$ROOT/docs/webgpu_shader_manifest.txt"
failures=0

WSP_DIR="$ROOT/renderers/vulkan/shaders/glsl/wsp"
MGS_DIR="$ROOT/renderers/vulkan/shaders/glsl/mgs"

mkdir -p "$(dirname "$MANIFEST")"

{
  echo "# Auto-generated by scripts/check_webgpu_shader_portability.sh"
  echo "# WebGPU-portable compute families (Vulkan sources today)"
  echo ""
  echo "[wsp]"
  if [[ -d "$WSP_DIR" ]]; then
    find "$WSP_DIR" -maxdepth 1 -name '*.comp' -exec basename {} \; | sort
  fi
  echo ""
  echo "[mgs]"
  if [[ -d "$MGS_DIR" ]]; then
    find "$MGS_DIR" -maxdepth 1 -name '*.comp' -exec basename {} \; | sort
  fi
} > "$MANIFEST"

count_section() {
  local tag="$1"
  grep -A999 "^\[$tag\]" "$MANIFEST" | tail -n +2 | grep -v '^\[' | grep -c '\.comp' || true
}

wsp_count="$(count_section wsp)"
mgs_count="$(count_section mgs)"

echo "WebGPU portability manifest: $MANIFEST"
echo "  wsp: $wsp_count compute shader(s)"
echo "  mgs: $mgs_count compute shader(s)"

if [[ "$wsp_count" -lt 5 ]]; then
  echo "FAIL: expected at least 5 wsp/*.comp shaders"
  failures=$((failures + 1))
fi

if [[ "$mgs_count" -lt 1 ]]; then
  echo "FAIL: expected at least 1 mgs/*.comp shader"
  failures=$((failures + 1))
fi

if [[ $failures -ne 0 ]]; then
  exit 1
fi

echo "WebGPU shader portability check passed."
