
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/tim/.local/bin/"
      - "/home/tim/.grok/bin/"
      - "/opt/devkitpro/tools/bin/"
      - "/usr/share/cursor/resources/app/node_modules/@vscode/ripgrep/bin/"
      - "/home/tim/.deno/bin/"
      - "/home/tim/.cargo/bin/"
      - "/home/tim/.nvm/versions/node/v24.14.0/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/snap/bin/"
      - "/home/tim/android-sdk/android-sdk-tools/bin/"
      - "/home/tim/android-sdk/platform-tools/"
      - "/home/tim/.lmstudio/bin/"
    searched_directories:
      - "/home/tim/.local/bin/uname"
      - "/home/tim/.grok/bin/uname"
      - "/opt/devkitpro/tools/bin/uname"
      - "/usr/share/cursor/resources/app/node_modules/@vscode/ripgrep/bin/uname"
      - "/home/tim/.deno/bin/uname"
      - "/home/tim/.cargo/bin/uname"
      - "/home/tim/.nvm/versions/node/v24.14.0/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/tim/.local/bin"
        - "/home/tim/.grok/bin"
        - "/opt/devkitpro/tools/bin"
        - "/usr/share/cursor/resources/app/node_modules/@vscode/ripgrep/bin"
        - "/home/tim/.grok/bin"
        - "/home/tim/.local/bin"
        - "/home/tim/.grok/bin"
        - "/home/tim/.deno/bin"
        - "/home/tim/.cargo/bin"
        - "/home/tim/.nvm/versions/node/v24.14.0/bin"
        - "/opt/devkitpro/tools/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/snap/bin"
        - "/snap/bin"
        - "/home/tim/android-sdk/android-sdk-tools/bin"
        - "/home/tim/android-sdk/platform-tools"
        - "/home/tim/.lmstudio/bin"
        - "/home/tim/.lmstudio/bin"
        - "/home/tim/android-sdk/android-sdk-tools/bin"
        - "/home/tim/android-sdk/platform-tools"
        - "/home/tim/.lmstudio/bin"
        - "/home/tim/android-sdk/android-sdk-tools/bin"
        - "/home/tim/android-sdk/platform-tools"
        - "/home/tim/.lmstudio/bin"
        - "/home/tim/.lmstudio/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 7.0.0-28-generic - x86_64
...
