# IdTech3Profile.cmake — apply build profile defaults after option() declarations.
# Profiles: core | game | full | research
# CI toolchains (GCC 15+ / Clang 18+) are expected to expose cxx_std_20.

function(idtech3_profile_set cache_var value)
	set(${cache_var} ${value} CACHE BOOL "Set by IDTECH3_PROFILE=${IDTECH3_PROFILE}" FORCE)
endfunction()

function(idtech3_apply_build_profile profile)
	if(profile STREQUAL "core")
		idtech3_profile_set(USE_OPEN_WORLD OFF)
		idtech3_profile_set(USE_RESEARCH_EXTENSIONS OFF)
		idtech3_profile_set(USE_FLUX OFF)
		idtech3_profile_set(USE_TRELLIS OFF)
		idtech3_profile_set(USE_GENETIC_GAN OFF)
		idtech3_profile_set(USE_EXPERIMENTAL_RENDERERS OFF)
		idtech3_profile_set(USE_FREEUSD OFF)
		idtech3_profile_set(USE_RECAST_NAV OFF)
		idtech3_profile_set(USE_GAME_AI_MIDDLEWARE OFF)
		idtech3_profile_set(USE_UBERTOOLS_COMPAT OFF)
		idtech3_profile_set(USE_BABBLE OFF)
		idtech3_profile_set(USE_TIKI OFF)
		idtech3_profile_set(BUILD_FREETYPE ON)
	elseif(profile STREQUAL "game")
		idtech3_profile_set(USE_OPEN_WORLD ON)
		idtech3_profile_set(USE_RESEARCH_EXTENSIONS OFF)
		idtech3_profile_set(USE_FLUX OFF)
		idtech3_profile_set(USE_TRELLIS OFF)
		idtech3_profile_set(USE_GENETIC_GAN OFF)
		idtech3_profile_set(USE_EXPERIMENTAL_RENDERERS OFF)
		idtech3_profile_set(USE_FREEUSD ON)
		idtech3_profile_set(USE_RECAST_NAV ON)
		idtech3_profile_set(USE_GAME_AI_MIDDLEWARE ON)
		idtech3_profile_set(USE_UBERTOOLS_COMPAT ON)
		idtech3_profile_set(USE_BABBLE ON)
		idtech3_profile_set(USE_TIKI ON)
		idtech3_profile_set(BUILD_FREETYPE ON)
	elseif(profile STREQUAL "full")
		idtech3_profile_set(USE_OPEN_WORLD ON)
		idtech3_profile_set(USE_ARC_BLANC ON)
		idtech3_profile_set(USE_RESEARCH_EXTENSIONS ON)
		idtech3_profile_set(USE_FLUX ON)
		idtech3_profile_set(USE_TRELLIS ON)
		idtech3_profile_set(USE_GENETIC_GAN ON)
		idtech3_profile_set(USE_EXPERIMENTAL_RENDERERS ON)
		idtech3_profile_set(USE_FREEUSD ON)
		idtech3_profile_set(USE_RECAST_NAV ON)
		idtech3_profile_set(USE_UBERTOOLS_COMPAT ON)
		idtech3_profile_set(USE_BABBLE ON)
		idtech3_profile_set(USE_TIKI ON)
		idtech3_profile_set(BUILD_FREETYPE ON)
	elseif(profile STREQUAL "research")
		idtech3_profile_set(USE_OPEN_WORLD ON)
		idtech3_profile_set(USE_RESEARCH_EXTENSIONS ON)
		idtech3_profile_set(USE_FLUX ON)
		idtech3_profile_set(USE_TRELLIS ON)
		idtech3_profile_set(USE_GENETIC_GAN ON)
		idtech3_profile_set(USE_EXPERIMENTAL_RENDERERS ON)
		idtech3_profile_set(USE_FREEUSD ON)
		idtech3_profile_set(USE_RECAST_NAV ON)
		idtech3_profile_set(USE_UBERTOOLS_COMPAT ON)
		idtech3_profile_set(USE_BABBLE ON)
		idtech3_profile_set(USE_TIKI ON)
		idtech3_profile_set(BUILD_FREETYPE ON)
	else()
		message(FATAL_ERROR "Unknown IDTECH3_PROFILE '${profile}' (expected core|game|full|research)")
	endif()
endfunction()

idtech3_apply_build_profile("${IDTECH3_PROFILE}")
message(STATUS "IdTech3 build profile: ${IDTECH3_PROFILE} (OPEN_WORLD=${USE_OPEN_WORLD} RESEARCH=${USE_RESEARCH_EXTENSIONS} FLUX=${USE_FLUX} EXPERIMENTAL_RENDERERS=${USE_EXPERIMENTAL_RENDERERS} ARC_BLANC=${USE_ARC_BLANC} UBERTOOLS=${USE_UBERTOOLS_COMPAT} BABBLE=${USE_BABBLE} TIKI=${USE_TIKI})")
# Chocolate Vulkan paths (MGS/WSP/SqueezeMe, Hybrid1/Raygun, ArcBlanc sources) are always
# linked; Arc Blanc needs USE_ARC_BLANC, Hybrid1/Raygun need USE_VULKAN_RTX for real RT.
