#!/usr/bin/env bash
# Guard the documented modern Vulkan default profile.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "PASS: $*"; }

CFG="config/modern_vulkan.cfg"
STABLE="config/modern_vulkan_stable.cfg"
DEFERRED_OVERLAY="config/vulkan_overlay_deferred.cfg"
RTX_OVERLAY="config/vulkan_overlay_rtx.cfg"
HYBRID_OVERLAY="config/vulkan_overlay_hybrid1.cfg"
NATIVE="config/modern_native.cfg"
TR_INIT="renderers/vulkan/tr_init.c"
TR_INIT_DIAG="renderers/vulkan/tr_init_diagnostics.inc"
DGB="renderers/vulkan/vk_deferred_gbuffer.c"
ATTACH="renderers/vulkan/vk_attachments.c"

[ -f "$CFG" ] || fail "missing $CFG"
[ -f "$STABLE" ] || fail "missing $STABLE"
[ -f "$DEFERRED_OVERLAY" ] || fail "missing $DEFERRED_OVERLAY"
[ -f "$RTX_OVERLAY" ] || fail "missing $RTX_OVERLAY"
[ -f "$HYBRID_OVERLAY" ] || fail "missing $HYBRID_OVERLAY"
[ -f "$NATIVE" ] || fail "missing $NATIVE"
[ -f "$TR_INIT_DIAG" ] || fail "missing $TR_INIT_DIAG"

grep -q 'exec modern_vulkan.cfg' "$NATIVE" || fail "modern_native must inherit modern_vulkan"
grep -q 'exec modern_vulkan_stable.cfg' "$CFG" || fail "modern_vulkan must inherit Spine stable profile"
grep -q 'modern_vulkan.cfg' scripts/compile_engine.sh || fail "release packaging must ship modern_vulkan.cfg"
grep -q 'modern_vulkan.cfg' runtime/client/core/cl_cvars.c || fail "auto profile help must mention modern_vulkan"
grep -q 'vulkan_overlay_deferred.cfg' scripts/compile_engine.sh || fail "release packaging must ship deferred overlay"
grep -q 'vulkan_overlay_rtx.cfg' scripts/compile_engine.sh || fail "release packaging must ship RTX overlay"
grep -q 'vulkan_overlay_hybrid1.cfg' scripts/compile_engine.sh || fail "release packaging must ship Hybrid1 overlay"
grep -q 'vulkan_overlay_hybrid1.cfg' runtime/client/core/cl_cvars.c || fail "auto profile help must mention Vulkan overlays"

grep -q 'seta r_fbo 1' "$STABLE" || fail "modern Vulkan must use FBO"
grep -q 'seta r_hdr 2' "$STABLE" || fail "modern Vulkan must use HDR32 default"
grep -q 'seta r_pbr 1' "$STABLE" || fail "modern Vulkan must enable PBR"
grep -q 'seta r_materialBlend 1' "$STABLE" || fail "modern Vulkan must enable material blending"
grep -q 'seta r_renderMode 2' "$STABLE" || fail "modern Vulkan stable must use Forward+ primary (mode 2)"
grep -q 'seta r_forwardPlus 1' "$STABLE" || fail "modern Vulkan must enable Forward+"
grep -q 'seta r_forwardPlusShade 1' "$STABLE" || fail "modern Vulkan must enable Forward+ shading"
grep -q 'seta r_forwardPlusDepthCull 1' "$STABLE" || fail "modern Vulkan must depth-cull Forward+ tiles"
grep -q 'seta r_deferredGBuffer 1' "$STABLE" || fail "modern Vulkan must allocate G-buffer sidecar"
grep -q 'seta r_deferredGBufferFill 1' "$STABLE" || fail "modern Vulkan must fill G-buffer sidecar"
grep -q 'seta r_deferredLighting 0' "$STABLE" || fail "modern Vulkan stable must keep deferred lighting off in mode 2"
grep -q 'seta r_aaMode 2' "$STABLE" || fail "modern Vulkan must default r_aaMode 2 (SMAA 1x)"
grep -q 'seta r_taa 0' "$STABLE" || fail "modern Vulkan must default Temporal Reconstruction off (SMAA baseline)"
grep -q 'seta r_ext_smaa 1' "$STABLE" || fail "modern Vulkan must enable SMAA"
grep -q 'seta r_taaMotionVectors 0' "$STABLE" || fail "modern Vulkan stable must leave motion-vector TAA off"
grep -q 'seta r_deferredMaterialClassify 0' "$STABLE" || fail "modern Vulkan stable must disable deferred material classify"
grep -q 'seta r_visibilityBuffer 0' "$STABLE" || fail "modern Vulkan stable must disable visibility buffer"
grep -q 'modern_clustered.cfg' scripts/compile_engine.sh || fail "release packaging must ship modern_clustered.cfg"
grep -q 'vulkan_overlay_unified_clustered.cfg' scripts/compile_engine.sh || fail "release packaging must ship unified clustered overlay"
grep -q 'seta r_tonemap 3' "$STABLE" || fail "modern Vulkan must pin Filmic tonemap"
grep -q 'seta r_post 1' "$STABLE" || fail "modern Vulkan must keep the post resolve active"
grep -q 'seta r_grade_vibrance 0' "$STABLE" || fail "modern Vulkan must default to neutral vibrance"
grep -q 'seta r_grade_hue 0' "$STABLE" || fail "modern Vulkan must default to neutral hue"
grep -q 'seta r_post_contrast 1' "$STABLE" || fail "modern Vulkan must default to neutral legacy post contrast"
grep -q 'seta r_post_saturation 1' "$STABLE" || fail "modern Vulkan must default to neutral legacy post saturation"

grep -q 'exec modern_vulkan.cfg' "$DEFERRED_OVERLAY" || fail "deferred overlay must inherit modern Vulkan"
grep -q 'seta r_renderMode 1' "$DEFERRED_OVERLAY" || fail "deferred overlay must switch to mode 1"
grep -q 'seta r_deferredLighting 1' "$DEFERRED_OVERLAY" || fail "deferred overlay must enable deferred lighting"
grep -q 'seta r_forwardPlusShade 1' "$DEFERRED_OVERLAY" || fail "deferred overlay must enable Forward+ transparent shade (opaque handoff)"
grep -q 'seta r_deferredAOCoupling 0.65' "$DEFERRED_OVERLAY" || fail "deferred overlay must enable AO-coupled dynamic lighting"
grep -q 'seta r_deferredSpecularStrength 1' "$DEFERRED_OVERLAY" || fail "deferred overlay must pin deferred specular strength"

grep -q 'exec modern_vulkan.cfg' "$RTX_OVERLAY" || fail "RTX overlay must inherit modern Vulkan"
grep -q 'seta r_rtx 1' "$RTX_OVERLAY" || fail "RTX overlay must enable r_rtx"
grep -q 'seta r_rtxDemo 1' "$RTX_OVERLAY" || fail "RTX overlay must enable shared TLAS/demo path"
grep -q 'seta r_rtxEntities 1' "$RTX_OVERLAY" || fail "RTX overlay must opt into entity BLAS"

grep -q 'exec modern_vulkan.cfg' "$HYBRID_OVERLAY" || fail "Hybrid1 overlay must inherit modern Vulkan"
grep -q 'seta r_hybrid1 1' "$HYBRID_OVERLAY" || fail "Hybrid1 overlay must enable Hybrid1"
grep -q 'seta r_rtxDemo 1' "$HYBRID_OVERLAY" || fail "Hybrid1 overlay must enable shared TLAS"
grep -q 'seta r_renderMode 1' "$HYBRID_OVERLAY" && fail "Hybrid1 overlay must not replace the modern clustered base with mode 1"
grep -q 'modern_clustered.cfg' docs/UNIFIED_CLUSTERED_RENDERER.md || fail "UNIFIED docs must mention modern_clustered.cfg"

grep -q 'r_renderMode 1/2' "$TR_INIT" || fail "cvar docs must say G-buffer works in render modes 1/2"
grep -q 'post       : post=%d tonemap=%d' "$TR_INIT_DIAG" || fail "renderer_status must expose color grading state"
grep -q 'r_grade_hue' renderers/vulkan/vk_postfx.c || fail "renderer must register hue grading cvar"
grep -q 'ri.Cmd_AddCommand( "renderer_subsystems"' "$TR_INIT" || fail "renderer_subsystems must be registered"
grep -q 'ri.Cmd_AddCommand( "renderer_modern_safe"' "$TR_INIT" || fail "renderer_modern_safe must be registered"
grep -q 'Renderer Subsystems' "$TR_INIT_DIAG" || fail "renderer_subsystems must print a subsystem health table"
grep -q 'modern profile expects r_forwardPlusDepthCull 1' "$TR_INIT_DIAG" || fail "modern compatibility must warn when Forward+ depth cull drifts off"
grep -q 'renderer_modern_safe + vid_restart' "$TR_INIT_DIAG" || fail "modern compatibility must point to modern-safe recovery"
grep -q 'R_RenderMode_WantsGBuffer' "$DGB" || fail "G-buffer active helper must use render mode profile helper"
grep -q 'R_RenderMode_WantsGBuffer' "$ATTACH" || fail "G-buffer allocation must use render mode profile helper"
grep -q 'R_RenderMode_WantsDeferredLighting' "$DGB" || fail "deferred lighting must use render mode profile helper"
grep -q 'R_LatchCvarInt( r_forwardPlusDepthCull, "r_forwardPlusDepthCull", 1 )' renderers/vulkan/tr_render_mode_vk.c || fail "mode latch must restore Forward+ depth cull in modern/clustered modes"
grep -q 'R_LatchCvarInt( r_deferredLighting, "r_deferredLighting", 0 )' renderers/vulkan/tr_render_mode_vk.c || fail "mode 2 latch must disable deferred lighting leftovers"

grep -q 'modern_vulkan.cfg' docs/RENDERERS.md || fail "RENDERERS.md must document the modern Vulkan default"
grep -q 'deferred G-buffer sidecar' docs/RENDERERS.md || fail "RENDERERS.md must document G-buffer sidecar"
grep -q 'renderer_modern_safe' docs/RENDERERS.md || fail "RENDERERS.md must document modern-safe recovery"
grep -q 'vulkan_overlay_hybrid1.cfg' docs/RENDERERS.md || fail "RENDERERS.md must document Vulkan overlays"

pass "modern Vulkan default profile contract"
