#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "PASS: $*"; }

grep -q 'Cmd_AddCommand( "p2p_status"' runtime/client/core/cl_cmds.c || fail "missing p2p_status command"
grep -q 'Cmd_AddCommand( "p2p_address"' runtime/client/core/cl_cmds.c || fail "missing p2p_address command"
grep -q 'Cmd_AddCommand( "p2p_connect"' runtime/client/core/cl_cmds.c || fail "missing p2p_connect command"
grep -q 'Cmd_AddCommand( "p2p_punch"' runtime/client/core/cl_cmds.c || fail "missing p2p_punch command"
grep -q 'Cmd_AddCommand( "p2p_punch_status"' runtime/client/core/cl_cmds.c || fail "missing p2p_punch_status command"
grep -q 'Cmd_AddCommand( "p2p_list"' runtime/client/core/cl_cmds.c || fail "missing p2p_list command"
grep -q 'Cmd_AddCommand( "p2p_sessioninfo"' runtime/client/core/cl_cmds.c || fail "missing p2p_sessioninfo command"
grep -q 'Cmd_AddCommand( "p2p_connect_browser"' runtime/client/core/cl_cmds.c || fail "missing p2p_connect_browser command"
grep -q 'net_p2pBackend' engine/core/net_p2p.c || fail "missing backend selector cvar"
grep -q 'net_p2pAdvertiseAddress' engine/core/net_p2p.c || fail "missing direct UDP advertise cvar"
grep -q 'net_p2pPunchInterval' engine/core/net_p2p.c || fail "missing direct UDP punch interval cvar"
grep -q 'NET_P2P_BeginPunchForAddress' engine/core/net_p2p.c || fail "missing direct UDP punch helper"
grep -q 'NET_P2P_HandleOobPacket' engine/core/net_p2p.c || fail "missing p2p OOB handler"
grep -q 'NET_P2P_NormalizeAddressString' engine/core/net_p2p.c || fail "missing p2p address normalizer"
grep -q 'udp:' engine/core/net_chan.c || fail "missing udp p2p address parsing"
grep -q 'Cmd_AddCommand( "p2p_status"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_status command"
grep -q 'Cmd_AddCommand( "p2p_address"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_address command"
grep -q 'Cmd_AddCommand( "p2p_punch"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_punch command"
grep -q 'Cmd_AddCommand( "p2p_punch_status"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_punch_status command"
grep -q 'NET_P2P_IsEnabled() && server->p2pAddr\\[0\\]' runtime/client/shell/cl_ui.c || grep -q 'NET_P2P_IsEnabled() && server->p2pAddr\[0\]' runtime/client/shell/cl_ui.c || fail "missing UI join preference for p2paddr"
grep -q 'LAN_ServerMatchesP2PIdentity' runtime/client/shell/cl_ui.c || fail "missing UI-side p2p identity matcher"
grep -q 'LAN_CopyKnownServerMetadata' runtime/client/shell/cl_ui.c || fail "missing favorites p2p metadata copy"
grep -q 'CL_ServerMatchesP2PIdentity' runtime/client/core/cl_serverbrowser.c || fail "missing p2p identity matcher"
grep -q 'server->p2pAvailable' runtime/client/shell/cl_ui.c || fail "missing p2p availability export to UI"
grep -q 'NET_P2P_IsAddressString' runtime/client/shell/cl_ui.c || fail "missing generic p2p address detection in UI"
grep -q 'Cvar_Get( "net_p2p"' engine/core/net_sdr.c || fail "missing net_p2p cvar alias"
grep -q 'NET_P2P_GetLocalAddressString' engine/core/net_p2p.c || fail "missing p2p wrapper"
grep -q 'SteamShared_Init' engine/core/steam_shared.c || fail "missing shared Steam bootstrap"
grep -q 'p2paddr' runtime/server/core/sv_main.c || fail "missing advertised p2p info key"
grep -q 'p2psession' runtime/server/core/sv_main.c || fail "missing advertised p2p session id"
grep -q 'p2psecure' runtime/server/core/sv_main.c || fail "missing advertised anti-cheat posture"
grep -q 'sv_p2pReconnectWindow' runtime/server/core/sv_init.c || fail "missing server reconnect policy cvar"
grep -q 'NET_P2P_HandleOobPacket' runtime/client/core/cl_connect.c || fail "missing client p2p OOB hook"
grep -q 'NET_P2P_HandleOobPacket' runtime/server/core/sv_main.c || fail "missing server p2p OOB hook"
grep -q 'NET_P2P_PrintPathStatus' runtime/client/core/cl_cmds.c || fail "missing path status in client p2p status"
grep -q 'NET_P2P_PrintPathStatus' runtime/server/core/sv_ccmds.c || fail "missing path status in server p2p status"
grep -Fq 'usage: p2p_list [local|global|favorites|master]' runtime/client/core/cl_cmds.c || fail "missing p2p_list usage text"
grep -Fq 'usage: p2p_sessioninfo <local|global|favorites> <index>' runtime/client/core/cl_cmds.c || fail "missing p2p_sessioninfo usage text"
grep -Fq 'usage: p2p_connect <steamid|steam:steamid|host:port|udp:host:port>' runtime/client/core/cl_cmds.c || fail "missing generic p2p_connect usage text"
grep -Fq 'usage: p2p_punch <host:port|udp:host:port>' runtime/client/core/cl_cmds.c || fail "missing p2p_punch usage text"
grep -q 'p2p_connect_browser <local|global|favorites> <index>' docs/P2P_NETWORKING.md || fail "missing P2P browser docs"
grep -q 'p2p_sessioninfo <local|global|favorites> <index>' docs/P2P_NETWORKING.md || fail "missing P2P sessioninfo docs"
grep -q 'p2psession' docs/P2P_NETWORKING.md || fail "missing session contract docs"
grep -q 'NET_P2P_Init' engine/core/net_ip.c || fail "missing NET_P2P_Init in NET_Init"
grep -q 'NET_P2P_Shutdown' engine/core/net_ip.c || fail "missing NET_P2P_Shutdown in NET_Shutdown"
grep -q 'NET_P2P_UsesSteamSdrBackend' engine/core/net_p2p.h || fail "missing steam backend selector export"
grep -q 'NET_P2P_UsesSteamSdrBackend' engine/core/net_sdr.c || fail "missing SDR backend gate"
grep -q 'digits >= 15' engine/core/net_p2p.c || fail "missing bare SteamID64 guard in address normalizer"
grep -q 'Cmd_AddCommand( "p2p_connect"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_connect command"
grep -q 'Cmd_AddCommand( "p2p_list"' runtime/server/core/sv_ccmds.c || fail "missing dedicated p2p_list command"
grep -q 'Cmd_AddCommand( "p2p_candidates"' runtime/client/core/cl_cmds.c || fail "missing p2p_candidates command"
grep -q 'NET_P2P_NatTryHandlePacket' engine/core/net_p2p_nat.c || fail "missing STUN packet handler"
grep -q 'NET_P2P_EnsurePunchPeer' engine/core/net_p2p.c || fail "missing symmetric punch peer helper"
grep -q 'inbound punch from' engine/core/net_p2p.c || fail "missing inbound symmetric punch logging"
grep -q 'net_p2pStun' engine/core/net_p2p_nat.c || fail "missing STUN cvar"
grep -q 'net_p2pTurn' engine/core/net_p2p_nat.c || fail "missing TURN cvar"
grep -q 'ICE-lite' docs/P2P_NETWORKING.md || fail "missing ICE docs"
grep -q 'p2p_list master' docs/P2P_NETWORKING.md || fail "missing master browse docs"
test -f engine/core/net_p2p_stun_codec.c || fail "missing STUN codec module"
grep -q 'NET_P2P_StunBuildBindingRequest' engine/core/net_p2p_stun_codec.c || fail "missing STUN binding builder"
grep -q 'NET_P2P_BeginConnectPath' engine/core/net_p2p.c || fail "missing ICE connect path entry"
grep -q 'p2pCheck' engine/core/net_p2p_ice.c || fail "missing ICE connectivity check OOB"
grep -q 'ignoring candidates from unexpected peer' engine/core/net_p2p_ice.c || fail "missing ICE peer ownership guard for candidates"
grep -q 'ignoring check ack from unexpected peer' engine/core/net_p2p_ice.c || fail "missing ICE peer ownership guard for check acks"
grep -q 'cl_p2pAutoReconnect' runtime/client/core/cl_p2p_session.c || fail "missing auto-reconnect cvar"
grep -q 'SV_P2P_HandleReconnectRequest' runtime/server/client/sv_client.c || fail "missing server P2P reconnect handler"
grep -q 'p2pMigrate' runtime/client/core/cl_p2p_session.c || fail "missing host migration handler"
grep -q 'NET_P2P_TurnAppendMessageIntegrity' engine/core/net_p2p_turn_auth.c || fail "missing TURN auth module"
grep -q 'test_p2p_nat_sim' CMakeLists.txt || fail "missing NAT sim ctest registration"
grep -q 'test_p2p_reconnect' CMakeLists.txt || fail "missing reconnect ctest registration"
grep -q 'test_p2p_migrate' CMakeLists.txt || fail "missing migrate ctest registration"
grep -q 'test_p2p_ice_guard' CMakeLists.txt || fail "missing ICE guard ctest registration"
grep -q 'net_p2pIceDeferConnect' engine/core/net_p2p_ice.c || fail "missing ICE defer-connect cvar"
grep -q 'NET_P2P_ConnectIsDeferred' engine/core/net_p2p.h || fail "missing deferred-connect export"
grep -q 'NET_P2P_ConsumeDeferredConnect' runtime/client/core/cl_p2p_session.c || fail "missing deferred-connect consume in session frame"
grep -q 'NET_P2P_BeginConnectPath' runtime/server/core/sv_ccmds.c || fail "missing dedicated ICE connect path"
test -f tests/scripts/test_p2p_reconnect.sh || fail "missing reconnect test script"
test -f tests/scripts/test_p2p_migrate.sh || fail "missing migrate test script"
test -f tests/scripts/test_p2p_ice_guard.sh || fail "missing ICE guard test script"
test -f config/vulkan_overlay_p2p_direct_udp.cfg || fail "missing direct_udp P2P overlay"
test -f examples/demo_game/mod/demo_p2p_direct_udp.cfg || fail "missing direct_udp P2P demo"
test -f .github/workflows/p2p-nat.yml || fail "missing P2P NAT workflow"
test -f docs/P2P_NAT_TESTING.md || fail "missing NAT testing docs"
grep -q 'net_p2pIceDeferConnect' docs/P2P_NETWORKING.md || fail "missing defer-connect docs"
grep -q 'demo_p2p_direct_udp' docs/P2P_NETWORKING.md || fail "missing direct_udp demo docs"

pass "optional P2P networking wrapper, commands, and docs are present"
