#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
source "$(dirname "$0")/idtech3_test_paths.sh"
idtech3_test_paths_init "$ROOT"

VT="$(idtech3_file renderers/vulkan/vk_vt.c src/renderers/vulkan/vk_vt.c)"
SPARSE="$(idtech3_file renderers/vulkan/vk_sparse.c src/renderers/vulkan/vk_sparse.c)"
INST="$(idtech3_file renderers/vulkan/vk_instance.c src/renderers/vulkan/vk_instance.c)"
TR="$(idtech3_file renderers/vulkan/tr_init.c src/renderers/vulkan/tr_init.c)"
STREAM="$(idtech3_file renderers/vulkan/tr_bsp_stream.c src/renderers/vulkan/tr_bsp_stream.c)"
CMDS="$(idtech3_file renderers/vulkan/tr_cmds.c src/renderers/vulkan/tr_cmds.c)"
BE="$(idtech3_file renderers/vulkan/tr_backend.c src/renderers/vulkan/tr_backend.c)"

grep -q 'r_vt' "$VT"
grep -q 'r_vtSparse' "$VT"
grep -q 'r_vtFeedback' "$VT"
grep -q 'r_vtVirtualPages' "$VT"
grep -q 'r_vtPhysicalPages' "$VT"
grep -q 'vt_status' "$VT"
grep -q 'vt_load' "$VT"
grep -q 'R_LoadPNG' "$VT"
grep -q 'R_VT_WantSample' "$VT"
grep -q 'R_VT_Feedback_EndFrame' "$VT"
grep -q 'vk_sparse_bind_page' "$VT"
grep -q 'atomicOr\|VT_Feedback_DispatchGpu\|vt_feedback_cs_spv' "$VT"
grep -q 'R_VT_Init' "$TR"
grep -q 'R_VT_Shutdown' "$TR"
grep -q 'sparseResidencyImage2D' "$INST"
grep -q 'sparseBinding' "$INST"
grep -q 'vkQueueBindSparse\|qvkQueueBindSparse' "$INST"
grep -q 'vk_sparse_create_image2d' "$SPARSE"
grep -q 'qvkQueueBindSparse' "$SPARSE"
grep -q 'R_VT_Feedback_RequestUV' "$STREAM"
grep -q 'R_VT_Feedback_BeginFrame' "$CMDS"
grep -q 'R_VT_Feedback_EndFrame' "$BE"
test -f "$ROOT/docs/VIRTUAL_TEXTURE.md"
test -f "$ROOT/examples/demo_game/mod/demo_vt.cfg"
test -f "$ROOT/examples/demo_game/bootstrap_media/vt/page0.png"
test -f "$ROOT/renderers/vulkan/shaders/glsl/vt_feedback.comp"
test -f "$ROOT/renderers/vulkan/vk_vt_feedback_spirv.inc"
grep -q 'r_vtSparse' "$ROOT/examples/demo_game/mod/demo_vt.cfg"
grep -q 'sparse' "$ROOT/docs/VIRTUAL_TEXTURE.md"
grep -q 'atomicOr' "$ROOT/docs/VIRTUAL_TEXTURE.md"
echo "test_vt.sh: ok"
