#!/usr/bin/env bash
# Hybrid Rendering 1 scaffolding checks
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
# shellcheck source=idtech3_test_paths.sh
source "$(dirname "$0")/idtech3_test_paths.sh"
idtech3_test_paths_init "$ROOT"

HYBRID="$(idtech3_file renderers/vulkan/extensions/rtx/vk_hybrid1.c src/renderers/vulkan/extensions/rtx/vk_hybrid1.c)"
TR_INIT="$(idtech3_file renderers/vulkan/tr_init.c src/renderers/vulkan/tr_init.c)"
SPIRV="$(idtech3_file renderers/vulkan/extensions/rtx/vk_hybrid1_spirv.inc src/renderers/vulkan/extensions/rtx/vk_hybrid1_spirv.inc)"
HIT="$(idtech3_file renderers/vulkan/shaders/glsl/hybrid1/hybrid1_hit.glsl src/renderers/vulkan/shaders/glsl/hybrid1/hybrid1_hit.glsl)"
DIFFUSE="$(idtech3_file renderers/vulkan/shaders/glsl/hybrid1/hybrid1_diffuse.rgen src/renderers/vulkan/shaders/glsl/hybrid1/hybrid1_diffuse.rgen)"

grep -q 'vk_hybrid1_record_pass' "$HYBRID"
grep -q 'r_hybrid1_historyClamp' "$TR_INIT"
grep -q 'hybrid1_temporal.comp' "$ROOT/scripts/compile_shaders.sh"
test -f "$ROOT/docs/HYBRID_RENDERING1.md"
test -f "$SPIRV"
test -f "$HIT"
grep -q 'WorldAlbedoSSBO' "$HIT"
grep -q 'r_hybrid1_ibl' "$TR_INIT"
grep -q 'r_hybrid1_motion' "$TR_INIT"
grep -q 'r_hybrid1_restir' "$TR_INIT"
grep -q 'r_hybrid1_restir' "$HYBRID"
grep -q 'restir_reservoir' "$HYBRID"
grep -q 'HYBRID1_RecordRestir' "$HYBRID"
grep -q 'hybrid1_restir.comp' "$HYBRID"
grep -q 'hybrid1_restir.comp' "$ROOT/scripts/compile_shaders.sh"
grep -q 'r_rtxBindless", "1"' "$TR_INIT" || grep -q "r_rtxBindless\", \"1\"" "$TR_INIT"
grep -q 'r_hybrid1_phiColor' "$TR_INIT"
grep -q 'r_hybrid1_rayBias' "$TR_INIT"
grep -q 'r_hybrid1_depthTol' "$TR_INIT"
grep -q 'r_hybrid1_sunRadius' "$TR_INIT"
grep -q 'r_hybrid1_ggx' "$TR_INIT"
grep -q 'r_hybrid1_dlightShadows' "$TR_INIT"
grep -q 'r_hybrid1_glint' "$TR_INIT"
grep -q 'r_glintSampleBudget' "$HYBRID"
grep -q 'r_hybrid1_glint' "$HYBRID"
grep -q 'glint_ndf.glsl' "$ROOT/renderers/vulkan/shaders/glsl/hybrid1/hybrid1_spec.rgen"
grep -q 'params4' "$HYBRID"
test -f "$ROOT/docs/RTX_HIT_SHADER_UV.md"
grep -q 'brdflut' "$HYBRID"
grep -q 'forward_plus.buffer' "$HYBRID"
grep -q 'hybrid1_sampleEnvBRDF' "$ROOT/renderers/vulkan/shaders/glsl/hybrid1/hybrid1_ibl.glsl"
grep -q 'Hybrid1FpLights' "$ROOT/renderers/vulkan/shaders/glsl/hybrid1/hybrid1_shadow.rgen"
grep -q 'hybrid1_reset' "$HYBRID"
grep -q 'hybrid1_reload' "$HYBRID"
grep -q 'HYBRID1_StateString' "$HYBRID"
grep -q 'waiting: shared RTX TLAS not ready' "$HYBRID"
grep -q 'ready: all trace channels disabled' "$HYBRID"
grep -q 'HYBRID1_ConsumeCvarResets' "$HYBRID"
grep -q 'params2' "$HYBRID"
grep -q 'vk_rtx_bind_world_albedo_ssbo' "$HYBRID"
test -f "$DIFFUSE"
test -f "$ROOT/examples/demo_game/mod/demo_hybrid1.cfg"

PT="$(idtech3_file renderers/vulkan/extensions/rtx/vk_pathtrace.c src/renderers/vulkan/extensions/rtx/vk_pathtrace.c)"
grep -q 'pathtrace_status' "$PT"
grep -q 'r_pathtrace_denoiseStrength' "$TR_INIT"
grep -q 'r_pathtrace_denoiseDepthTol' "$TR_INIT"

echo "test_hybrid1.sh: ok"
