#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

fail() { echo "FAIL: $*" >&2; exit 1; }

CFG="$ROOT/config/demo_deferred_many_lights.cfg"
SCENE="$ROOT/renderers/vulkan/tr_scene.c"
INIT="$ROOT/renderers/vulkan/tr_init.c"
LOCAL="$ROOT/renderers/vulkan/tr_local.h"
DOC="$ROOT/docs/DEFERRED_MANY_LIGHTS_DEMO.md"
STAGE="$ROOT/scripts/compile_engine.sh"
READBACK="$ROOT/renderers/vulkan/vk_read_pixels.c"
COMMON="$ROOT/renderers/vulkan/shaders/glsl/deferred_lighting_common.glsl"
FORWARD="$ROOT/renderers/vulkan/shaders/glsl/forward_plus_light_eval.glsl"
INIT="$ROOT/renderers/vulkan/tr_init.c"

[[ -f "$CFG" ]] || fail "demo config missing"
[[ -f "$DOC" ]] || fail "demo docs missing"

grep -q 'seta r_renderMode 3' "$CFG" || fail "demo must use unified deferred clustered mode"
grep -q 'seta r_deferredLighting 1' "$CFG" || fail "deferred lighting must be enabled"
grep -q 'seta r_gbufferQuality 2' "$CFG" || fail "demo must request full-fidelity G-buffer quality"
grep -q 'seta r_ext_multisample 0' "$CFG" || fail "demo must disable MSAA for direct G-buffer export"
grep -q 'seta r_ssao 0' "$CFG" || fail "demo must avoid legacy SSAO ownership"
grep -q 'seta r_ambientVisibilityMode 0' "$CFG" || fail "demo must avoid ambient-visibility ownership conflict"
grep -q 'seta r_classicLighting 0' "$CFG" || fail "demo must disable classic lighting ownership"
grep -q 'seta cl_autoGraphicsProfile 0' "$CFG" || fail "demo must disable QVM graphics profile override"
grep -q 'seta r_deferredLightDemo 1' "$CFG" || fail "demo light injector must be enabled"
grep -q 'seta r_deferredLightDemoCount 64' "$CFG" || fail "demo should exercise 64 lights"
grep -q 'seta r_deferredLightDemoDistance 520' "$CFG" || fail "demo distance default missing"
grep -q 'seta r_deferredLightDemoEnergy 1.25' "$CFG" || fail "demo energy tuning missing"
grep -q 'seta r_textureMode GL_LINEAR_MIPMAP_LINEAR' "$CFG" || fail "demo must use trilinear texture filtering"
grep -q 'float radial = clamp( 1.0 - dr \* dr, 0.0, 1.0 )' "$COMMON" || fail "deferred point lights must use bounded radial falloff"
grep -q 'return radial \* radial \* ( 3.0 - 2.0 \* radial )' "$COMMON" || fail "deferred point lights must use smooth radial falloff"
grep -q 'float radial = clamp( 1.0 - dr \* dr, 0.0, 1.0 )' "$FORWARD" || fail "Forward+ point lights must share deferred radial falloff"
grep -q 'att = radial \* radial \* ( 3.0 - 2.0 \* radial )' "$FORWARD" || fail "Forward+ point lights must share smooth radial falloff"
grep -q 'r_textureMode = ri.Cvar_Get( "r_textureMode", "GL_LINEAR_MIPMAP_LINEAR"' "$INIT" || fail "renderer default must use trilinear filtering"
grep -q 'seta r_forwardPlusDebug 0$' "$CFG" || fail "demo should default to clean lighting captures"
grep -q 'set r_forwardPlusDebug 0.35' "$CFG" || fail "demo docs/config should retain opt-in occupancy proof"
grep -q '^wait 120$' "$CFG" || fail "demo must wait out post-devmap restart debounce"
grep -q '^vid_restart keep_window$' "$CFG" || fail "demo must apply latched deferred renderer mode"
grep -q '^set r_classicLighting 0$' "$CFG" || fail "demo must reassert non-classic lighting after QVM profile"

grep -q 'R_AddDeferredLightDemoLights' "$SCENE" || fail "scene injector missing"
grep -q 'R_DeferredLightDemoStatus_f' "$SCENE" || fail "status command implementation missing"
grep -q 'HUD/weapon/UI' "$SCENE" || fail "demo status must preserve world-scene light count"
grep -q 'deferred_many_lights_status' "$INIT" || fail "status command registration missing"
grep -q 'r_deferredLightDemoCount' "$LOCAL" || fail "cvar declarations missing"
grep -q 'r_deferredLightDemoDistance' "$LOCAL" || fail "distance cvar declaration missing"
grep -q 'r_deferredLightDemoEnergy' "$LOCAL" || fail "energy cvar declaration missing"
grep -q 'demo_deferred_many_lights.cfg' "$STAGE" || fail "compile_engine staging list missing demo cfg"
grep -q 'dest/baseoa' "$ROOT/scripts/compile_engine.sh" || fail "release staging must include OpenArena baseoa"
grep -q 'cluster_status' "$DOC" || fail "docs must include runtime proof command"
grep -q 'dm4ish_clustered_lighting' "$DOC" || fail "docs must include clustered lighting capture"
grep -q 'dm4ish_forwardplus_occupancy' "$DOC" || fail "docs must include occupancy capture"
grep -q 'dm4ish_deferred_gbuffer' "$DOC" || fail "docs must include G-buffer capture"
grep -q 'VK_TIMEOUT' "$READBACK" || fail "screenshot readback must bound WSI fence wait"

echo "PASS: deferred many-lights demo"
