#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
H="$ROOT/renderers/vulkan/extensions/scaffold/vk_hair_deferred.c"
HH="$ROOT/renderers/vulkan/extensions/scaffold/vk_hair_deferred.h"
DOC="$ROOT/docs/HAIR_DEFERRED.md"
CFG="$ROOT/config/vulkan_overlay_hair_deferred.cfg"
SHADER="$ROOT/renderers/vulkan/shaders/glsl/hair_deferred/hair_lod.comp"
VIS_SHADER="$ROOT/renderers/vulkan/shaders/glsl/hair_deferred/hair_visibility_atomic.comp"

grep -q 'vkHairBundle_t' "$HH"
grep -q 'visibilityBits' "$HH"
grep -q 'r_hairDeferred' "$H"
grep -q 'hair_deferred_status' "$H"
grep -q 'vk.forward_plus.tile_buffer' "$H"
grep -q '64-bit' "$DOC"
grep -q 'contract_only' "$DOC"
grep -q 'r_hairDeferred 1' "$CFG"
grep -q 'HairBundles' "$SHADER"
grep -q 'dispatchData' "$SHADER"
grep -q 'uint64_t' "$VIS_SHADER"
grep -q 'atomicMin' "$VIS_SHADER"
grep -q 'hair_lod.comp' "$ROOT/scripts/compile_shaders.sh"
grep -q 'hair_visibility_atomic.comp' "$ROOT/scripts/compile_shaders.sh"
echo "test_hair_deferred.sh: ok"
