#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

fail() { echo "FAIL: $*" >&2; exit 1; }
pass() { echo "PASS: $*"; }

grep -q 'Cmd_AddCommand( "p2p_status"' runtime/client/core/cl_cmds.c || fail "missing p2p_status command"
grep -q 'Cmd_AddCommand( "p2p_address"' runtime/client/core/cl_cmds.c || fail "missing p2p_address command"
grep -q 'Cmd_AddCommand( "p2p_connect"' runtime/client/core/cl_cmds.c || fail "missing p2p_connect command"
grep -q 'Cmd_AddCommand( "p2p_punch"' runtime/client/core/cl_cmds.c || fail "missing p2p_punch command"
grep -q 'Cmd_AddCommand( "p2p_punch_status"' runtime/client/core/cl_cmds.c || fail "missing p2p_punch_status command"
grep -q 'Cmd_AddCommand( "p2p_list"' runtime/client/core/cl_cmds.c || fail "missing p2p_list command"
grep -q 'Cmd_AddCommand( "p2p_connect_browser"' runtime/client/core/cl_cmds.c || fail "missing p2p_connect_browser command"
grep -q 'net_p2pBackend' engine/core/net_p2p.c || fail "missing backend selector cvar"
grep -q 'net_p2pAdvertiseAddress' engine/core/net_p2p.c || fail "missing direct UDP advertise cvar"
grep -q 'net_p2pPunchInterval' engine/core/net_p2p.c || fail "missing direct UDP punch interval cvar"
grep -q 'NET_P2P_BeginPunchForAddress' engine/core/net_p2p.c || fail "missing direct UDP punch helper"
grep -q 'NET_P2P_HandleOobPacket' engine/core/net_p2p.c || fail "missing p2p OOB handler"
grep -q 'NET_P2P_NormalizeAddressString' engine/core/net_p2p.c || fail "missing p2p address normalizer"
grep -q 'udp:' engine/core/net_chan.c || fail "missing udp p2p address parsing"
grep -q 'Cmd_AddCommand( "p2p_status"' runtime/server/sv_ccmds.c || fail "missing dedicated p2p_status command"
grep -q 'Cmd_AddCommand( "p2p_address"' runtime/server/sv_ccmds.c || fail "missing dedicated p2p_address command"
grep -q 'Cmd_AddCommand( "p2p_punch"' runtime/server/sv_ccmds.c || fail "missing dedicated p2p_punch command"
grep -q 'Cmd_AddCommand( "p2p_punch_status"' runtime/server/sv_ccmds.c || fail "missing dedicated p2p_punch_status command"
grep -q 'NET_P2P_IsEnabled() && server->p2pAddr\\[0\\]' runtime/client/cl_ui.c || grep -q 'NET_P2P_IsEnabled() && server->p2pAddr\[0\]' runtime/client/cl_ui.c || fail "missing UI join preference for p2paddr"
grep -q 'LAN_ServerMatchesP2PIdentity' runtime/client/cl_ui.c || fail "missing UI-side p2p identity matcher"
grep -q 'LAN_CopyKnownServerMetadata' runtime/client/cl_ui.c || fail "missing favorites p2p metadata copy"
grep -q 'CL_ServerMatchesP2PIdentity' runtime/client/core/cl_serverbrowser.c || fail "missing p2p identity matcher"
grep -q 'server->p2pAvailable' runtime/client/cl_ui.c || fail "missing p2p availability export to UI"
grep -q 'NET_P2P_IsAddressString' runtime/client/cl_ui.c || fail "missing generic p2p address detection in UI"
grep -q 'Cvar_Get( "net_p2p"' engine/core/net_sdr.c || fail "missing net_p2p cvar alias"
grep -q 'NET_P2P_GetLocalAddressString' engine/core/net_p2p.c || fail "missing p2p wrapper"
grep -q 'SteamShared_Init' engine/core/steam_shared.c || fail "missing shared Steam bootstrap"
grep -q 'p2paddr' runtime/server/sv_main.c || fail "missing advertised p2p info key"
grep -q 'NET_P2P_HandleOobPacket' runtime/client/core/cl_connect.c || fail "missing client p2p OOB hook"
grep -q 'NET_P2P_HandleOobPacket' runtime/server/sv_main.c || fail "missing server p2p OOB hook"
grep -Fq 'usage: p2p_list [local|global|favorites]' runtime/client/core/cl_cmds.c || fail "missing p2p_list usage text"
grep -Fq 'usage: p2p_connect <steamid|steam:steamid|host:port|udp:host:port>' runtime/client/core/cl_cmds.c || fail "missing generic p2p_connect usage text"
grep -Fq 'usage: p2p_punch <host:port|udp:host:port>' runtime/client/core/cl_cmds.c || fail "missing p2p_punch usage text"
grep -q 'p2p_connect_browser <local|global|favorites> <index>' docs/P2P_NETWORKING.md || fail "missing P2P browser docs"
grep -q 'NET_P2P_Init' engine/core/net_ip.c || fail "missing NET_P2P_Init in NET_Init"
grep -q 'NET_P2P_Shutdown' engine/core/net_ip.c || fail "missing NET_P2P_Shutdown in NET_Shutdown"
grep -q 'NET_P2P_UsesSteamSdrBackend' engine/core/net_p2p.h || fail "missing steam backend selector export"
grep -q 'NET_P2P_UsesSteamSdrBackend' engine/core/net_sdr.c || fail "missing SDR backend gate"
grep -q 'digits >= 15' engine/core/net_p2p.c || fail "missing bare SteamID64 guard in address normalizer"
grep -q 'server->adr.port == 0 && !server->p2pAddr' runtime/client/core/cl_cmds.c || fail "missing p2p-only browser join guard"

pass "optional P2P networking wrapper, commands, and docs are present"
