#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
source "$(dirname "$0")/idtech3_test_paths.sh"
idtech3_test_paths_init "$ROOT"

ML="$(idtech3_file renderers/vulkan/vk_meshlets.c src/renderers/vulkan/vk_meshlets.c)"
MESH="$(idtech3_file renderers/vulkan/tr_mesh.c src/renderers/vulkan/tr_mesh.c)"
SURF="$(idtech3_file renderers/vulkan/tr_surface.c src/renderers/vulkan/tr_surface.c)"
TR="$(idtech3_file renderers/vulkan/tr_init.c src/renderers/vulkan/tr_init.c)"
DRAW="$(idtech3_file renderers/vulkan/vk_draw_state.c src/renderers/vulkan/vk_draw_state.c)"
PROCS="$(idtech3_file renderers/vulkan/vk_procs.h src/renderers/vulkan/vk_procs.h)"
INST="$(idtech3_file renderers/vulkan/vk_instance.c src/renderers/vulkan/vk_instance.c)"
HDR="$(idtech3_file renderers/vulkan/vk_meshlets.h src/renderers/vulkan/vk_meshlets.h)"
SHADER="$ROOT/renderers/vulkan/shaders/glsl/meshlet_cull_indirect.comp"

grep -q 'r_meshlets' "$ML"
grep -q 'r_virtualGeometry' "$ML"
grep -q 'meshlet_status' "$ML"
grep -q 'R_Meshlets_Bake' "$ML"
grep -q 'R_CullMD3SurfaceMeshlets' "$MESH"
grep -q 'R_Meshlets_CacheLocal' "$ML"
grep -q 'R_Meshlets_PackIndirect' "$ML"
grep -q 'r_meshletsMdi' "$ML"
grep -q 'r_meshletsMdiDraw' "$ML"
grep -q 'R_Meshlets_AppendVisibleIndexes' "$ML"
grep -q 'r_meshletsCompact' "$ML"
grep -q 'R_Meshlets_AppendVisibleIndexes' "$SURF"
grep -q 'R_Meshlets_Init' "$TR"
grep -q 'R_Meshlets_TryDrawIndirect' "$ML"
grep -q 'R_Meshlets_TryDrawIndirect' "$DRAW"
grep -q 'qvkCmdDrawIndexedIndirect' "$PROCS"
grep -q 'vkCmdDrawIndexedIndirect' "$INST"
grep -q 'VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT' "$ML"
grep -q 'VK_BUFFER_USAGE_INDEX_BUFFER_BIT' "$ML"
grep -q 'R_Meshlets_RegisterPersistentIndexes' "$HDR"
grep -q 'r_meshletsGpuCull' "$ML"
grep -q 'r_meshletsStreaming' "$ML"
grep -q 'r_meshletsBsp' "$ML"
grep -q 'r_meshletsSkinned' "$ML"
grep -q 'meshlet_cull_indirect_cs' "$ROOT/scripts/compile_shaders.sh"
grep -q 'atomicAdd' "$SHADER"
grep -q 'sphereVisible' "$SHADER"
grep -q 'textureLod' "$SHADER"
grep -q 'drawCount' "$SHADER"
grep -q 'r_meshletsLod' "$ML"
grep -q 'r_meshletsLodPixels' "$ML"
grep -q 'Meshlet_PassesScreenLod' "$ML"
grep -q 'frame != 0' "$MESH"
grep -q 'oldframe != 0' "$ML"
grep -q 'R_Meshlets_BeginSurface' "$ML"
grep -q 'VK_SPINE_PASS_VIRTUAL_GEOMETRY_CULL' "$ML"
grep -q 'VK_SPINE_PASS_VIRTUAL_GEOMETRY_DRAW' "$ML"
test -f "$ROOT/docs/MESHLETS.md"
test -f "$ROOT/examples/demo_game/mod/demo_meshlets.cfg"
echo "test_meshlets.sh: ok"
