#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
bash "$ROOT/tests/scripts/test_renderer_iq_p1.sh"
bash "$ROOT/tests/scripts/test_renderer_iq_profile.sh"
bash "$ROOT/tests/scripts/test_bloom_source_contract.sh"
bash "$ROOT/tests/scripts/test_bloom_firefly_control.sh"
bash "$ROOT/tests/scripts/test_temporal_history_registry.sh"
bash "$ROOT/tests/scripts/test_renderer_p1_cert_levels.sh"
bash "$ROOT/tests/scripts/test_iq_live_cert_contract.sh"
bash "$ROOT/tests/scripts/test_iq_firefly_metrics.sh"
bash "$ROOT/tests/scripts/test_iq_edge_metrics.sh"
bash "$ROOT/tests/scripts/test_iq_temporal_history_live.sh"
bash "$ROOT/tests/scripts/test_p1_live_state_machine.sh"
bash "$ROOT/tests/scripts/test_p1_live_preflight.sh"
bash "$ROOT/tests/scripts/test_p1_fixture_visibility.sh"
bash "$ROOT/tests/scripts/test_p1_readback_identity.sh"
bash "$ROOT/tests/scripts/test_p1_final_promotion.sh"
bash "$ROOT/tests/scripts/test_p1_evidence_invalidation.sh"
bash "$ROOT/tests/scripts/test_p1_failure_bundles.sh"
grep -q 'RENDERER_P1' "$ROOT/docs/RENDERER_P1_CERTIFICATION.md"
grep -q 'IMAGE_QUALITY_CERTIFIED' "$ROOT/docs/RENDERER_IQ_LIVE_CERTIFICATION.md"
grep -q 'state machine' "$ROOT/docs/RENDERER_IQ_LIVE_CERTIFICATION.md"
echo "test_renderer_p1_certification.sh OK"
